package com.nec.asia.nic.enquiry.controller;

/**
 * NicUploadJob generated by hbm2java
 */
public class NicUploadJobInfo implements java.io.Serializable {

	public static final String RECORD_STATUS_IN_PROGRESS 	= "01";
	public static final String RECORD_STATUS_COMPLETED 		= "02";
	public static final String RECORD_STATUS_REJECTED 		= "04";
	
	
	private long uploadJobId;
	private String transactionId;
	private String transactionStatus;
	private String jobType;
	private String jobUploadDateTime;
	private String jobCurrentState;
	private String jobStartDateTime;
	private String jobEndDateTime;
	private String cpdCheckStatus;
	private String afisRegisterStatus;
	private String afisCheckStatus;
	private String investigationType;
	private String investigationStatus;
	private String investigationOfficerId;
	private String syncTxCpdStatus;
	private String dataPreparationStatus;
	private String persoRegisterStatus;
	private Boolean nicJobCompletedFlag;
	private String syncInventoryStatus;
	private String syncCardCpdStatus;
	private Boolean issuanceJobCompletedFlag;
	private String createBy;
	private String createWkstnId;
	private String createDateTime;
	private String updateBy;
	private String updateWkstnId;
	private String updateDateTime;
	private String afisDeleteStatus;
	private Integer jobReprocessCount;
	
	private String jobTxnId;
	private String regSiteDesc;
	
	private Boolean nicJobErrorFlag;
	private String jobCurrentStatus;
	private String afisVerifyStatus;
	private String errorDesc;
	


	public long getUploadJobId() {
		return this.uploadJobId;
	}

	public void setUploadJobId(long uploadJobId) {
		this.uploadJobId = uploadJobId;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	public String getJobUploadDateTime() {
		return this.jobUploadDateTime;
	}

	public void setJobUploadDateTime(String jobUploadDateTime) {
		this.jobUploadDateTime = jobUploadDateTime;
	}

	public String getJobCurrentState() {
		return this.jobCurrentState;
	}

	public void setJobCurrentState(String jobCurrentState) {
		this.jobCurrentState = jobCurrentState;
	}

	public String getJobStartDateTime() {
		return this.jobStartDateTime;
	}

	public void setJobStartDateTime(String jobStartDateTime) {
		this.jobStartDateTime = jobStartDateTime;
	}

	public String getJobEndDateTime() {
		return this.jobEndDateTime;
	}

	public void setJobEndDateTime(String jobEndDateTime) {
		this.jobEndDateTime = jobEndDateTime;
	}

	public String getCpdCheckStatus() {
		return this.cpdCheckStatus;
	}

	public void setCpdCheckStatus(String cpdCheckStatus) {
		this.cpdCheckStatus = cpdCheckStatus;
	}

	public String getAfisRegisterStatus() {
		return this.afisRegisterStatus;
	}

	public void setAfisRegisterStatus(String afisRegisterStatus) {
		this.afisRegisterStatus = afisRegisterStatus;
	}

	public String getAfisCheckStatus() {
		return this.afisCheckStatus;
	}

	public void setAfisCheckStatus(String afisCheckStatus) {
		this.afisCheckStatus = afisCheckStatus;
	}

	public String getInvestigationType() {
		return this.investigationType;
	}

	public void setInvestigationType(String investigationType) {
		this.investigationType = investigationType;
	}

	public String getInvestigationStatus() {
		return this.investigationStatus;
	}

	public void setInvestigationStatus(String investigationStatus) {
		this.investigationStatus = investigationStatus;
	}

	public String getInvestigationOfficerId() {
		return this.investigationOfficerId;
	}

	public void setInvestigationOfficerId(String investigationOfficerId) {
		this.investigationOfficerId = investigationOfficerId;
	}

	public String getSyncTxCpdStatus() {
		return this.syncTxCpdStatus;
	}

	public void setSyncTxCpdStatus(String syncTxCpdStatus) {
		this.syncTxCpdStatus = syncTxCpdStatus;
	}

	public String getDataPreparationStatus() {
		return this.dataPreparationStatus;
	}

	public void setDataPreparationStatus(String dataPreparationStatus) {
		this.dataPreparationStatus = dataPreparationStatus;
	}

	public String getPersoRegisterStatus() {
		return this.persoRegisterStatus;
	}

	public void setPersoRegisterStatus(String persoRegisterStatus) {
		this.persoRegisterStatus = persoRegisterStatus;
	}

	public Boolean getNicJobCompletedFlag() {
		return this.nicJobCompletedFlag;
	}

	public void setNicJobCompletedFlag(Boolean nicJobCompletedFlag) {
		this.nicJobCompletedFlag = nicJobCompletedFlag;
	}

	public String getSyncInventoryStatus() {
		return this.syncInventoryStatus;
	}

	public void setSyncInventoryStatus(String syncInventoryStatus) {
		this.syncInventoryStatus = syncInventoryStatus;
	}

	public String getSyncCardCpdStatus() {
		return this.syncCardCpdStatus;
	}

	public void setSyncCardCpdStatus(String syncCardCpdStatus) {
		this.syncCardCpdStatus = syncCardCpdStatus;
	}

	public Boolean getIssuanceJobCompletedFlag() {
		return this.issuanceJobCompletedFlag;
	}

	public void setIssuanceJobCompletedFlag(Boolean issuanceJobCompletedFlag) {
		this.issuanceJobCompletedFlag = issuanceJobCompletedFlag;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public String getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(String createDateTime) {
		this.createDateTime = createDateTime;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public String getUpdateDateTime() {
		return this.updateDateTime;
	}

	public void setUpdateDateTime(String updateDateTime) {
		this.updateDateTime = updateDateTime;
	}

	
	public String getAfisDeleteStatus() {
		return afisDeleteStatus;
	}

	public void setAfisDeleteStatus(String afisDeleteStatus) {
		this.afisDeleteStatus = afisDeleteStatus;
	}

	public Integer getJobReprocessCount() {
		return jobReprocessCount;
	}

	public void setJobReprocessCount(Integer jobReprocessCount) {
		this.jobReprocessCount = jobReprocessCount;
	}

	public String getJobTxnId() {
		return jobTxnId;
	}

	public void setJobTxnId(String jobTxnId) {
		this.jobTxnId = jobTxnId;
	}

	public String getRegSiteDesc() {
		return regSiteDesc;
	}

	public void setRegSiteDesc(String regSiteDesc) {
		this.regSiteDesc = regSiteDesc;
	}

	/**
	 * @return the jobCurrentStatus
	 */
	public String getJobCurrentStatus() {
		return jobCurrentStatus;
	}

	/**
	 * @param jobCurrentStatus the jobCurrentStatus to set
	 */
	public void setJobCurrentStatus(String jobCurrentStatus) {
		this.jobCurrentStatus = jobCurrentStatus;
	}

	/**
	 * @return the afisVerifyStatus
	 */
	public String getAfisVerifyStatus() {
		return afisVerifyStatus;
	}

	/**
	 * @param afisVerifyStatus the afisVerifyStatus to set
	 */
	public void setAfisVerifyStatus(String afisVerifyStatus) {
		this.afisVerifyStatus = afisVerifyStatus;
	}

	/**
	 * @return the nicJobErrorFlag
	 */
	public Boolean getNicJobErrorFlag() {
		return nicJobErrorFlag;
	}

	/**
	 * @param nicJobErrorFlag the nicJobErrorFlag to set
	 */
	public void setNicJobErrorFlag(Boolean nicJobErrorFlag) {
		this.nicJobErrorFlag = nicJobErrorFlag;
	}

	/**
	 * @return the errorDesc
	 */
	public String getErrorDesc() {
		return errorDesc;
	}

	/**
	 * @param errorDesc the errorDesc to set
	 */
	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	public String getTransactionStatus() {
		return transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}
	

}
