package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicTransaction generated by hbm2java
 */
public class FeeRecieptPayment implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private long id;
	private String recieptNo;
	private String typePayment;
	private String description;
	private Double price;
	private String unit;
	private Integer amount;
	private Double total;
	private Date createDate;
	private String createBy;
	private Date updateDate;
	private String updateBy;
	private String rmPaymentFlag;
	private String createByName;
	
	public FeeRecieptPayment(long id, String recieptNo, String typePayment,
			String description, Double price, String unit, Integer amount,
			Double total, Date createDate, String createBy, Date updateDate,
			String updateBy, String rmPaymentFlag, String createByName) {
		super();
		this.id = id;
		this.recieptNo = recieptNo;
		this.typePayment = typePayment;
		this.description = description;
		this.price = price;
		this.unit = unit;
		this.amount = amount;
		this.total = total;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.rmPaymentFlag = rmPaymentFlag;
		this.createByName = createByName;
	}

	public String getCreateByName() {
		return createByName;
	}

	public void setCreateByName(String createByName) {
		this.createByName = createByName;
	}

	public FeeRecieptPayment() {
	}

	public FeeRecieptPayment(long id, String recieptNo, String typePayment,
			String description, Double price, String unit, Integer amount,
			Double total, Date createDate, String createBy, Date updateDate,
			String updateBy, String rmPaymentFlag) {
		super();
		this.id = id;
		this.recieptNo = recieptNo;
		this.typePayment = typePayment;
		this.description = description;
		this.price = price;
		this.unit = unit;
		this.amount = amount;
		this.total = total;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.rmPaymentFlag = rmPaymentFlag;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRecieptNo() {
		return recieptNo;
	}

	public void setRecieptNo(String recieptNo) {
		this.recieptNo = recieptNo;
	}

	public String getTypePayment() {
		return typePayment;
	}

	public void setTypePayment(String typePayment) {
		this.typePayment = typePayment;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Double getTotal() {
		return total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getRmPaymentFlag() {
		return rmPaymentFlag;
	}

	public void setRmPaymentFlag(String rmPaymentFlag) {
		this.rmPaymentFlag = rmPaymentFlag;
	}
}
