package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicFPData generated by hbm2java
 */
public class NicFPData implements java.io.Serializable {

	private static final long serialVersionUID = 1666676631975973049L;
	
	private NicFPDataId id;
	private String siteCode;
	private Date dateOfApplication;
	private String createBy;
	private Date createDatetime;
	private String fpIndicator;
	private Integer quality;
	private Integer verifyScore;
	private Long docId;

	public NicFPData() {
	}

	public NicFPData(NicFPDataId id) {
		this.id = id;
	}

	public NicFPData(NicFPDataId id, String siteCode, Date dateOfApplication, String createBy, Date createDatetime,
			String fpIndicator, Integer quality, Integer verifyScore, Long docId) {
		this.id = id;
		this.siteCode = siteCode;
		this.dateOfApplication = dateOfApplication;
		this.createBy = createBy;
		this.createDatetime = createDatetime;
		this.fpIndicator = fpIndicator;
		this.quality = quality;
		this.verifyScore = verifyScore;
		this.docId = docId;
	}

	public NicFPDataId getId() {
		return this.id;
	}

	public void setId(NicFPDataId id) {
		this.id = id;
	}

	public String getSiteCode() {
		return this.siteCode;
	}

	public void setSiteCode(String siteCode) {
		this.siteCode = siteCode;
	}

	public Date getDateOfApplication() {
		return this.dateOfApplication;
	}

	public void setDateOfApplication(Date dateOfApplication) {
		this.dateOfApplication = dateOfApplication;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getFpIndicator() {
		return this.fpIndicator;
	}

	public void setFpIndicator(String fpIndicator) {
		this.fpIndicator = fpIndicator;
	}

	public Integer getQuality() {
		return this.quality;
	}

	public void setQuality(Integer quality) {
		this.quality = quality;
	}

	public Integer getVerifyScore() {
		return this.verifyScore;
	}

	public void setVerifyScore(Integer verifyScore) {
		this.verifyScore = verifyScore;
	}

	public Long getDocId() {
		return this.docId;
	}

	public void setDocId(Long docId) {
		this.docId = docId;
	}

}
