package com.nec.asia.nic.comp.immihistory.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.nec.asia.nic.comp.immihistory.model.ImmihistoryImage;

/**
 * NicDecisionManager generated by hbm2java
 */

@XmlRootElement(name = "ImmiHistoryImages")
@XmlAccessorType(XmlAccessType.FIELD)
public class ImmiHistoryImages implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    @XmlElement(name = "id") 
    private Long id;
    @XmlElement(name = "createdBy") 
    private String createdBy;
    @XmlElement(name = "lastModifiedBy") 
    private String lastModifiedBy;
    @XmlElement(name = "createdTime") 
    private Date createdTime;
    @XmlElement(name = "lastModifiedTime") 
    private Date lastModifiedTime;
    @XmlElement(name="immihistoryId")
    private Long immihistoryId;
    @XmlElement(name="type")
    private String type;
    @XmlElement(name="data")
    private byte[] data;
    
	public ImmiHistoryImages() {
		super();
	}
	
	public ImmiHistoryImages(ImmihistoryImage img) {
		//this.id = img.getId();
		this.createdBy = img.getCreatedBy();
		this.lastModifiedBy = img.getLastModifiedBy();
		this.createdTime = img.getCreatedTime();
		this.lastModifiedTime = img.getLastModifiedTime();
		//this.immihistoryId = img.getImmihistoryId();
		this.type = img.getType();
		this.data = img.getData();
	}

	public ImmiHistoryImages(Long id, String createdBy, String lastModifiedBy,
			Date createdTime, Date lastModifiedTime, Long immihistoryId,
			String type, byte[] data) {
		super();
		this.id = id;
		this.createdBy = createdBy;
		this.lastModifiedBy = lastModifiedBy;
		this.createdTime = createdTime;
		this.lastModifiedTime = lastModifiedTime;
		this.immihistoryId = immihistoryId;
		this.type = type;
		this.data = data;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastModifiedBy() {
		return lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getLastModifiedTime() {
		return lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public Long getImmihistoryId() {
		return immihistoryId;
	}

	public void setImmihistoryId(Long immihistoryId) {
		this.immihistoryId = immihistoryId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public byte[] getData() {
		return data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	
}
