<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.ws.dx.nic.asia.nec.com/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:ns2="http://schemas.xmlsoap.org/soap/http"
	xmlns:ns1 = "http://ws.dx.nic.asia.nec.com/"
	name="idserverWSImplService" targetNamespace="http://impl.ws.dx.nic.asia.nec.com/">
	<wsdl:import location = "idserverWS.wsdl" namespace = "http://ws.dx.nic.asia.nec.com/"/>
	<wsdl:binding name="idserverWSImplServiceSoapBinding" type="ns1:idserverWS">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="identification">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="identification">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="identificationResponse">
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="faultException">
				<soap:fault name="faultException" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="verification">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="verification">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="verificationResponse">
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="faultException">
				<soap:fault name="faultException" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="idserverWSImplService">
		<wsdl:port binding="tns:idserverWSImplServiceSoapBinding" name="idserverWSImplPort">
			<soap:address location="http://localhost:8080/mnic-ws/services/idserver" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>