package com.nec.asia.nic.framework.report.domain;

// Generated Jun 14, 2013 12:38:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VNicTransactionId generated by hbm2java
 */
public class VNicTransactionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nin;
	private String applnRefNo;
	private String transactionType;
	private String transactionSubtype;
	private String transactionStatus;
	private Date   dateOfApplication;
	private String transactionId;
	private String firstnameFull;
	private String surnameFull;
	private String surnameBirthFull;
	private String gender;
	private Date   dateOfBirth;
	private String regOfficerId;

	public VNicTransactionId() {
	}

	public VNicTransactionId(String nin, String transactionId) {
		this.nin = nin;
		this.transactionId = transactionId;
	}

	public VNicTransactionId(String nin, String applnRefNo,
			String transactionType, String transactionSubtype,
			String transactionStatus, Date dateOfApplication,
			String transactionId, String firstnameFull, String surnameFull,
			String surnameBirthFull, String gender, Date dateOfBirth,
			String regOfficerId) {
		this.nin = nin;
		this.applnRefNo = applnRefNo;
		this.transactionType = transactionType;
		this.transactionSubtype = transactionSubtype;
		this.transactionStatus = transactionStatus;
		this.dateOfApplication = dateOfApplication;
		this.transactionId = transactionId;
		this.firstnameFull = firstnameFull;
		this.surnameFull = surnameFull;
		this.surnameBirthFull = surnameBirthFull;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.regOfficerId = regOfficerId;
	}

	public String getNin() {
		return this.nin;
	}

	public void setNin(String nin) {
		this.nin = nin;
	}

	public String getApplnRefNo() {
		return this.applnRefNo;
	}

	public void setApplnRefNo(String applnRefNo) {
		this.applnRefNo = applnRefNo;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getTransactionSubtype() {
		return this.transactionSubtype;
	}

	public void setTransactionSubtype(String transactionSubtype) {
		this.transactionSubtype = transactionSubtype;
	}

	public String getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public Date getDateOfApplication() {
		return this.dateOfApplication;
	}

	public void setDateOfApplication(Date dateOfApplication) {
		this.dateOfApplication = dateOfApplication;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getFirstnameFull() {
		return this.firstnameFull;
	}

	public void setFirstnameFull(String firstnameFull) {
		this.firstnameFull = firstnameFull;
	}

	public String getSurnameFull() {
		return this.surnameFull;
	}

	public void setSurnameFull(String surnameFull) {
		this.surnameFull = surnameFull;
	}

	public String getSurnameBirthFull() {
		return this.surnameBirthFull;
	}

	public void setSurnameBirthFull(String surnameBirthFull) {
		this.surnameBirthFull = surnameBirthFull;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getRegOfficerId() {
		return this.regOfficerId;
	}

	public void setRegOfficerId(String regOfficerId) {
		this.regOfficerId = regOfficerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VNicTransactionId))
			return false;
		VNicTransactionId castOther = (VNicTransactionId) other;

		return ((this.getNin() == castOther.getNin()) || (this.getNin() != null
				&& castOther.getNin() != null && this.getNin().equals(
				castOther.getNin())))
				&& ((this.getApplnRefNo() == castOther.getApplnRefNo()) || (this
						.getApplnRefNo() != null
						&& castOther.getApplnRefNo() != null && this
						.getApplnRefNo().equals(castOther.getApplnRefNo())))
				&& ((this.getTransactionType() == castOther
						.getTransactionType()) || (this.getTransactionType() != null
						&& castOther.getTransactionType() != null && this
						.getTransactionType().equals(
								castOther.getTransactionType())))
				&& ((this.getTransactionSubtype() == castOther
						.getTransactionSubtype()) || (this
						.getTransactionSubtype() != null
						&& castOther.getTransactionSubtype() != null && this
						.getTransactionSubtype().equals(
								castOther.getTransactionSubtype())))
				&& ((this.getTransactionStatus() == castOther
						.getTransactionStatus()) || (this
						.getTransactionStatus() != null
						&& castOther.getTransactionStatus() != null && this
						.getTransactionStatus().equals(
								castOther.getTransactionStatus())))
				&& ((this.getDateOfApplication() == castOther
						.getDateOfApplication()) || (this
						.getDateOfApplication() != null
						&& castOther.getDateOfApplication() != null && this
						.getDateOfApplication().equals(
								castOther.getDateOfApplication())))
				&& ((this.getTransactionId() == castOther.getTransactionId()) || (this
						.getTransactionId() != null
						&& castOther.getTransactionId() != null && this
						.getTransactionId()
						.equals(castOther.getTransactionId())))
				&& ((this.getFirstnameFull() == castOther.getFirstnameFull()) || (this
						.getFirstnameFull() != null
						&& castOther.getFirstnameFull() != null && this
						.getFirstnameFull()
						.equals(castOther.getFirstnameFull())))
				&& ((this.getSurnameFull() == castOther.getSurnameFull()) || (this
						.getSurnameFull() != null
						&& castOther.getSurnameFull() != null && this
						.getSurnameFull().equals(castOther.getSurnameFull())))
				&& ((this.getSurnameBirthFull() == castOther
						.getSurnameBirthFull()) || (this.getSurnameBirthFull() != null
						&& castOther.getSurnameBirthFull() != null && this
						.getSurnameBirthFull().equals(
								castOther.getSurnameBirthFull())))
				&& ((this.getGender() == castOther.getGender()) || (this
						.getGender() != null && castOther.getGender() != null && this
						.getGender().equals(castOther.getGender())))
				&& ((this.getDateOfBirth() == castOther.getDateOfBirth()) || (this
						.getDateOfBirth() != null
						&& castOther.getDateOfBirth() != null && this
						.getDateOfBirth().equals(castOther.getDateOfBirth())))
				&& ((this.getRegOfficerId() == castOther.getRegOfficerId()) || (this
						.getRegOfficerId() != null
						&& castOther.getRegOfficerId() != null && this
						.getRegOfficerId().equals(castOther.getRegOfficerId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNin() == null ? 0 : this.getNin().hashCode());
		result = 37
				* result
				+ (getApplnRefNo() == null ? 0 : this.getApplnRefNo()
						.hashCode());
		result = 37
				* result
				+ (getTransactionType() == null ? 0 : this.getTransactionType()
						.hashCode());
		result = 37
				* result
				+ (getTransactionSubtype() == null ? 0 : this
						.getTransactionSubtype().hashCode());
		result = 37
				* result
				+ (getTransactionStatus() == null ? 0 : this
						.getTransactionStatus().hashCode());
		result = 37
				* result
				+ (getDateOfApplication() == null ? 0 : this
						.getDateOfApplication().hashCode());
		result = 37
				* result
				+ (getTransactionId() == null ? 0 : this.getTransactionId()
						.hashCode());
		result = 37
				* result
				+ (getFirstnameFull() == null ? 0 : this.getFirstnameFull()
						.hashCode());
		result = 37
				* result
				+ (getSurnameFull() == null ? 0 : this.getSurnameFull()
						.hashCode());
		result = 37
				* result
				+ (getSurnameBirthFull() == null ? 0 : this
						.getSurnameBirthFull().hashCode());
		result = 37 * result
				+ (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37
				* result
				+ (getDateOfBirth() == null ? 0 : this.getDateOfBirth()
						.hashCode());
		result = 37
				* result
				+ (getRegOfficerId() == null ? 0 : this.getRegOfficerId()
						.hashCode());
		return result;
	}

}
