package com.nec.asia.nic.comp.trans.domain;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicMain generated by hbm2java
 */
/* 
 * Modification History:
 * 
 * 02 Aug 2013 (chris): Add Columns OPTION_SURNAME, ADDRESS_LINE5, ADDRESS_LINE6, PREFERRED_MAILING_ADDRESS, OVERSEAS_ADDRESS, OVERSEAS_COUNTRY
 * 23 Aug 2013 (chris): change date of issue from string type to date type
 */
@Deprecated
public class NicMain implements java.io.Serializable {

	public static final int DEFAULT_GEN_NO = 0;
	public static final int DEFAULT_UPDATE_NO = 0;
	
	private long nicId;
	private String transactionId;
	private String nin;
	private int genNo;
	private int updateNo;
	private Date dateOfApplication;
	private Date prevDateOfIssue;
	private Date dateOfIssue;
	private String ccn;
	private Short samKeyVersion;
	private String cardStatus;
	private Date cardStatusChangeTime;
	private String cardStatusChangeReason;
	private String surname;
	private String firstname;
	private String surnameBirth;
	private String optionSurname; //refer to code table
	private Date dateOfBirth;
	private String printDob;
	private String gender;
	private String maritalStatus;
	private String nicAddr1;
	private String nicAddr2;
	private String nicAddr3;
	private String nicAddr4;
	private String nicAddr5;
	private String nicAddr6;
	private String preferredMailingAddress;
	private String overseasAddress;
	private String overseasCountry;
	
	private String fatherName;
	private String fatherSurname;
	private String fatherNin;
	private String motherName;
	private String motherSurname;
	private String motherNin;
	private String spouseName;
	private String spouseSurname;
	private String spouseNin;
	private String scIndicator;
	private Integer totalFp;
	private String fpIndicator;
	private String fpEncode;
	private String fpQuality;
	private Long fp01DocId;
	private Long fp02DocId;
	private Long fp03DocId;
	private Long fp04DocId;
	private Long fp05DocId;
	private Long fp06DocId;
	private Long fp07DocId;
	private Long fp08DocId;
	private Long fp09DocId;
	private Long fp10DocId;
	private Long mnu1DocId;
	private Long mnu2DocId;
	private Long mnu3DocId;
	private Long mnu4DocId;
	private String facialIndicator;
	private Long facialCapDocId;
	private Long facialGreyDocId;
	private Long facialChipDocId;
	private String signatureIndicator;
	private String signatureFp;
	private Long signatureDocId;
	private Long persoDocId;
	private Long scFormDocId;
	private Long scBirthExtDocId;
	private Long scMarCertDocId;
	private Long scAddrProofDocId;
	private Set nicChangeNinLogs = new HashSet(0);
	private Set nicHistories = new HashSet(0);
	private Set nicRegistrationDatas = new HashSet(0);

	public NicMain() {
	}

	public NicMain(long nicId, String transactionId, String nin,
			int genNo) {
		this.nicId = nicId;
		this.transactionId = transactionId;
		this.nin = nin;
		this.genNo = genNo;
	}

	public NicMain(long nicId, String transactionId, String nin,
			int genNo, int updateNo, String ccn, Short samKeyVersion,
			Date dateOfApplication,
			Date dateOfIssue, Date prevDateOfIssue, String cardStatus,
			Date cardStatusChangeTime, String cardStatusChangeReason,
			String surname, String firstname, String surnameBirth,
			Date dateOfBirth, String printDob, String gender,
			String maritalStatus, String nicAddr1, String nicAddr2,
			String nicAddr3, String nicAddr4, String fatherName,
			String fatherSurname, String fatherNin, String motherName,
			String motherSurname, String motherNin, String spouseName,
			String spouseSurname, String spouseNin, String scIndicator,
			Integer totalFp, String fpIndicator, String fpEncode,
			String fpQuality, Long fp01DocId, Long fp02DocId,
			Long fp03DocId, Long fp04DocId, Long fp05DocId,
			Long fp06DocId, Long fp07DocId, Long fp08DocId,
			Long fp09DocId, Long fp10DocId, Long mnu1DocId,
			Long mnu2DocId, Long mnu3DocId, Long mnu4DocId,
			String facialIndicator, Long facialCapDocId,
			Long facialGreyDocId, Long facialChipDocId,
			String signatureIndicator, String signatureFp,
			Long signatureDocId, Long persoDocId,
			Long scFormDocId, Long scBirthExtDocId,
			Long scMarCertDocId, Long scAddrProofDocId,
			Set nicChangeNinLogs, Set nicHistories, Set nicRegistrationDatas) {
		this.nicId = nicId;
		this.transactionId = transactionId;
		this.nin = nin;
		this.genNo = genNo;
		this.updateNo = updateNo;
		this.ccn = ccn;
		this.samKeyVersion = samKeyVersion;
		//this.dateOfIssue = dateOfIssue;
		//this.prevDateOfIssue = prevDateOfIssue;
		this.cardStatus = cardStatus;
		this.cardStatusChangeTime = cardStatusChangeTime;
		this.cardStatusChangeReason = cardStatusChangeReason;
		this.surname = surname;
		this.firstname = firstname;
		this.surnameBirth = surnameBirth;
		this.dateOfBirth = dateOfBirth;
		this.printDob = printDob;
		this.gender = gender;
		this.maritalStatus = maritalStatus;
		this.nicAddr1 = nicAddr1;
		this.nicAddr2 = nicAddr2;
		this.nicAddr3 = nicAddr3;
		this.nicAddr4 = nicAddr4;
		this.fatherName = fatherName;
		this.fatherSurname = fatherSurname;
		this.fatherNin = fatherNin;
		this.motherName = motherName;
		this.motherSurname = motherSurname;
		this.motherNin = motherNin;
		this.spouseName = spouseName;
		this.spouseSurname = spouseSurname;
		this.spouseNin = spouseNin;
		this.scIndicator = scIndicator;
		this.totalFp = totalFp;
		this.fpIndicator = fpIndicator;
		this.fpEncode = fpEncode;
		this.fpQuality = fpQuality;
		this.fp01DocId = fp01DocId;
		this.fp02DocId = fp02DocId;
		this.fp03DocId = fp03DocId;
		this.fp04DocId = fp04DocId;
		this.fp05DocId = fp05DocId;
		this.fp06DocId = fp06DocId;
		this.fp07DocId = fp07DocId;
		this.fp08DocId = fp08DocId;
		this.fp09DocId = fp09DocId;
		this.fp10DocId = fp10DocId;
		this.mnu1DocId = mnu1DocId;
		this.mnu2DocId = mnu2DocId;
		this.mnu3DocId = mnu3DocId;
		this.mnu4DocId = mnu4DocId;
		this.facialIndicator = facialIndicator;
		this.facialCapDocId = facialCapDocId;
		this.facialGreyDocId = facialGreyDocId;
		this.facialChipDocId = facialChipDocId;
		this.signatureIndicator = signatureIndicator;
		this.signatureFp = signatureFp;
		this.signatureDocId = signatureDocId;
		this.persoDocId = persoDocId;
		this.scFormDocId = scFormDocId;
		this.scBirthExtDocId = scBirthExtDocId;
		this.scMarCertDocId = scMarCertDocId;
		this.scAddrProofDocId = scAddrProofDocId;
		this.nicChangeNinLogs = nicChangeNinLogs;
		this.nicHistories = nicHistories;
		this.nicRegistrationDatas = nicRegistrationDatas;
	}

	public long getNicId() {
		return this.nicId;
	}

	public void setNicId(long nicId) {
		this.nicId = nicId;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getNin() {
		return this.nin;
	}

	public void setNin(String nin) {
		this.nin = nin;
	}

	public int getGenNo() {
		return this.genNo;
	}

	public void setGenNo(int genNo) {
		this.genNo = genNo;
	}

	public int getUpdateNo() {
		return this.updateNo;
	}

	public void setUpdateNo(int updateNo) {
		this.updateNo = updateNo;
	}
	
	public Date getDateOfApplication() {
		return this.dateOfApplication;
	}

	public void setDateOfApplication(Date dateOfApplication) {
		this.dateOfApplication = dateOfApplication;
	}

	public String getCcn() {
		return this.ccn;
	}

	public void setCcn(String ccn) {
		this.ccn = ccn;
	}

	public Short getSamKeyVersion() {
		return this.samKeyVersion;
	}

	public void setSamKeyVersion(Short samKeyVersion) {
		this.samKeyVersion = samKeyVersion;
	}

	public Date getDateOfIssue() {
		return this.dateOfIssue;
	}

	public void setDateOfIssue(Date dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}

	public Date getPrevDateOfIssue() {
		return this.prevDateOfIssue;
	}

	public void setPrevDateOfIssue(Date prevDateOfIssue) {
		this.prevDateOfIssue = prevDateOfIssue;
	}

	public String getCardStatus() {
		return this.cardStatus;
	}

	public void setCardStatus(String cardStatus) {
		this.cardStatus = cardStatus;
	}

	public Date getCardStatusChangeTime() {
		return this.cardStatusChangeTime;
	}

	public void setCardStatusChangeTime(Date cardStatusChangeTime) {
		this.cardStatusChangeTime = cardStatusChangeTime;
	}

	public String getCardStatusChangeReason() {
		return this.cardStatusChangeReason;
	}

	public void setCardStatusChangeReason(String cardStatusChangeReason) {
		this.cardStatusChangeReason = cardStatusChangeReason;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getSurnameBirth() {
		return this.surnameBirth;
	}

	public void setSurnameBirth(String surnameBirth) {
		this.surnameBirth = surnameBirth;
	}

	public String getOptionSurname() {
		return optionSurname;
	}

	public void setOptionSurname(String optionSurname) {
		this.optionSurname = optionSurname;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getPrintDob() {
		return this.printDob;
	}

	public void setPrintDob(String printDob) {
		this.printDob = printDob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getNicAddr1() {
		return this.nicAddr1;
	}

	public void setNicAddr1(String nicAddr1) {
		this.nicAddr1 = nicAddr1;
	}

	public String getNicAddr2() {
		return this.nicAddr2;
	}

	public void setNicAddr2(String nicAddr2) {
		this.nicAddr2 = nicAddr2;
	}

	public String getNicAddr3() {
		return this.nicAddr3;
	}

	public void setNicAddr3(String nicAddr3) {
		this.nicAddr3 = nicAddr3;
	}

	public String getNicAddr4() {
		return this.nicAddr4;
	}

	public void setNicAddr4(String nicAddr4) {
		this.nicAddr4 = nicAddr4;
	}

	public String getNicAddr5() {
		return nicAddr5;
	}

	public void setNicAddr5(String nicAddr5) {
		this.nicAddr5 = nicAddr5;
	}

	public String getNicAddr6() {
		return nicAddr6;
	}

	public void setNicAddr6(String nicAddr6) {
		this.nicAddr6 = nicAddr6;
	}

	public String getPreferredMailingAddress() {
		return preferredMailingAddress;
	}

	public void setPreferredMailingAddress(String preferredMailingAddress) {
		this.preferredMailingAddress = preferredMailingAddress;
	}

	public String getOverseasAddress() {
		return overseasAddress;
	}

	public void setOverseasAddress(String overseasAddress) {
		this.overseasAddress = overseasAddress;
	}

	public String getOverseasCountry() {
		return overseasCountry;
	}

	public void setOverseasCountry(String overseasCountry) {
		this.overseasCountry = overseasCountry;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getFatherSurname() {
		return this.fatherSurname;
	}

	public void setFatherSurname(String fatherSurname) {
		this.fatherSurname = fatherSurname;
	}

	public String getFatherNin() {
		return this.fatherNin;
	}

	public void setFatherNin(String fatherNin) {
		this.fatherNin = fatherNin;
	}

	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getMotherSurname() {
		return this.motherSurname;
	}

	public void setMotherSurname(String motherSurname) {
		this.motherSurname = motherSurname;
	}

	public String getMotherNin() {
		return this.motherNin;
	}

	public void setMotherNin(String motherNin) {
		this.motherNin = motherNin;
	}

	public String getSpouseName() {
		return this.spouseName;
	}

	public void setSpouseName(String spouseName) {
		this.spouseName = spouseName;
	}

	public String getSpouseSurname() {
		return this.spouseSurname;
	}

	public void setSpouseSurname(String spouseSurname) {
		this.spouseSurname = spouseSurname;
	}

	public String getSpouseNin() {
		return this.spouseNin;
	}

	public void setSpouseNin(String spouseNin) {
		this.spouseNin = spouseNin;
	}

	public String getScIndicator() {
		return this.scIndicator;
	}

	public void setScIndicator(String scIndicator) {
		this.scIndicator = scIndicator;
	}

	public Integer getTotalFp() {
		return this.totalFp;
	}

	public void setTotalFp(Integer totalFp) {
		this.totalFp = totalFp;
	}

	public String getFpIndicator() {
		return this.fpIndicator;
	}

	public void setFpIndicator(String fpIndicator) {
		this.fpIndicator = fpIndicator;
	}

	public String getFpEncode() {
		return this.fpEncode;
	}

	public void setFpEncode(String fpEncode) {
		this.fpEncode = fpEncode;
	}

	public String getFpQuality() {
		return this.fpQuality;
	}

	public void setFpQuality(String fpQuality) {
		this.fpQuality = fpQuality;
	}

	public Long getFp01DocId() {
		return this.fp01DocId;
	}

	public void setFp01DocId(Long fp01DocId) {
		this.fp01DocId = fp01DocId;
	}

	public Long getFp02DocId() {
		return this.fp02DocId;
	}

	public void setFp02DocId(Long fp02DocId) {
		this.fp02DocId = fp02DocId;
	}

	public Long getFp03DocId() {
		return this.fp03DocId;
	}

	public void setFp03DocId(Long fp03DocId) {
		this.fp03DocId = fp03DocId;
	}

	public Long getFp04DocId() {
		return this.fp04DocId;
	}

	public void setFp04DocId(Long fp04DocId) {
		this.fp04DocId = fp04DocId;
	}

	public Long getFp05DocId() {
		return this.fp05DocId;
	}

	public void setFp05DocId(Long fp05DocId) {
		this.fp05DocId = fp05DocId;
	}

	public Long getFp06DocId() {
		return this.fp06DocId;
	}

	public void setFp06DocId(Long fp06DocId) {
		this.fp06DocId = fp06DocId;
	}

	public Long getFp07DocId() {
		return this.fp07DocId;
	}

	public void setFp07DocId(Long fp07DocId) {
		this.fp07DocId = fp07DocId;
	}

	public Long getFp08DocId() {
		return this.fp08DocId;
	}

	public void setFp08DocId(Long fp08DocId) {
		this.fp08DocId = fp08DocId;
	}

	public Long getFp09DocId() {
		return this.fp09DocId;
	}

	public void setFp09DocId(Long fp09DocId) {
		this.fp09DocId = fp09DocId;
	}

	public Long getFp10DocId() {
		return this.fp10DocId;
	}

	public void setFp10DocId(Long fp10DocId) {
		this.fp10DocId = fp10DocId;
	}

	public Long getMnu1DocId() {
		return this.mnu1DocId;
	}

	public void setMnu1DocId(Long mnu1DocId) {
		this.mnu1DocId = mnu1DocId;
	}

	public Long getMnu2DocId() {
		return this.mnu2DocId;
	}

	public void setMnu2DocId(Long mnu2DocId) {
		this.mnu2DocId = mnu2DocId;
	}

	public Long getMnu3DocId() {
		return this.mnu3DocId;
	}

	public void setMnu3DocId(Long mnu3DocId) {
		this.mnu3DocId = mnu3DocId;
	}

	public Long getMnu4DocId() {
		return this.mnu4DocId;
	}

	public void setMnu4DocId(Long mnu4DocId) {
		this.mnu4DocId = mnu4DocId;
	}

	public String getFacialIndicator() {
		return this.facialIndicator;
	}

	public void setFacialIndicator(String facialIndicator) {
		this.facialIndicator = facialIndicator;
	}

	public Long getFacialCapDocId() {
		return this.facialCapDocId;
	}

	public void setFacialCapDocId(Long facialCapDocId) {
		this.facialCapDocId = facialCapDocId;
	}

	public Long getFacialGreyDocId() {
		return this.facialGreyDocId;
	}

	public void setFacialGreyDocId(Long facialGreyDocId) {
		this.facialGreyDocId = facialGreyDocId;
	}

	public Long getFacialChipDocId() {
		return this.facialChipDocId;
	}

	public void setFacialChipDocId(Long facialChipDocId) {
		this.facialChipDocId = facialChipDocId;
	}

	public String getSignatureIndicator() {
		return this.signatureIndicator;
	}

	public void setSignatureIndicator(String signatureIndicator) {
		this.signatureIndicator = signatureIndicator;
	}

	public String getSignatureFp() {
		return this.signatureFp;
	}

	public void setSignatureFp(String signatureFp) {
		this.signatureFp = signatureFp;
	}

	public Long getSignatureDocId() {
		return this.signatureDocId;
	}

	public void setSignatureDocId(Long signatureDocId) {
		this.signatureDocId = signatureDocId;
	}

	public Long getPersoDocId() {
		return this.persoDocId;
	}

	public void setPersoDocId(Long persoDocId) {
		this.persoDocId = persoDocId;
	}

	public Long getScFormDocId() {
		return this.scFormDocId;
	}

	public void setScFormDocId(Long scFormDocId) {
		this.scFormDocId = scFormDocId;
	}

	public Long getScBirthExtDocId() {
		return this.scBirthExtDocId;
	}

	public void setScBirthExtDocId(Long scBirthExtDocId) {
		this.scBirthExtDocId = scBirthExtDocId;
	}

	public Long getScMarCertDocId() {
		return this.scMarCertDocId;
	}

	public void setScMarCertDocId(Long scMarCertDocId) {
		this.scMarCertDocId = scMarCertDocId;
	}

	public Long getScAddrProofDocId() {
		return this.scAddrProofDocId;
	}

	public void setScAddrProofDocId(Long scAddrProofDocId) {
		this.scAddrProofDocId = scAddrProofDocId;
	}

	public Set getNicChangeNinLogs() {
		return this.nicChangeNinLogs;
	}

	public void setNicChangeNinLogs(Set nicChangeNinLogs) {
		this.nicChangeNinLogs = nicChangeNinLogs;
	}

	public Set getNicHistories() {
		return this.nicHistories;
	}

	public void setNicHistories(Set nicHistories) {
		this.nicHistories = nicHistories;
	}

	public Set getNicRegistrationDatas() {
		return this.nicRegistrationDatas;
	}

	public void setNicRegistrationDatas(Set nicRegistrationDatas) {
		this.nicRegistrationDatas = nicRegistrationDatas;
	}

}
