package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NicTransaction generated by hbm2java
 */
@Entity 
@Table(name = "EPP_CENTRAL.PERSO_SITES")
public class PersoSites implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
	private Long persoId;
	private String siteId;
	private Boolean active;
	
	public PersoSites() {
	}

	public PersoSites(Long id, Long persoId, String siteId, Boolean active) {
		super();
		this.id = id;
		this.persoId = persoId;
		this.siteId = siteId;
		this.active = active;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getPersoId() {
		return persoId;
	}

	public void setPersoId(Long persoId) {
		this.persoId = persoId;
	}

	public String getSiteId() {
		return siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	
}
