package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class EppDetailReciept implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private long id;
	private String recieptNo;
	private String authenticationCode;
	private String transactionId;
	private Date createDate;
	private String createBy;
	private Date modifyDate;
	private String modifyBy;
	private String description;
	private Integer serialNo;
	private String fullname;
	private Date dob;
	private String nin;
	private String address;
	private String checkTxn;
	
	public EppDetailReciept(){
		
	}
	
	public EppDetailReciept(long id, String recieptNo,
			String authenticationCode, String transactionId,
			Date createDate, String createBy, Date modifyDate,
			String modifyBy, String description, Integer serialNo,
			String fullname, Date dob, String nin, String address,
			String checkTxn) {
		super();
		this.id = id;
		this.recieptNo = recieptNo;
		this.authenticationCode = authenticationCode;
		this.transactionId = transactionId;
		this.createDate = createDate;
		this.createBy = createBy;
		this.modifyDate = modifyDate;
		this.modifyBy = modifyBy;
		this.description = description;
		this.serialNo = serialNo;
		this.fullname = fullname;
		this.dob = dob;
		this.nin = nin;
		this.address = address;
		this.checkTxn = checkTxn;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getRecieptNo() {
		return recieptNo;
	}
	public void setRecieptNo(String recieptNo) {
		this.recieptNo = recieptNo;
	}
	public String getAuthenticationCode() {
		return authenticationCode;
	}
	public void setAuthenticationCode(String authenticationCode) {
		this.authenticationCode = authenticationCode;
	}
	public String getTransactionId() {
		return transactionId;
	}
	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	public Date getModifyDate() {
		return modifyDate;
	}
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	public String getModifyBy() {
		return modifyBy;
	}
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Integer getSerialNo() {
		return serialNo;
	}
	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}
	public String getFullname() {
		return fullname;
	}
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	public Date getDob() {
		return dob;
	}
	public void setDob(Date dob) {
		this.dob = dob;
	}
	public String getNin() {
		return nin;
	}
	public void setNin(String nin) {
		this.nin = nin;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getCheckTxn() {
		return checkTxn;
	}
	public void setCheckTxn(String checkTxn) {
		this.checkTxn = checkTxn;
	}
	
	
}
