//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 03:36:12 PM ICT 
//


package com.nec.asia.epp.perso.persoStatus;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="InvalidData"/>
 *     &lt;enumeration value="SystemError"/>
 *     &lt;enumeration value="PersoError"/>
 *     &lt;enumeration value="QcError"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorCodeType")
@XmlEnum
public enum ErrorCodeType {

    @XmlEnumValue("InvalidData")
    INVALID_DATA("InvalidData"),
    @XmlEnumValue("SystemError")
    SYSTEM_ERROR("SystemError"),
    @XmlEnumValue("PersoError")
    PERSO_ERROR("PersoError"),
    @XmlEnumValue("QcError")
    QC_ERROR("QcError");
    private final String value;

    ErrorCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorCodeType fromValue(String v) {
        for (ErrorCodeType c: ErrorCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
