package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicSearchHitResult generated by hbm2java
 */
public class NicSearchHitResult implements java.io.Serializable {

	private static final long serialVersionUID = -4496377039424213441L;

	public static final String hitInfo__ITEM__DELIMITER = "XXX";
	public static final String hitInfo__SUB_ITEM__GROUP__DELIMITER = "="; 
	public static final String hitInfo__SUB_ITEM__GROUP_ITEM__DELIMITER = ","; 
	
	public static final String hitInfo_DataSource_CPD = "CPD";
	public static final String hitInfo_DataSource_BMS = "BMS";
	public static final String hitInfo_DataSource_ERROR = "ERROR";
	
	private Long hitResultId;
//	private NicSearchResult searchResult;
	private Long searchResultId;
	private String afisKeyNoHit;
	private String transactionIdHit;
	private Boolean hitDecision;
	private String dataSource;
	private String hitInfo;
	private Date createDatetime;
	private Boolean verifyDecision;
	private String verifyDecisionBy;
	private Date verifyDecisionDatetime;
	private String verifyDecisionRemarks;
	private Boolean verify2Decision;
	private String verify2DecisionBy;
	private Date verify2DecisionDatetime;
	private String verify2DecisionRemarks;

	public NicSearchHitResult() {
	}

//	public NicSearchHitResult(Long hitResultId, NicSearchResult nicSearchResult, String transactionIdHit) {
	public NicSearchHitResult(Long hitResultId, Long searchResultId, String transactionIdHit) {
		this.hitResultId = hitResultId;
//		this.searchResult = nicSearchResult;
		this.searchResultId = searchResultId;
		this.transactionIdHit = transactionIdHit;
	}

//	public NicSearchHitResult(Long hitResultId, NicSearchResult nicSearchResult, String afisKeyNoHit,
	public NicSearchHitResult(Long hitResultId, Long searchResultId, String afisKeyNoHit,
			String transactionIdHit, Boolean hitDecision, String dataSource, String hitInfo, Date createDatetime,
			Boolean verifyDecision, String verifyDecisionBy, Date verifyDecisionDatetime, String verifyDecisionRemarks,
			Boolean verify2Decision, String verify2DecisionBy, Date verify2DecisionDatetime,
			String verify2DecisionRemarks) {
		this.hitResultId = hitResultId;
//		this.searchResult = nicSearchResult;
		this.searchResultId = searchResultId;
		this.afisKeyNoHit = afisKeyNoHit;
		this.transactionIdHit = transactionIdHit;
		this.hitDecision = hitDecision;
		this.dataSource = dataSource;
		this.hitInfo = hitInfo;
		this.createDatetime = createDatetime;
		this.verifyDecision = verifyDecision;
		this.verifyDecisionBy = verifyDecisionBy;
		this.verifyDecisionDatetime = verifyDecisionDatetime;
		this.verifyDecisionRemarks = verifyDecisionRemarks;
		this.verify2Decision = verify2Decision;
		this.verify2DecisionBy = verify2DecisionBy;
		this.verify2DecisionDatetime = verify2DecisionDatetime;
		this.verify2DecisionRemarks = verify2DecisionRemarks;
	}

	public Long getHitResultId() {
		return this.hitResultId;
	}

	public void setHitResultId(Long hitResultId) {
		this.hitResultId = hitResultId;
	}
	
	public Long getSearchResultId() {
		return searchResultId;
	}

	public void setSearchResultId(Long searchResultId) {
		this.searchResultId = searchResultId;
	}

//	public NicSearchResult getSearchResult() {
//		return this.searchResult;
//	}
//
//	public void setSearchResult(NicSearchResult nicSearchResult) {
//		this.searchResult = nicSearchResult;
//	}

	public String getAfisKeyNoHit() {
		return this.afisKeyNoHit;
	}

	public void setAfisKeyNoHit(String afisKeyNoHit) {
		this.afisKeyNoHit = afisKeyNoHit;
	}

	public String getTransactionIdHit() {
		return this.transactionIdHit;
	}

	public void setTransactionIdHit(String transactionIdHit) {
		this.transactionIdHit = transactionIdHit;
	}

	public Boolean getHitDecision() {
		return this.hitDecision;
	}

	public void setHitDecision(Boolean hitDecision) {
		this.hitDecision = hitDecision;
	}

	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public String getHitInfo() {
		return this.hitInfo;
	}

	public void setHitInfo(String hitInfo) {
		this.hitInfo = hitInfo;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public Boolean getVerifyDecision() {
		return this.verifyDecision;
	}

	public void setVerifyDecision(Boolean verifyDecision) {
		this.verifyDecision = verifyDecision;
	}

	public String getVerifyDecisionBy() {
		return this.verifyDecisionBy;
	}

	public void setVerifyDecisionBy(String verifyDecisionBy) {
		this.verifyDecisionBy = verifyDecisionBy;
	}

	public Date getVerifyDecisionDatetime() {
		return this.verifyDecisionDatetime;
	}

	public void setVerifyDecisionDatetime(Date verifyDecisionDatetime) {
		this.verifyDecisionDatetime = verifyDecisionDatetime;
	}

	public String getVerifyDecisionRemarks() {
		return this.verifyDecisionRemarks;
	}

	public void setVerifyDecisionRemarks(String verifyDecisionRemarks) {
		this.verifyDecisionRemarks = verifyDecisionRemarks;
	}

	public Boolean getVerify2Decision() {
		return this.verify2Decision;
	}

	public void setVerify2Decision(Boolean verify2Decision) {
		this.verify2Decision = verify2Decision;
	}

	public String getVerify2DecisionBy() {
		return this.verify2DecisionBy;
	}

	public void setVerify2DecisionBy(String verify2DecisionBy) {
		this.verify2DecisionBy = verify2DecisionBy;
	}

	public Date getVerify2DecisionDatetime() {
		return this.verify2DecisionDatetime;
	}

	public void setVerify2DecisionDatetime(Date verify2DecisionDatetime) {
		this.verify2DecisionDatetime = verify2DecisionDatetime;
	}

	public String getVerify2DecisionRemarks() {
		return this.verify2DecisionRemarks;
	}

	public void setVerify2DecisionRemarks(String verify2DecisionRemarks) {
		this.verify2DecisionRemarks = verify2DecisionRemarks;
	}

}
