package com.nec.asia.nic.comp.trans.dto;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.nec.asia.nic.comp.trans.domain.NicIssuanceDataId;

/**
 * NicIssuanceData generated by hbm2java
 */
/* 
 * Modification History:
 * 
 * 20 Jun 2013 (chris): Add DateOfIssue Column
 * 24 Aug 2013 (chris): Add cardStatusChangeTime, cardStatusChangeReason column
 * 13 Sep 2013 (chris): Add packageSequence column
 */
public class NicIssuanceDataDto implements java.io.Serializable {

	private NicIssuanceDataId id;
	private NicTransactionDto nicTransactionDto;
	private String packageId;
	private String packageSequence;//13 Sep 2013 (chris)
	private String ccn;
	private Short samKeyVersion;
	private String cardStatus;
	private Date cardStatusChangeTime;
	private String cardStatusChangeReason;
	private String nin;
	private Date dateOfIssue;
	private String issuanceDecision;
	private String issuanceOfficerId;
	private Date collectionDate;
	private String createBy;
	private String createWkstnId;
	private Date createDate;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDate;
	private Date packageDate;
	private boolean receivedCardFlag;
	private String dispatchId;
	
	private String registrationDateFrom;
	private String registrationDateTo;
	private String collectionDateFrom;
	private String collectionDateTo;

	private String registrationDateDisp;
	private String collectionDateDisp;
	private String dateOfIssueDisp;
	
	public NicIssuanceDataDto() {
	}

	public NicIssuanceDataDto(NicIssuanceDataId id, NicTransactionDto nicTransactionDto) {
		this.id = id;
		this.nicTransactionDto = nicTransactionDto;
	}

	public NicIssuanceDataDto(NicIssuanceDataId id, NicTransactionDto nicTransactionDto,
			String packageId, String packageSequence, String ccn, Short samKeyVersion,
			String cardStatus, String nin, Date dateOfIssue, String issuanceDecision,
			String issuanceOfficerId, Date collectionDate, String createBy,
			String createWkstnId, Date createDate, String updateBy,
			String updateWkstnId, Date updateDate) {
		this.id = id;
		this.nicTransactionDto = nicTransactionDto;
		this.packageId = packageId;
		this.packageSequence = packageSequence;
		this.ccn = ccn;
		this.samKeyVersion = samKeyVersion;
		this.cardStatus = cardStatus;
		this.nin = nin;
		this.dateOfIssue = dateOfIssue;
		this.issuanceDecision = issuanceDecision;
		this.issuanceOfficerId = issuanceOfficerId;
		this.collectionDate = collectionDate;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDate = updateDate;
	}

	public NicIssuanceDataId getId() {
		return this.id;
	}

	public void setId(NicIssuanceDataId id) {
		this.id = id;
	}

	public NicTransactionDto getNicTransactionDto() {
		return this.nicTransactionDto;
	}

	public void setNicTransactionDto(NicTransactionDto nicTransactionDto) {
		this.nicTransactionDto = nicTransactionDto;
	}

	public String getPackageId() {
		return this.packageId;
	}

	public void setPackageId(String packageId) {
		this.packageId = packageId;
	}
	
	//13 Sep 2013 (chris) - start
	public String getPackageSequence() {
		return this.packageSequence;
	}

	public void setPackageSequence(String packageSequence) {
		this.packageSequence = packageSequence;
	}
	//13 Sep 2013 (chris) - end
	
	public String getCcn() {
		return this.ccn;
	}

	public void setCcn(String ccn) {
		this.ccn = ccn;
	}

	public Short getSamKeyVersion() {
		return this.samKeyVersion;
	}

	public void setSamKeyVersion(Short samKeyVersion) {
		this.samKeyVersion = samKeyVersion;
	}

	public String getCardStatus() {
		return this.cardStatus;
	}

	public void setCardStatus(String cardStatus) {
		this.cardStatus = cardStatus;
	}

	public String getNin() {
		return this.nin;
	}

	public void setNin(String nin) {
		this.nin = nin;
	}
	
	public Date getDateOfIssue() {
		return this.dateOfIssue;
	}

	public void setDateOfIssue(Date dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}

	public String getIssuanceDecision() {
		return this.issuanceDecision;
	}

	public void setIssuanceDecision(String issuanceDecision) {
		this.issuanceDecision = issuanceDecision;
	}

	public String getIssuanceOfficerId() {
		return this.issuanceOfficerId;
	}

	public void setIssuanceOfficerId(String issuanceOfficerId) {
		this.issuanceOfficerId = issuanceOfficerId;
	}

	public Date getCollectionDate() {
		return this.collectionDate;
	}

	public void setCollectionDate(Date collectionDate) {
		this.collectionDate = collectionDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * @return the packageDate
	 */
	public Date getPackageDate() {
		return packageDate;
	}

	/**
	 * @param packageDate the packageDate to set
	 */
	public void setPackageDate(Date packageDate) {
		this.packageDate = packageDate;
	}

	/**
	 * @return the receivedCard
	 */
	public boolean isReceivedCardFlag() {
		return receivedCardFlag;
	}

	/**
	 * @param receivedCard the receivedCard to set
	 */
	public void setReceivedCardFlag(boolean receivedCardFlag) {
		this.receivedCardFlag = receivedCardFlag;
	}

	public Date getCardStatusChangeTime() {
		return cardStatusChangeTime;
	}

	public void setCardStatusChangeTime(Date cardStatusChangeTime) {
		this.cardStatusChangeTime = cardStatusChangeTime;
	}

	public String getCardStatusChangeReason() {
		return cardStatusChangeReason;
	}

	public void setCardStatusChangeReason(String cardStatusChangeReason) {
		this.cardStatusChangeReason = cardStatusChangeReason;
	}

	public String getDispatchId() {
		return dispatchId;
	}

	public void setDispatchId(String dispatchId) {
		this.dispatchId = dispatchId;
	}

	public String getRegistrationDateFrom() {
		return registrationDateFrom;
	}

	public void setRegistrationDateFrom(String registrationDateFrom) {
		this.registrationDateFrom = registrationDateFrom;
	}

	public String getRegistrationDateTo() {
		return registrationDateTo;
	}

	public void setRegistrationDateTo(String registrationDateTo) {
		this.registrationDateTo = registrationDateTo;
	}

	public String getCollectionDateFrom() {
		return collectionDateFrom;
	}

	public void setCollectionDateFrom(String collectionDateFrom) {
		this.collectionDateFrom = collectionDateFrom;
	}

	public String getCollectionDateTo() {
		return collectionDateTo;
	}

	public void setCollectionDateTo(String collectionDateTo) {
		this.collectionDateTo = collectionDateTo;
	}

	public String getRegistrationDateDisp() {
		return registrationDateDisp;
	}

	public void setRegistrationDateDisp(String registrationDateDisp) {
		this.registrationDateDisp = registrationDateDisp;
	}

	public String getCollectionDateDisp() {
		return collectionDateDisp;
	}

	public void setCollectionDateDisp(String collectionDateDisp) {
		this.collectionDateDisp = collectionDateDisp;
	}

	public String getDateOfIssueDisp() {
		return dateOfIssueDisp;
	}

	public void setDateOfIssueDisp(String dateOfIssueDisp) {
		this.dateOfIssueDisp = dateOfIssueDisp;
	}


	
}
