package com.nec.asia.nic.comp.trans.dto;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Map;

import org.hibernate.annotations.Sort;

/**
 * NicTransactionAttachment generated by hbm2java
 */
/*
 * Modification History:
 * 24 Jun 2013 (chris): to workaround the transaction id is null when saving.
 * 15 Aug 2013 (chris): to change signature document type from SI to SIGNATURE.
 */
public class NicTransactionAttachmentDto implements java.io.Serializable {
	//Prefix
	public final static String DOC_TYPE_PREFIX_PHOTO 		= "PH";
	public final static String DOC_TYPE_PREFIX_THUMBNAIL 	= "TH";
	public final static String DOC_TYPE_PREFIX_SCANNEDDOC 	= "SC";
	public final static String DOC_TYPE_PREFIX_SIGN 		= "SIGN";
	public final static String DOC_TYPE_FINGERPRINT 		= "FP";
	public final static String DOC_TYPE_MINUTIA 			= "MNU";
	public final static String DOC_TYPE_ENCODING 			= "ENCODING";
	public final static String DOC_TYPE_PERSO 				= "PERSO";
	public final static String DOC_TYPE_SIGNATURE 			= "SIGNATURE";
	public final static String DOC_TYPE_SIGN_FP 			= "SIGN_FP";
	public final static String DOC_TYPE_USER_DECLARATION 	= "USER_DECL";
	//SubTypes
	public final static String DOC_TYPE_PHOTO_CAPTURE 		= "PH_CAP";
	public final static String DOC_TYPE_THUMBNAIL_CAPTURE 	= "TH_CAP";
	public final static String DOC_TYPE_PHOTO_GREY	 		= "PH_GREY";
	public final static String DOC_TYPE_THUMBNAIL_GREY 		= "TH_GREY";
	public final static String DOC_TYPE_PHOTO_CHIP 			= "PH_CHIP";
	public final static String DOC_TYPE_THUMBNAIL_CHIP 		= "TH_CHIP";
	public final static String DOC_TYPE_PHOTO_CLI 			= "PH_CLI";
	//Scanned Document
	public final static String DOC_TYPE_SC_BIRTH_CERT		= "SC_BIRTH_CERT";
	public final static String DOC_TYPE_SC_MAR_CERT 		= "SC_MAR_CERT";
	public final static String DOC_TYPE_SC_ADDR_PROOF		= "SC_ADDR_PROOF_DOC";
	
	public static final String DEFAULT_SERIAL_NO = "01";
	
	private long transactionDocId;
	//private NicTransaction nicTransaction;
	private String transactionId;
	
	private String docType;
	@Sort
	private String serialNo;
	private byte[] docData;
	private String status;
	private String purpose;
	private String createBy;
	private String createWkstnId;
	private Date createDate;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDate;
	

	
	public NicTransactionAttachmentDto() {
	}

	public NicTransactionAttachmentDto(long transactionDocId,
			String transactionId,
			//NicTransaction nicTransaction, 
			String docType, String serialNo) {
		this.transactionDocId = transactionDocId;
		//this.nicTransaction = nicTransaction;
		this.transactionId = transactionId;
		this.docType = docType;
		this.serialNo = serialNo;
	}

	public NicTransactionAttachmentDto(long transactionDocId,
			//NicTransaction nicTransaction, 
			String transactionId,
			String docType, String serialNo,
			byte[] docData, String status, String purpose, String createBy,
			String createWkstnId, Date createDate, String updateBy,
			String updateWkstnId, Date updateDate) {
		this.transactionDocId = transactionDocId;
		//this.nicTransaction = nicTransaction;
		this.transactionId = transactionId;
		this.docType = docType;
		this.serialNo = serialNo;
		this.docData = docData;
		this.status = status;
		this.purpose = purpose;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDate = updateDate;
	}
	public long getTransactionDocId() {
		return this.transactionDocId;
	}

	public void setTransactionDocId(long transactionDocId) {
		this.transactionDocId = transactionDocId;
	}

	/*public NicTransaction getNicTransaction() {
		return this.nicTransaction;
	}

	public void setNicTransaction(NicTransaction nicTransaction) {
		this.nicTransaction = nicTransaction;
	}*/
	
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public byte[] getDocData() {
		return this.docData;
	}

	public void setDocData(byte[] docData) {
		this.docData = docData;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
