package com.nec.asia.nic.comp.trans.dto;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.nec.asia.nic.comp.trans.domain.NicDocumentData;
import com.nec.asia.nic.comp.trans.domain.NicRegistrationData;
import com.nec.asia.nic.comp.trans.domain.NicSearchResult;
import com.nec.asia.nic.comp.trans.domain.NicTransactionAttachment;
import com.nec.asia.nic.comp.trans.domain.NicTransactionPayment;
import com.nec.asia.nic.comp.trans.domain.NicWorkflowJob;

/**
 * NicTransaction generated by hbm2java
 */

/* 
 * Modification History:
 * 
 * 28 Jun 2013 (chris): Add Column  DATE_OF_ISSUE.
 */
public class NicTransactionJsonDto implements java.io.Serializable {
	private String transactionId;
	private String applnRefNo;
	private String nin;
	private Date dateOfApplication;
	private Date estDateOfCollection;
	private String passportType;
	private Integer validityPeriod;
	private String issuingAuthority;
	private Integer priority;
	private String regSiteCode;
	private String issSiteCode;
	private String transactionType;
	private String transactionStatus;
	private String prevPassportNo;
	private Date prevDateOfIssue;
	private String createBy;
	private String createWkstnId;
	private Date createDatetime;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDatetime;
	
	private Long printPerso;
	private Integer syncPassport;
	private String packageID;
	private String nicSiteCode;
	private String leaderOfficerId;
	private String noteHandoverB;
	private Boolean isPostOffice;
	private String recieptNo;
	
	private String dateOfBirthDesc;
	private String createDesc;
	private String religionDesc;
	private String nationDesc;
	private String dateNinDesc;
	private String datePassportDesc;
	private String spouseDobDesc;
	private String motherDobDesc;
	private String fatherDobDesc;
	private String dateDecisionDesc;
	private String estimateFromDesc;
	private String dateCountryDesc;
	private String infoPerson;
	private Boolean passportStyle;
	private String receiver;
	
	public String getDateOfBirthDesc() {
		return dateOfBirthDesc;
	}
	public void setDateOfBirthDesc(String dateOfBirthDesc) {
		this.dateOfBirthDesc = dateOfBirthDesc;
	}
	public String getCreateDesc() {
		return createDesc;
	}
	public void setCreateDesc(String createDesc) {
		this.createDesc = createDesc;
	}
	public String getReligionDesc() {
		return religionDesc;
	}
	public void setReligionDesc(String religionDesc) {
		this.religionDesc = religionDesc;
	}
	public String getNationDesc() {
		return nationDesc;
	}
	public void setNationDesc(String nationDesc) {
		this.nationDesc = nationDesc;
	}
	public String getDateNinDesc() {
		return dateNinDesc;
	}
	public void setDateNinDesc(String dateNinDesc) {
		this.dateNinDesc = dateNinDesc;
	}
	public String getDatePassportDesc() {
		return datePassportDesc;
	}
	public void setDatePassportDesc(String datePassportDesc) {
		this.datePassportDesc = datePassportDesc;
	}
	public String getSpouseDobDesc() {
		return spouseDobDesc;
	}
	public void setSpouseDobDesc(String spouseDobDesc) {
		this.spouseDobDesc = spouseDobDesc;
	}
	public String getMotherDobDesc() {
		return motherDobDesc;
	}
	public void setMotherDobDesc(String motherDobDesc) {
		this.motherDobDesc = motherDobDesc;
	}
	public String getFatherDobDesc() {
		return fatherDobDesc;
	}
	public void setFatherDobDesc(String fatherDobDesc) {
		this.fatherDobDesc = fatherDobDesc;
	}
	public String getDateDecisionDesc() {
		return dateDecisionDesc;
	}
	public void setDateDecisionDesc(String dateDecisionDesc) {
		this.dateDecisionDesc = dateDecisionDesc;
	}
	public String getEstimateFromDesc() {
		return estimateFromDesc;
	}
	public void setEstimateFromDesc(String estimateFromDesc) {
		this.estimateFromDesc = estimateFromDesc;
	}
	public String getDateCountryDesc() {
		return dateCountryDesc;
	}
	public void setDateCountryDesc(String dateCountryDesc) {
		this.dateCountryDesc = dateCountryDesc;
	}
	public String getInfoPerson() {
		return infoPerson;
	}
	public void setInfoPerson(String infoPerson) {
		this.infoPerson = infoPerson;
	}
	public Boolean getPassportStyle() {
		return passportStyle;
	}
	public void setPassportStyle(Boolean passportStyle) {
		this.passportStyle = passportStyle;
	}
	public String getReceiver() {
		return receiver;
	}
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}
	public String getTransactionId() {
		return transactionId;
	}
	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}
	public String getApplnRefNo() {
		return applnRefNo;
	}
	public void setApplnRefNo(String applnRefNo) {
		this.applnRefNo = applnRefNo;
	}
	public String getNin() {
		return nin;
	}
	public void setNin(String nin) {
		this.nin = nin;
	}
	public Date getDateOfApplication() {
		return dateOfApplication;
	}
	public void setDateOfApplication(Date dateOfApplication) {
		this.dateOfApplication = dateOfApplication;
	}
	public Date getEstDateOfCollection() {
		return estDateOfCollection;
	}
	public void setEstDateOfCollection(Date estDateOfCollection) {
		this.estDateOfCollection = estDateOfCollection;
	}
	public String getPassportType() {
		return passportType;
	}
	public void setPassportType(String passportType) {
		this.passportType = passportType;
	}
	public Integer getValidityPeriod() {
		return validityPeriod;
	}
	public void setValidityPeriod(Integer validityPeriod) {
		this.validityPeriod = validityPeriod;
	}
	public String getIssuingAuthority() {
		return issuingAuthority;
	}
	public void setIssuingAuthority(String issuingAuthority) {
		this.issuingAuthority = issuingAuthority;
	}
	public Integer getPriority() {
		return priority;
	}
	public void setPriority(Integer priority) {
		this.priority = priority;
	}
	public String getRegSiteCode() {
		return regSiteCode;
	}
	public void setRegSiteCode(String regSiteCode) {
		this.regSiteCode = regSiteCode;
	}
	public String getIssSiteCode() {
		return issSiteCode;
	}
	public void setIssSiteCode(String issSiteCode) {
		this.issSiteCode = issSiteCode;
	}
	public String getTransactionType() {
		return transactionType;
	}
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}
	public String getTransactionStatus() {
		return transactionStatus;
	}
	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}
	public String getPrevPassportNo() {
		return prevPassportNo;
	}
	public void setPrevPassportNo(String prevPassportNo) {
		this.prevPassportNo = prevPassportNo;
	}
	public Date getPrevDateOfIssue() {
		return prevDateOfIssue;
	}
	public void setPrevDateOfIssue(Date prevDateOfIssue) {
		this.prevDateOfIssue = prevDateOfIssue;
	}
	public String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	public String getCreateWkstnId() {
		return createWkstnId;
	}
	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}
	public Date getCreateDatetime() {
		return createDatetime;
	}
	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}
	public String getUpdateBy() {
		return updateBy;
	}
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	public String getUpdateWkstnId() {
		return updateWkstnId;
	}
	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}
	public Date getUpdateDatetime() {
		return updateDatetime;
	}
	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}
	public Long getPrintPerso() {
		return printPerso;
	}
	public void setPrintPerso(Long printPerso) {
		this.printPerso = printPerso;
	}
	public Integer getSyncPassport() {
		return syncPassport;
	}
	public void setSyncPassport(Integer syncPassport) {
		this.syncPassport = syncPassport;
	}
	public String getPackageID() {
		return packageID;
	}
	public void setPackageID(String packageID) {
		this.packageID = packageID;
	}
	public String getNicSiteCode() {
		return nicSiteCode;
	}
	public void setNicSiteCode(String nicSiteCode) {
		this.nicSiteCode = nicSiteCode;
	}
	public String getLeaderOfficerId() {
		return leaderOfficerId;
	}
	public void setLeaderOfficerId(String leaderOfficerId) {
		this.leaderOfficerId = leaderOfficerId;
	}
	public String getNoteHandoverB() {
		return noteHandoverB;
	}
	public void setNoteHandoverB(String noteHandoverB) {
		this.noteHandoverB = noteHandoverB;
	}
	public Boolean getIsPostOffice() {
		return isPostOffice;
	}
	public void setIsPostOffice(Boolean isPostOffice) {
		this.isPostOffice = isPostOffice;
	}
	public String getRecieptNo() {
		return recieptNo;
	}
	public void setRecieptNo(String recieptNo) {
		this.recieptNo = recieptNo;
	}
	
	
}
