package com.nec.asia.nic.comp.trans.domain;

// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

/**
 * NicDocumentDataId generated by hbm2java
 */
public class NicDocumentDataId implements java.io.Serializable {

	private String transactionId;

	private String passportNo;

	// private String serialNo;

	public NicDocumentDataId() {
	}

	public NicDocumentDataId(String transactionId, String passportNo) {
		super();
		this.transactionId = transactionId;
		this.passportNo = passportNo;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NicDocumentDataId))
			return false;
		NicDocumentDataId castOther = (NicDocumentDataId) other;

		return ((this.getTransactionId() == castOther.getTransactionId()) || (this
				.getTransactionId() != null
				&& castOther.getTransactionId() != null && this
				.getTransactionId().equals(castOther.getTransactionId())))
				&& ((this.getPassportNo() == castOther.getPassportNo()) || (this
						.getPassportNo() != null
						&& castOther.getPassportNo() != null && this
						.getPassportNo().equals(castOther.getPassportNo())))
				/*&& ((this.getSerialNo() == castOther.getSerialNo()) || (this
						.getSerialNo() != null
						&& castOther.getSerialNo() != null && this
						.getSerialNo().equals(castOther.getSerialNo())))*/;
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTransactionId() == null ? 0 : this.getTransactionId()
						.hashCode());
		result = 37
				* result
				+ (getPassportNo() == null ? 0 : this.getPassportNo()
						.hashCode());
//		result = 37 * result
//				+ (getSerialNo() == null ? 0 : this.getSerialNo().hashCode());
		return result;
	}

}
