package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * NicDecisionManager generated by hbm2java
 */
@XmlRootElement(name = "EppBlacklist")
@XmlAccessorType(XmlAccessType.FIELD)
public class EppBlacklist implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    

    @XmlElement(name = "id")
    private Long id;
    @XmlElement(name = "deleteTs")
    private Date deleteTs;
    @XmlElement(name = "deletedBy")
    private String deletedBy;
    @XmlElement(name = "updateTs")
    private Date updateTs;
    @XmlElement(name = "updatedBy")
	private String updatedBy;
    @XmlElement(name = "createTs")
	private Date createTs;
    @XmlElement(name = "createdBy")
	private String createdBy;
    @XmlElement(name = "name")
	private String name; //Họ tên
    @XmlElement(name = "searchName")
	private String searchName; //Tên tìm kiếm
    @XmlElement(name = "nickName")
	private String nickName;
    @XmlElement(name = "dateOfBirth")
	private String dateOfBirth; //Ngày sinh
    @XmlElement(name = "gender")
	private String gender; //Giới tính
    @XmlElement(name = "ethnic")
	private String ethnic;
    @XmlElement(name = "religion")
	private String religion;
    @XmlElement(name = "originNationalityId")
	private Integer originNationalityId; //id Quốc tịch gốc
    @XmlElement(name = "currentNationalityId")
	private Integer currentNationalityId;  //id Quốc tịch hiện tại
    @XmlElement(name = "occupation")
	private String occupation;
    @XmlElement(name = "placeOfBirthId")
	private Integer placeOfBirthId; //Id nơi sinh
    @XmlElement(name = "passportNo")
	private String passportNo;
    @XmlElement(name = "idNumber")
	private String idNumber; //Số CMND/CCCD
    @XmlElement(name = "address")
	private String address;
    @XmlElement(name = "residentAddress")
	private String residentAddress;
    @XmlElement(name = "family")
	private String family;
    @XmlElement(name = "regCause")
	private String regCause;
    @XmlElement(name = "basedOnDoc")
	private String basedOnDoc;
    @XmlElement(name = "note")
	private String note; //Ghi chú
    @XmlElement(name = "mngRegNo")
	private String mngRegNo;
    @XmlElement(name = "mngRegOffice")
	private String mngRegOffice;
    @XmlElement(name = "mngBehave")
	private String mngBehave;
    @XmlElement(name = "mngApprovedBy")
	private String mngApprovedBy;
    @XmlElement(name = "mngPhoneNo")
	private String mngPhoneNo;
    @XmlElement(name = "mngDocNo")
	private String mngDocNo;
    @XmlElement(name = "mngDocDate")
	private String mngDocDate;
    @XmlElement(name = "mngExpire_")
	private String mngExpire_;
    @XmlElement(name = "mngNote")
	private String mngNote; 
    @XmlElement(name = "type_")
	private String type_;
    @XmlElement(name = "level_")
	private String level_;
    @XmlElement(name = "status")
	private String status;
    @XmlElement(name = "photo")
	private String photo;
	
	
	public EppBlacklist() {
		super();
	}

	public EppBlacklist(Long id, Date deleteTs, String deletedBy,
			Date updateTs, String updatedBy, Date createTs, String createdBy,
			String name, String searchName, String nickName,
			String dateOfBirth, String gender, String ethnic, String religion,
			Integer originNationalityId, Integer currentNationalityId,
			String occupation, Integer placeOfBirthId, String passportNo,
			String idNumber, String address, String residentAddress,
			String family, String regCause, String basedOnDoc, String note,
			String mngRegNo, String mngRegOffice, String mngBehave,
			String mngApprovedBy, String mngPhoneNo, String mngDocNo,
			String mngDocDate, String mngExpire_, String mngNote, String type_,
			String level_, String status) {
		super();
		this.id = id;
		this.deleteTs = deleteTs;
		this.deletedBy = deletedBy;
		this.updateTs = updateTs;
		this.updatedBy = updatedBy;
		this.createTs = createTs;
		this.createdBy = createdBy;
		this.name = name;
		this.searchName = searchName;
		this.nickName = nickName;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.ethnic = ethnic;
		this.religion = religion;
		this.originNationalityId = originNationalityId;
		this.currentNationalityId = currentNationalityId;
		this.occupation = occupation;
		this.placeOfBirthId = placeOfBirthId;
		this.passportNo = passportNo;
		this.idNumber = idNumber;
		this.address = address;
		this.residentAddress = residentAddress;
		this.family = family;
		this.regCause = regCause;
		this.basedOnDoc = basedOnDoc;
		this.note = note;
		this.mngRegNo = mngRegNo;
		this.mngRegOffice = mngRegOffice;
		this.mngBehave = mngBehave;
		this.mngApprovedBy = mngApprovedBy;
		this.mngPhoneNo = mngPhoneNo;
		this.mngDocNo = mngDocNo;
		this.mngDocDate = mngDocDate;
		this.mngExpire_ = mngExpire_;
		this.mngNote = mngNote;
		this.type_ = type_;
		this.level_ = level_;
		this.status = status;
	}
	
	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Date getDeleteTs() {
		return deleteTs;
	}
	public void setDeleteTs(Date deleteTs) {
		this.deleteTs = deleteTs;
	}
	public String getDeletedBy() {
		return deletedBy;
	}
	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy;
	}
	public Date getUpdateTs() {
		return updateTs;
	}
	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}
	public String getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public Date getCreateTs() {
		return createTs;
	}
	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSearchName() {
		return searchName;
	}
	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}
	public String getNickName() {
		return nickName;
	}
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	public String getDateOfBirth() {
		return dateOfBirth;
	}
	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getEthnic() {
		return ethnic;
	}
	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}
	public String getReligion() {
		return religion;
	}
	public void setReligion(String religion) {
		this.religion = religion;
	}
	public Integer getOriginNationalityId() {
		return originNationalityId;
	}
	public void setOriginNationalityId(Integer originNationalityId) {
		this.originNationalityId = originNationalityId;
	}
	public Integer getCurrentNationalityId() {
		return currentNationalityId;
	}
	public void setCurrentNationalityId(Integer currentNationalityId) {
		this.currentNationalityId = currentNationalityId;
	}
	public String getOccupation() {
		return occupation;
	}
	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}
	public Integer getPlaceOfBirthId() {
		return placeOfBirthId;
	}
	public void setPlaceOfBirthId(Integer placeOfBirthId) {
		this.placeOfBirthId = placeOfBirthId;
	}
	public String getPassportNo() {
		return passportNo;
	}
	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}
	public String getIdNumber() {
		return idNumber;
	}
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getResidentAddress() {
		return residentAddress;
	}
	public void setResidentAddress(String residentAddress) {
		this.residentAddress = residentAddress;
	}
	public String getFamily() {
		return family;
	}
	public void setFamily(String family) {
		this.family = family;
	}
	public String getRegCause() {
		return regCause;
	}
	public void setRegCause(String regCause) {
		this.regCause = regCause;
	}
	public String getBasedOnDoc() {
		return basedOnDoc;
	}
	public void setBasedOnDoc(String basedOnDoc) {
		this.basedOnDoc = basedOnDoc;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public String getMngRegNo() {
		return mngRegNo;
	}
	public void setMngRegNo(String mngRegNo) {
		this.mngRegNo = mngRegNo;
	}
	public String getMngRegOffice() {
		return mngRegOffice;
	}
	public void setMngRegOffice(String mngRegOffice) {
		this.mngRegOffice = mngRegOffice;
	}
	public String getMngBehave() {
		return mngBehave;
	}
	public void setMngBehave(String mngBehave) {
		this.mngBehave = mngBehave;
	}
	public String getMngApprovedBy() {
		return mngApprovedBy;
	}
	public void setMngApprovedBy(String mngApprovedBy) {
		this.mngApprovedBy = mngApprovedBy;
	}
	public String getMngPhoneNo() {
		return mngPhoneNo;
	}
	public void setMngPhoneNo(String mngPhoneNo) {
		this.mngPhoneNo = mngPhoneNo;
	}
	public String getMngDocNo() {
		return mngDocNo;
	}
	public void setMngDocNo(String mngDocNo) {
		this.mngDocNo = mngDocNo;
	}
	public String getMngDocDate() {
		return mngDocDate;
	}
	public void setMngDocDate(String mngDocDate) {
		this.mngDocDate = mngDocDate;
	}
	public String getMngExpire_() {
		return mngExpire_;
	}
	public void setMngExpire_(String mngExpire_) {
		this.mngExpire_ = mngExpire_;
	}
	public String getMngNote() {
		return mngNote;
	}
	public void setMngNote(String mngNote) {
		this.mngNote = mngNote;
	}
	public String getType_() {
		return type_;
	}
	public void setType_(String type_) {
		this.type_ = type_;
	}
	public String getLevel_() {
		return level_;
	}
	public void setLevel_(String level_) {
		this.level_ = level_;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
}
