package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NicTransaction generated by hbm2java
 */
public class RequestDocument implements Serializable {

	public RequestDocument() {
	}

	@JsonProperty("document")
	private DocumentInfo document;

	public DocumentInfo getDocument() {
		return document;
	}

	public void setDocument(DocumentInfo document) {
		this.document = document;
	}
}
