package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicRejectionData generated by hbm2java
 */
public class NicRejectionData implements java.io.Serializable {

    public static final String rejectReason_faultCaseManagement="AS DETERMINED IN FAULT CASE MANAGEMENT";
    public static final String rejectReason_investigation="AS DETERMINED IN INVESTIGATION";

    private Long workflowJobId;

    private String transactionId;

    private String rejectBy;

    private Date rejectDatetime;

    private String rejectReason;

    private String rejectRemarks;
    
    private String syncStatus;

    private Date lastSyncDatetime;

    public NicRejectionData() {
    }

    public NicRejectionData(Long workflowJobId) {
        this.workflowJobId = workflowJobId;
    }

    public NicRejectionData(Long workflowJobId, String transactionId, String rejectBy, Date rejectDatetime, String rejectReason, String rejectRemarks) {
        this.workflowJobId = workflowJobId;
        this.transactionId = transactionId;
        this.rejectBy = rejectBy;
        this.rejectDatetime = rejectDatetime;
        this.rejectReason = rejectReason;
        this.rejectRemarks = rejectRemarks;
    }

    public Long getWorkflowJobId() {
        return this.workflowJobId;
    }

    public void setWorkflowJobId(Long workflowJobId) {
        this.workflowJobId = workflowJobId;
    }

    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getRejectBy() {
        return this.rejectBy;
    }

    public void setRejectBy(String rejectBy) {
        this.rejectBy = rejectBy;
    }

    public Date getRejectDatetime() {
        return this.rejectDatetime;
    }

    public void setRejectDatetime(Date rejectDatetime) {
        this.rejectDatetime = rejectDatetime;
    }

    public String getRejectReason() {
        return this.rejectReason;
    }

    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    public String getRejectRemarks() {
        return this.rejectRemarks;
    }

    public void setRejectRemarks(String rejectRemarks) {
        this.rejectRemarks = rejectRemarks;
    }
    
    public String getSyncStatus() {
        return this.syncStatus;
    }

    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus;
    }

    public Date getLastSyncDatetime() {
        return this.lastSyncDatetime;
    }

    public void setLastSyncDatetime(Date lastSyncDatetime) {
        this.lastSyncDatetime = lastSyncDatetime;
    }
}
