package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicDocumentData generated by hbm2java
 */
public class NicDocumentData implements java.io.Serializable {

	public static final String DOCUMENT_DATA_STATUS_ISSUANCE = "ISSUANCE";
	public static final String DOCUMENT_DATA_STATUS_PERSONALIZED= "PERSONALIZED";
	public static final String DOCUMENT_DATA_STATUS_NONE = "NONE";
	public static final String DOCUMENT_DATA_STATUS_CANCELLED = "CANCELLED";
	public static final String DOCUMENT_DATA_STATUS_EXPIRED = "EXPIRED";
	public static final String DOCUMENT_DATA_STATUS_LOST = "LOST";
	public static final String DOCUMENT_DATA_STATUS_DAMAGED = "DAMAGED";
	
	
	public static final String DOCUMENT_DATA_CANCEL_TYPE_IN_HONG = "PRINT_FAIL";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_BAO_MAT= "LOST";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_BI_HUY = "DAMAGE";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_DONG_DAU_HUY = "RENEW";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_THU_HOI = "REVOKE";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_DIA_PHUONG_TRA_VE = "RETURNED";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_HC_TRA_LAI = "RETURNED";
	public static final String DOCUMENT_DATA_CANCELLED_TYPE_PRINT_FAIL = "PRINT_FAIL";
	public static final String DOCUMENT_DATA_STATUS_PACKED = "PACKED";
	public static final String DOCUMENT_DATA_STATUS_INIT = "INIT";
	public static final String DOCUMENT_DATA_CANCEL_TYPE_RESTORE_DRAFT = "RESTORE_DRAFT";
	
    private NicDocumentDataId id;
    
    private NicTransaction nicTransaction;

    private String chipSerialNo;

    private String printingSite;

    private Date dateOfIssue;

    private Date dateOfExpiry;

    private String status;

    private Date statusUpdateTime;

    private String packageId;

    private Date packageDatetime;

    private String dispatchId;

    private Date dispatchDatetime;

	private Boolean issuedFlag;

	private Boolean activeFlag;

    private String receiveBy;

    private Date receiveDatetime;

    private String issueBy;

    private Date issueDatetime;

    private String rejectBy;

    private Date rejectDatetime;

    private String cancelBy;

    private Date cancelDatetime;

    private String createBy;

    private String createWkstnId;

    private Date createDatetime;

    private String updateBy;

    private String updateWkstnId;

    private Date updateDatetime;

    private String syncStatus;

    private Date lastSyncDatetime;

    private String icaoLine1;
    
    private String icaoLine2;
    
    private String signer;
    
    private String positionSigner;
    
    private String cancelReason;
    //add
    private String serialNo;
    private Date printDate;
    private String printName;
    
    private String cancelType;
    private String printerSerial;
    private String passportType;
    private String placeOfIssueCode;
    
    public String getPassportType() {
		return passportType;
	}

	public void setPassportType(String passportType) {
		this.passportType = passportType;
	}

	public String getPlaceOfIssueCode() {
		return placeOfIssueCode;
	}

	public void setPlaceOfIssueCode(String placeOfIssueCode) {
		this.placeOfIssueCode = placeOfIssueCode;
	}

	public String getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public Date getPrintDate() {
		return printDate;
	}

	public void setPrintDate(Date printDate) {
		this.printDate = printDate;
	}

	public String getPrintName() {
		return printName;
	}

	public void setPrintName(String printName) {
		this.printName = printName;
	}

	public String getCancelReason() {
		return cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	public NicDocumentData() {
    }

    public NicDocumentData(NicDocumentDataId id) {
        this.id = id;
    }
   
    public NicDocumentData(NicDocumentDataId id, NicTransaction nicTransaction,
			String chipSerialNo, String printingSite, Date dateOfIssue,
			Date dateOfExpiry, String status, Date statusUpdateTime,
			String packageId, Date packageDatetime, String dispatchId,
			Date dispatchDatetime, Boolean issuedFlag, Boolean activeFlag,
			String receiveBy, Date receiveDatetime, String issueBy,
			Date issueDatetime, String rejectBy, Date rejectDatetime,
			String cancelBy, Date cancelDatetime, String createBy,
			String createWkstnId, Date createDatetime, String updateBy,
			String updateWkstnId, Date updateDatetime, String syncStatus,
			Date lastSyncDatetime, String icaoLine1, String icaoLine2,
			String signer, String positionSigner, String cancelReason,
			String serialNo, Date printDate, String printName,
			String cancelType, String printerSerial) {
		super();
		this.id = id;
		this.nicTransaction = nicTransaction;
		this.chipSerialNo = chipSerialNo;
		this.printingSite = printingSite;
		this.dateOfIssue = dateOfIssue;
		this.dateOfExpiry = dateOfExpiry;
		this.status = status;
		this.statusUpdateTime = statusUpdateTime;
		this.packageId = packageId;
		this.packageDatetime = packageDatetime;
		this.dispatchId = dispatchId;
		this.dispatchDatetime = dispatchDatetime;
		this.issuedFlag = issuedFlag;
		this.activeFlag = activeFlag;
		this.receiveBy = receiveBy;
		this.receiveDatetime = receiveDatetime;
		this.issueBy = issueBy;
		this.issueDatetime = issueDatetime;
		this.rejectBy = rejectBy;
		this.rejectDatetime = rejectDatetime;
		this.cancelBy = cancelBy;
		this.cancelDatetime = cancelDatetime;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDatetime = createDatetime;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDatetime = updateDatetime;
		this.syncStatus = syncStatus;
		this.lastSyncDatetime = lastSyncDatetime;
		this.icaoLine1 = icaoLine1;
		this.icaoLine2 = icaoLine2;
		this.signer = signer;
		this.positionSigner = positionSigner;
		this.cancelReason = cancelReason;
		this.serialNo = serialNo;
		this.printDate = printDate;
		this.printName = printName;
		this.cancelType = cancelType;
		this.printerSerial = printerSerial;
	}

	public String getSigner() {
		return signer;
	}

	public void setSigner(String signer) {
		this.signer = signer;
	}

	public String getPositionSigner() {
		return positionSigner;
	}

	public void setPositionSigner(String positionSigner) {
		this.positionSigner = positionSigner;
	}

	public String getIcaoLine1() {
		return icaoLine1;
	}

	public void setIcaoLine1(String icaoLine1) {
		this.icaoLine1 = icaoLine1;
	}

	public String getIcaoLine2() {
		return icaoLine2;
	}

	public void setIcaoLine2(String icaoLine2) {
		this.icaoLine2 = icaoLine2;
	}

	public NicDocumentDataId getId() {
        return this.id;
    }

    public void setId(NicDocumentDataId id) {
        this.id = id;
    }

    public String getChipSerialNo() {
        return this.chipSerialNo;
    }

    public void setChipSerialNo(String chipSerialNo) {
        this.chipSerialNo = chipSerialNo;
    }

    public String getPrintingSite() {
        return this.printingSite;
    }

    public void setPrintingSite(String printingSite) {
        this.printingSite = printingSite;
    }

    public Date getDateOfIssue() {
        return this.dateOfIssue;
    }

    public void setDateOfIssue(Date dateOfIssue) {
        this.dateOfIssue = dateOfIssue;
    }

    public Date getDateOfExpiry() {
        return this.dateOfExpiry;
    }

    public void setDateOfExpiry(Date dateOfExpiry) {
        this.dateOfExpiry = dateOfExpiry;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getStatusUpdateTime() {
        return this.statusUpdateTime;
    }

    public void setStatusUpdateTime(Date statusUpdateTime) {
        this.statusUpdateTime = statusUpdateTime;
    }

    public String getPackageId() {
        return this.packageId;
    }

    public void setPackageId(String packageId) {
        this.packageId = packageId;
    }

    public Date getPackageDatetime() {
        return this.packageDatetime;
    }

    public void setPackageDatetime(Date packageDatetime) {
        this.packageDatetime = packageDatetime;
    }

    public String getDispatchId() {
        return this.dispatchId;
    }

    public void setDispatchId(String dispatchId) {
        this.dispatchId = dispatchId;
    }

    public Date getDispatchDatetime() {
        return this.dispatchDatetime;
    }

    public void setDispatchDatetime(Date dispatchDatetime) {
        this.dispatchDatetime = dispatchDatetime;
    }

	public Boolean getIssuedFlag() {
		return this.issuedFlag;
	}

	public void setIssuedFlag(Boolean issuedFlag) {
		this.issuedFlag = issuedFlag;
	}

	public Boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

    public String getReceiveBy() {
        return this.receiveBy;
    }

    public void setReceiveBy(String receiveBy) {
        this.receiveBy = receiveBy;
    }

    public Date getReceiveDatetime() {
        return this.receiveDatetime;
    }

    public void setReceiveDatetime(Date receiveDatetime) {
        this.receiveDatetime = receiveDatetime;
    }

    public String getIssueBy() {
        return this.issueBy;
    }

    public void setIssueBy(String issueBy) {
        this.issueBy = issueBy;
    }

    public Date getIssueDatetime() {
        return this.issueDatetime;
    }

    public void setIssueDatetime(Date issueDatetime) {
        this.issueDatetime = issueDatetime;
    }

    public String getRejectBy() {
        return this.rejectBy;
    }

    public void setRejectBy(String rejectBy) {
        this.rejectBy = rejectBy;
    }

    public Date getRejectDatetime() {
        return this.rejectDatetime;
    }

    public void setRejectDatetime(Date rejectDatetime) {
        this.rejectDatetime = rejectDatetime;
    }

    public String getCancelBy() {
        return this.cancelBy;
    }

    public void setCancelBy(String cancelBy) {
        this.cancelBy = cancelBy;
    }

    public Date getCancelDatetime() {
        return this.cancelDatetime;
    }

    public void setCancelDatetime(Date cancelDatetime) {
        this.cancelDatetime = cancelDatetime;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getCreateWkstnId() {
        return this.createWkstnId;
    }

    public void setCreateWkstnId(String createWkstnId) {
        this.createWkstnId = createWkstnId;
    }

    public Date getCreateDatetime() {
        return this.createDatetime;
    }

    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public String getUpdateWkstnId() {
        return this.updateWkstnId;
    }

    public void setUpdateWkstnId(String updateWkstnId) {
        this.updateWkstnId = updateWkstnId;
    }

    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }

    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    public String getSyncStatus() {
        return this.syncStatus;
    }

    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus;
    }

    public Date getLastSyncDatetime() {
        return this.lastSyncDatetime;
    }

    public void setLastSyncDatetime(Date lastSyncDatetime) {
        this.lastSyncDatetime = lastSyncDatetime;
    }

	public NicTransaction getNicTransaction() {
		return nicTransaction;
	}

	public void setNicTransaction(NicTransaction nicTransaction) {
		this.nicTransaction = nicTransaction;
	}

	public String getCancelType() {
		return cancelType;
	}

	public void setCancelType(String cancelType) {
		this.cancelType = cancelType;
	}

	public String getPrinterSerial() {
		return printerSerial;
	}

	public void setPrinterSerial(String printerSerial) {
		this.printerSerial = printerSerial;
	}

}
