
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationService {


    /**
     * 
     * @param cres
     * @return
     *     returns authen.Singlestring
     */
    @WebMethod(operationName = "GetAccessToken", action = "http://tempuri.org/AuthenticationService/GetAccessToken")
    @WebResult(name = "GetAccessTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccessToken", targetNamespace = "http://tempuri.org/", className = "authen.GetAccessToken")
    @ResponseWrapper(localName = "GetAccessTokenResponse", targetNamespace = "http://tempuri.org/", className = "authen.GetAccessTokenResponse")
    public Singlestring getAccessToken(
        @WebParam(name = "cres", targetNamespace = "http://tempuri.org/")
        Credential cres);

    /**
     * 
     * @param cres
     * @return
     *     returns authen.Singlestring
     */
    @WebMethod(operationName = "GetAccessTokenAdvange", action = "http://tempuri.org/AuthenticationService/GetAccessTokenAdvange")
    @WebResult(name = "GetAccessTokenAdvangeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccessTokenAdvange", targetNamespace = "http://tempuri.org/", className = "authen.GetAccessTokenAdvange")
    @ResponseWrapper(localName = "GetAccessTokenAdvangeResponse", targetNamespace = "http://tempuri.org/", className = "authen.GetAccessTokenAdvangeResponse")
    public Singlestring getAccessTokenAdvange(
        @WebParam(name = "cres", targetNamespace = "http://tempuri.org/")
        Credential cres);

    /**
     * 
     * @param cres
     * @return
     *     returns authen.Singlestring
     */
    @WebMethod(operationName = "GetAccessTokenDigest", action = "http://tempuri.org/AuthenticationService/GetAccessTokenDigest")
    @WebResult(name = "GetAccessTokenDigestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccessTokenDigest", targetNamespace = "http://tempuri.org/", className = "authen.GetAccessTokenDigest")
    @ResponseWrapper(localName = "GetAccessTokenDigestResponse", targetNamespace = "http://tempuri.org/", className = "authen.GetAccessTokenDigestResponse")
    public Singlestring getAccessTokenDigest(
        @WebParam(name = "cres", targetNamespace = "http://tempuri.org/")
        Credential cres);

}
