package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RptStatisticsTransmitData generated by hbm2java
 */
public class EppInventory implements java.io.Serializable {
    /**
     * 
     */

	public static final String CHUA_SU_DUNG = "I";
	public static final String DA_IN = "D";
	public static final String IN_HONG = "H";
	public static final String PHOI_LOI = "L";
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Integer id;
	private String name;
	private String code;
	private Integer officeId;
	private String description;
	private String active;
	private String address;
	
	public EppInventory() {
	}

	public Integer getId() {
		return id;
	}



	public void setId(Integer id) {
		this.id = id;
	}



	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getOfficeId() {
		return officeId;
	}

	public void setOfficeId(Integer officeId) {
		this.officeId = officeId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
