package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final


/**
 * EppPersonAttchmnt generated by hbm2java
 */
public class EppPersonAttchmnt implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private Long personId;
    private String type_;
    private Integer serialNo;
    private String fileName;
    private String base64;
	
	
	public EppPersonAttchmnt() {
		super();
	}


	public EppPersonAttchmnt(Long id, Long personId, String type_,
			Integer serialNo, String fileName, String base64) {
		super();
		this.id = id;
		this.personId = personId;
		this.type_ = type_;
		this.serialNo = serialNo;
		this.fileName = fileName;
		this.base64 = base64;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public Long getPersonId() {
		return personId;
	}


	public void setPersonId(Long personId) {
		this.personId = personId;
	}


	public String getType_() {
		return type_;
	}


	public void setType_(String type_) {
		this.type_ = type_;
	}


	public Integer getSerialNo() {
		return serialNo;
	}


	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}


	public String getFileName() {
		return fileName;
	}


	public void setFileName(String fileName) {
		this.fileName = fileName;
	}


	public String getBase64() {
		return base64;
	}


	public void setBase64(String base64) {
		this.base64 = base64;
	}

	
	
}
