package com.nec.asia.nic.comp.trans.domain;

// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class CountryData implements java.io.Serializable {

	private String id;
	private String name;
	private String numCode;
	private String alpha2Code;
	private String alpha3Code;
	private String nationality;

	public CountryData() {
	}


	public CountryData( String name, String numCode,
			String alpha2Code, String alpha3Code, String nationality) {
		this.name = name;
		this.numCode = numCode;
		this.alpha2Code = alpha2Code;
		this.nationality = nationality;
		this.alpha3Code = alpha3Code;
	}

	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumCode() {
		return this.numCode;
	}

	public void setNumCode(String numCode) {
		this.numCode = numCode;
	}

	public String getAlpha2Code() {
		return this.alpha2Code;
	}

	public void setAlpha2Code(String alpha2Code) {
		this.alpha2Code = alpha2Code;
	}
	
	public String getAlpha3Code() {
		return this.alpha3Code;
	}

	public void setAlpha3Code(String alpha3Code) {
		this.alpha3Code = alpha3Code;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

}
