package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * QueuesJobSchedule generated by hbm2java
 */
public class QueuesJobSchedule implements java.io.Serializable {
	
	public static final String TYPE_TRANSACTION_RECIEPTNO = "RNO"; 
	public static final String TYPE_TRANSACTION_AUTHENTICATION = "AUTH"; 
	public static final String TYPE_TRANSACTION_LDS = "LDS"; 
	public static final String TYPE_TRANSACTION_SYNC = "SYNC"; 

	public static final String STATUS_JOB_NEW = "NEW"; 
	public static final String STATUS_JOB_PENDING = "PENDING"; 
	public static final String STATUS_JOB_SUCCESS = "SUCCESS "; 
	public static final String STATUS_JOB_ERROR = "ERROR"; 
	
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private Long recordId;
    private String code;
	private String typeTransaction;
	private String name;
	private String passportType;
	private String description;
	private String status;
	private String typeLogJob;
	
	public QueuesJobSchedule() {
	}
	
	public QueuesJobSchedule(Long id) {
		this.id = id;
	}

	public QueuesJobSchedule(Long id, Long recordId, String code,
			String typeTransaction, String name, String passportType,
			String description, String status, String typeLogJob) {
		super();
		this.id = id;
		this.recordId = recordId;
		this.code = code;
		this.typeTransaction = typeTransaction;
		this.name = name;
		this.passportType = passportType;
		this.description = description;
		this.status = status;
		this.typeLogJob = typeLogJob;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRecordId() {
		return recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTypeTransaction() {
		return typeTransaction;
	}

	public void setTypeTransaction(String typeTransaction) {
		this.typeTransaction = typeTransaction;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassportType() {
		return passportType;
	}

	public void setPassportType(String passportType) {
		this.passportType = passportType;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTypeLogJob() {
		return typeLogJob;
	}

	public void setTypeLogJob(String typeLogJob) {
		this.typeLogJob = typeLogJob;
	}

	
}
