package com.nec.asia.nic.framework.report.domain;

import java.util.Date;
// default package
// Generated Jun 29, 2013 3:31:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * VRicTxn generated by hbm2java
 */
public class VRicTxn implements java.io.Serializable {

	private String nin;
	private String transactionId;
	private String firstname;
	private String surname;
	private String surnameBirth;
	private String transactionType;
	private String transactionSubtype;
	private String transactionStatus;
	private String gender;
	private Date applicationDate;
	private String servedBy;
	private String regOfficerId;

	public VRicTxn() {
	}

	public VRicTxn(String nin, String transactionId) {
		this.nin = nin;
		this.transactionId = transactionId;
	}

	public VRicTxn(String nin, String transactionId, String firstname,
			String surname, String surnameBirth, String transactionType,
			String transactionSubtype, String transactionStatus, String gender,
			Date applicationDate, String servedBy,String regOfficerId) {
		this.nin = nin;
		this.transactionId = transactionId;
		this.firstname = firstname;
		this.surname = surname;
		this.surnameBirth = surnameBirth;
		this.transactionType = transactionType;
		this.transactionSubtype = transactionSubtype;
		this.transactionStatus = transactionStatus;
		this.gender = gender;
		this.applicationDate = applicationDate;
		this.servedBy = servedBy;
		this.regOfficerId=regOfficerId;
	}

	public String getNin() {
		return this.nin;
	}

	public void setNin(String nin) {
		this.nin = nin;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getSurnameBirth() {
		return this.surnameBirth;
	}

	public void setSurnameBirth(String surnameBirth) {
		this.surnameBirth = surnameBirth;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getTransactionSubtype() {
		return this.transactionSubtype;
	}

	public void setTransactionSubtype(String transactionSubtype) {
		this.transactionSubtype = transactionSubtype;
	}

	public String getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getApplicationDate() {
		return this.applicationDate;
	}

	public void setApplicationDate(Date applicationDate) {
		this.applicationDate = applicationDate;
	}

	public String getServedBy() {
		return this.servedBy;
	}

	public void setServedBy(String servedBy) {
		this.servedBy = servedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VRicTxn))
			return false;
		VRicTxn castOther = (VRicTxn) other;

		return ((this.getNin() == castOther.getNin()) || (this.getNin() != null
				&& castOther.getNin() != null && this.getNin().equals(
				castOther.getNin())))
				&& ((this.getTransactionId() == castOther.getTransactionId()) || (this
						.getTransactionId() != null
						&& castOther.getTransactionId() != null && this
						.getTransactionId()
						.equals(castOther.getTransactionId())))
				&& ((this.getFirstname() == castOther.getFirstname()) || (this
						.getFirstname() != null
						&& castOther.getFirstname() != null && this
						.getFirstname().equals(castOther.getFirstname())))
				&& ((this.getSurname() == castOther.getSurname()) || (this
						.getSurname() != null && castOther.getSurname() != null && this
						.getSurname().equals(castOther.getSurname())))
				&& ((this.getSurnameBirth() == castOther.getSurnameBirth()) || (this
						.getSurnameBirth() != null
						&& castOther.getSurnameBirth() != null && this
						.getSurnameBirth().equals(castOther.getSurnameBirth())))
				&& ((this.getTransactionType() == castOther
						.getTransactionType()) || (this.getTransactionType() != null
						&& castOther.getTransactionType() != null && this
						.getTransactionType().equals(
								castOther.getTransactionType())))
				&& ((this.getTransactionSubtype() == castOther
						.getTransactionSubtype()) || (this
						.getTransactionSubtype() != null
						&& castOther.getTransactionSubtype() != null && this
						.getTransactionSubtype().equals(
								castOther.getTransactionSubtype())))
				&& ((this.getTransactionStatus() == castOther
						.getTransactionStatus()) || (this
						.getTransactionStatus() != null
						&& castOther.getTransactionStatus() != null && this
						.getTransactionStatus().equals(
								castOther.getTransactionStatus())))
				&& ((this.getGender() == castOther.getGender()) || (this
						.getGender() != null && castOther.getGender() != null && this
						.getGender().equals(castOther.getGender())))
				&& ((this.getApplicationDate() == castOther
						.getApplicationDate()) || (this.getApplicationDate() != null
						&& castOther.getApplicationDate() != null && this
						.getApplicationDate().equals(
								castOther.getApplicationDate())))
				&& ((this.getServedBy() == castOther.getServedBy()) || (this
						.getServedBy() != null
						&& castOther.getServedBy() != null && this
						.getServedBy().equals(castOther.getServedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNin() == null ? 0 : this.getNin().hashCode());
		result = 37
				* result
				+ (getTransactionId() == null ? 0 : this.getTransactionId()
						.hashCode());
		result = 37 * result
				+ (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		result = 37 * result
				+ (getSurname() == null ? 0 : this.getSurname().hashCode());
		result = 37
				* result
				+ (getSurnameBirth() == null ? 0 : this.getSurnameBirth()
						.hashCode());
		result = 37
				* result
				+ (getTransactionType() == null ? 0 : this.getTransactionType()
						.hashCode());
		result = 37
				* result
				+ (getTransactionSubtype() == null ? 0 : this
						.getTransactionSubtype().hashCode());
		result = 37
				* result
				+ (getTransactionStatus() == null ? 0 : this
						.getTransactionStatus().hashCode());
		result = 37 * result
				+ (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37
				* result
				+ (getApplicationDate() == null ? 0 : this.getApplicationDate()
						.hashCode());
		result = 37 * result
				+ (getServedBy() == null ? 0 : this.getServedBy().hashCode());
		return result;
	}

	public String getRegOfficerId() {
		return regOfficerId;
	}

	public void setRegOfficerId(String regOfficerId) {
		this.regOfficerId = regOfficerId;
	}
}
