package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RptStatisticsTransmitData generated by hbm2java
 */
public class EppInventoryItemsDetail implements java.io.Serializable {
    /**
     * 
     */

    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
	private Long inventoryItemsId;
	private Date updateTs;
	private String updatedBy;
	private String status;
	private String chipSeriesNo;
	private String batchNo;
	private String docChars;
	private String docNum;
	private String issuedDate;
	private String syncStatus;
	
	public EppInventoryItemsDetail() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getInventoryItemsId() {
		return inventoryItemsId;
	}

	public void setInventoryItemsId(Long inventoryItemsId) {
		this.inventoryItemsId = inventoryItemsId;
	}

	public Date getUpdateTs() {
		return updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getChipSeriesNo() {
		return chipSeriesNo;
	}

	public void setChipSeriesNo(String chipSeriesNo) {
		this.chipSeriesNo = chipSeriesNo;
	}

	public String getDocChars() {
		return docChars;
	}

	public void setDocChars(String docChars) {
		this.docChars = docChars;
	}

	public String getDocNum() {
		return docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	public String getIssuedDate() {
		return issuedDate;
	}

	public void setIssuedDate(String issuedDate) {
		this.issuedDate = issuedDate;
	}

	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getSyncStatus() {
		return syncStatus;
	}

	public void setSyncStatus(String syncStatus) {
		this.syncStatus = syncStatus;
	}

	
	
}
