package com.nec.asia.nic.comp.dispatch.domain;
// Generated Jan 20, 2016 1:09:15 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * DispatchQueueData generated by hbm2java
 */
public class DispatchQueueData implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private Long queueId;
	private String batchNumber;
	private String documentType;
	private int priority;
	private int batchSize;
	private String collectionSite;
	private Date collectionDate;
	private String passportNo;
	private String transactionId;
	private String packageNo;
	private Character status;

	public DispatchQueueData() {
	}

	public DispatchQueueData(Long queueId, String batchNumber, int priority, int batchSize,
			String collectionSite, String passportNo, String transactionId) {
		this.queueId = queueId;
		this.batchNumber = batchNumber;
		this.priority = priority;
		this.batchSize = batchSize;
		this.collectionSite = collectionSite;
		this.passportNo = passportNo;
		this.transactionId = transactionId;
	}

	public DispatchQueueData(Long queueId, String batchNumber, String documentType, int priority, int batchSize,
			String collectionSite, Date collectionDate, String passportNo, String transactionId, String packageNo,
			Character status) {
		this.queueId = queueId;
		this.batchNumber = batchNumber;
		this.documentType = documentType;
		this.priority = priority;
		this.batchSize = batchSize;
		this.collectionSite = collectionSite;
		this.collectionDate = collectionDate;
		this.passportNo = passportNo;
		this.transactionId = transactionId;
		this.packageNo = packageNo;
		this.status = status;
	}

	public Long getQueueId() {
		return this.queueId;
	}

	public void setQueueId(Long queueId) {
		this.queueId = queueId;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public int getBatchSize() {
		return this.batchSize;
	}

	public void setBatchSize(int batchSize) {
		this.batchSize = batchSize;
	}

	public String getCollectionSite() {
		return this.collectionSite;
	}

	public void setCollectionSite(String collectionSite) {
		this.collectionSite = collectionSite;
	}

	public Date getCollectionDate() {
		return this.collectionDate;
	}

	public void setCollectionDate(Date collectionDate) {
		this.collectionDate = collectionDate;
	}

	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getPackageNo() {
		return this.packageNo;
	}

	public void setPackageNo(String packageNo) {
		this.packageNo = packageNo;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
