//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 03:36:12 PM ICT 
//


package com.nec.asia.epp.perso.dispatchInfo;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.nec.asia.nic.dx.utils.DateAdapter;


/**
 * <p>Java class for dispatchInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dispatchInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batchNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="docType" type="{http://epass.asia.nec.com/pps/dispatchInfo}docTypeType"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="batchSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="collectLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="documents" type="{http://epass.asia.nec.com/pps/dispatchInfo}documentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dispatchInfoType", propOrder = {
    "batchNum",
    "docType",
    "priority",
    "batchSize",
    "collectLocation",
    "collectionDate",
    "documents"
})
@XmlRootElement(name = "dispatchInfo")
public class DispatchInfo {

    @XmlElement(required = true)
    protected String batchNum;
    @XmlElement(required = true)
    protected DocTypeType docType;
    protected int priority;
    protected int batchSize;
    @XmlElement(required = true)
    protected String collectLocation;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(DateAdapter.class)
    @XmlSchemaType(name = "date")
    protected Date collectionDate;
    @XmlElement(required = true)
    protected DocumentType documents;

    /**
     * Gets the value of the batchNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchNum() {
        return batchNum;
    }

    /**
     * Sets the value of the batchNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchNum(String value) {
        this.batchNum = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * @return
     *     possible object is
     *     {@link DocTypeType }
     *     
     */
    public DocTypeType getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocTypeType }
     *     
     */
    public void setDocType(DocTypeType value) {
        this.docType = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the batchSize property.
     * 
     */
    public int getBatchSize() {
        return batchSize;
    }

    /**
     * Sets the value of the batchSize property.
     * 
     */
    public void setBatchSize(int value) {
        this.batchSize = value;
    }

    /**
     * Gets the value of the collectLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectLocation() {
        return collectLocation;
    }

    /**
     * Sets the value of the collectLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectLocation(String value) {
        this.collectLocation = value;
    }

    /**
     * Gets the value of the collectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCollectionDate() {
        return collectionDate;
    }

    /**
     * Sets the value of the collectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionDate(Date value) {
        this.collectionDate = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    public DocumentType getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setDocuments(DocumentType value) {
        this.documents = value;
    }

}
