package com.nec.asia.nic.comp.trans.dto;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * NicTransactionDTOPayment generated by hbm2java
 */
public class NicTransactionPaymentDto implements java.io.Serializable {

	private String transactionId;
	private String paymentId;
	private Double feeAmount;
	private Integer noCardLost;
	private Boolean reduceRateFlag;
	private Double reduceRateAmount;
	private Double paymentAmount;
	private String collectionOfficerId;
	private Date paymentTime;
	private Boolean waiverFlag;
	private String waiverReason;
	private String waiverOfficerId;
	private Double cashReceived;
	private Double balance;
	private String paymentStatus;
	private String createBy;
	private String createWkstnId;
	private Date createDate;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDate;

	public NicTransactionPaymentDto() {
	}

	public NicTransactionPaymentDto(NicTransactionDto nicTransaction,
			String paymentId, Double feeAmount) {
		this.paymentId = paymentId;
		this.feeAmount = feeAmount;
	}

	public NicTransactionPaymentDto(NicTransactionDto nicTransaction,
			String paymentId, Double feeAmount, Integer noCardLost,
			Boolean reduceRateFlag, Double reduceRateAmount,
			Double paymentAmount, String collectionOfficerId,
			Date paymentTime, Boolean waiverFlag, String waiverReason,
			String waiverOfficerId, Double cashReceived,
			Double balance, String paymentStatus, String createBy,
			String createWkstnId, Date createDate, String updateBy,
			String updateWkstnId, Date updateDate) {
		this.paymentId = paymentId;
		this.feeAmount = feeAmount;
		this.noCardLost = noCardLost;
		this.reduceRateFlag = reduceRateFlag;
		this.reduceRateAmount = reduceRateAmount;
		this.paymentAmount = paymentAmount;
		this.collectionOfficerId = collectionOfficerId;
		this.paymentTime = paymentTime;
		this.waiverFlag = waiverFlag;
		this.waiverReason = waiverReason;
		this.waiverOfficerId = waiverOfficerId;
		this.cashReceived = cashReceived;
		this.balance = balance;
		this.paymentStatus = paymentStatus;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDate = updateDate;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	public Double getFeeAmount() {
		return this.feeAmount;
	}

	public void setFeeAmount(Double feeAmount) {
		this.feeAmount = feeAmount;
	}

	public Integer getNoCardLost() {
		return this.noCardLost;
	}

	public void setNoCardLost(Integer noCardLost) {
		this.noCardLost = noCardLost;
	}

	public Boolean getReduceRateFlag() {
		return this.reduceRateFlag;
	}

	public void setReduceRateFlag(Boolean reduceRateFlag) {
		this.reduceRateFlag = reduceRateFlag;
	}

	public Double getReduceRateAmount() {
		return this.reduceRateAmount;
	}

	public void setReduceRateAmount(Double reduceRateAmount) {
		this.reduceRateAmount = reduceRateAmount;
	}

	public Double getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	public String getCollectionOfficerId() {
		return this.collectionOfficerId;
	}

	public void setCollectionOfficerId(String collectionOfficerId) {
		this.collectionOfficerId = collectionOfficerId;
	}

	public Date getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}

	public Boolean getWaiverFlag() {
		return this.waiverFlag;
	}

	public void setWaiverFlag(Boolean waiverFlag) {
		this.waiverFlag = waiverFlag;
	}

	public String getWaiverReason() {
		return this.waiverReason;
	}

	public void setWaiverReason(String waiverReason) {
		this.waiverReason = waiverReason;
	}

	public String getWaiverOfficerId() {
		return this.waiverOfficerId;
	}

	public void setWaiverOfficerId(String waiverOfficerId) {
		this.waiverOfficerId = waiverOfficerId;
	}

	public Double getCashReceived() {
		return this.cashReceived;
	}

	public void setCashReceived(Double cashReceived) {
		this.cashReceived = cashReceived;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
