package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NicTransaction generated by hbm2java
 */
public class DataJson implements Serializable {

	public DataJson() {
	}

	@JsonProperty("passportNo")
	private String passportNo;
	@JsonProperty("passportYear")
	private String passportYear;
	@JsonProperty("transactionId")
	private String transactionId;

	public String getPassportNo() {
		return passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public String getPassportYear() {
		return passportYear;
	}

	public void setPassportYear(String passportYear) {
		this.passportYear = passportYear;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

}