package com.nec.asia.nic.comp.trans.domain;

// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class AttachmentDoc implements java.io.Serializable {

	private static final long serialVersionUID = 4030959704968010599L;

	private String type;
/*	private String fileName;
	private String fileId;*/
	private Integer serialNo;
	private String base64;
/*	private String description;*/

	public AttachmentDoc() {
	}


	public AttachmentDoc(String type, String fileName, String fileId, Integer serialNo, String base64, String description) {
		this.type = type;
/*		this.fileName = fileName;
		this.fileId = fileId;*/
		this.serialNo = serialNo;
		this.base64 = base64;
/*		this.description = description;*/
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/*public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}
*/
	public Integer getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}
	public String getBase64() {
		return this.base64;
	}

	public void setBase64(String base64) {
		this.base64 = base64;
	}
	/*public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}*/
}
