package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class PassportInformation implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L;

	private String passportNo;
	private String type;
	private String dateOfIssue;
	private String dateOfExpiry;
	private String icaoLine1;
	private String icaoLine2;
	private String signerName;
	private String signerPosition;
	private OfficeData placeOfIdIssue;
	private String description;
	private String status;
	private String chipSerialNo;
	private String fpEnCode;
	private String isPassport; 


	public PassportInformation() {
	}

	public PassportInformation(String passportNo) {
		this.passportNo = passportNo;
	}

	
	public PassportInformation(String passportNo, String type, String dateOfIssue, String dateOfExpiry,
			String icaoLine1, String icaoLine2, String signerName, String signerPosition, OfficeData placeOfIdIssue,
			String description, String status) {
		
		this.passportNo = passportNo;
		this.type = type;
		this.dateOfIssue = dateOfIssue;
		this.dateOfExpiry = dateOfExpiry;
		this.icaoLine1 = icaoLine1;
		this.icaoLine2 = icaoLine2;
		this.signerName = signerName;
		this.signerPosition = signerPosition;
		this.placeOfIdIssue = placeOfIdIssue;
		this.description = description;
		this.status = status;
	}

	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDateOfIssue() {
		return this.dateOfIssue;
	}

	public void setDateOfIssue(String dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}
	
	public String getDateOfExpiry() {
		return this.dateOfExpiry;
	}

	public void setDateOfExpiry(String dateOfExpiry) {
		this.dateOfExpiry = dateOfExpiry;
	}

	public String getIcaoLine1() {
		return this.icaoLine1;
	}

	public void setIcaoLine1(String icaoLine1) {
		this.icaoLine1 = icaoLine1;
	}

	public String getIcaoLine2() {
		return this.icaoLine2;
	}

	public void setIcaoLine2(String icaoLine2) {
		this.icaoLine2 = icaoLine2;
	}

	public String getSignerName() {
		return this.signerName;
	}

	public void setSignerName(String signerName) {
		this.signerName = signerName;
	}

	public String getSignerPosition() {
		return this.signerPosition;
	}

	public void setSignerPosition(String signerPosition) {
		this.signerPosition = signerPosition;
	}

	public OfficeData getPlaceOfIssue() {
		return this.placeOfIdIssue;
	}

	public void setPlaceOfIssue(OfficeData placeOfIdIssue) {
		this.placeOfIdIssue = placeOfIdIssue;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getChipSerialNo() {
		return chipSerialNo;
	}

	public void setChipSerialNo(String chipSerialNo) {
		this.chipSerialNo = chipSerialNo;
	}

	public String getFpEnCode() {
		return fpEnCode;
	}

	public void setFpEnCode(String fpEnCode) {
		this.fpEnCode = fpEnCode;
	}

	public String getIsPassport() {
		return isPassport;
	}

	public void setIsPassport(String isPassport) {
		this.isPassport = isPassport;
	}
}