package com.nec.asia.nic.comp.trans.dto;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */

/* 
 * Modification History:
 * 
 * 28 Jun 2013 (chris): Add Column  DATE_OF_ISSUE.
 */
public class NicTransactionDto implements java.io.Serializable {
	//CORE TRANSACTION
	public static final String TRANSACTION_TYPE_REGISTRATION 		= "REG";
	public static final String TRANSACTION_TYPE_REPLACEMENT 		= "REP";
	public static final String TRANSACTION_TYPE_PARTICULAR_UPDATE 	= "PAR_UPD";
	public static final String TRANSACTION_TYPE_CONVERSION	 		= "CON";
	//UPDATE OF TRANSACTION
	public static final String TRANSACTION_TYPE_CARD_ISSUANCE		= "CAR_ISS";
	public static final String TRANSACTION_TYPE_CARD_SUSPENSION		= "CAR_SUS";
	public static final String TRANSACTION_TYPE_CARD_REACTIVATION	= "CAR_REA";
	public static final String TRANSACTION_TYPE_CARD_TERMINATION	= "CAR_TER";

	private String transactionId;
	private String queueNumber;
	private String applnRefNo;
	private String nin;
	private Date   dateOfApplication;
	private Date   dateOfIssue; //date of application approved.
	private String regSiteCode;
	private String issSiteCode;
	private String transactionType;
	private String transactionSubtype;
	private String transactionStatus;
	private String createBy;
	private String createWkstnId;
	private Date createDate;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDate;
	public NicTransactionDto() {
	}

	public NicTransactionDto(String transactionId) {
		this.transactionId = transactionId;
	}

	public NicTransactionDto(String transactionId, String queueNumber,
			String applnRefNo, String nin, Date dateOfApplication,
			String regSiteCode, String issSiteCode, String transactionType,
			String transactionSubtype, String transactionStatus,
			String createBy, String createWkstnId, Date createDate,
			String updateBy, String updateWkstnId, Date updateDate) {
		this.transactionId = transactionId;
		this.queueNumber = queueNumber;
		this.applnRefNo = applnRefNo;
		this.nin = nin;
		this.dateOfApplication = dateOfApplication;
		this.regSiteCode = regSiteCode;
		this.issSiteCode = issSiteCode;
		this.transactionType = transactionType;
		this.transactionSubtype = transactionSubtype;
		this.transactionStatus = transactionStatus;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDate = updateDate;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getQueueNumber() {
		return this.queueNumber;
	}

	public void setQueueNumber(String queueNumber) {
		this.queueNumber = queueNumber;
	}

	public String getApplnRefNo() {
		return this.applnRefNo;
	}

	public void setApplnRefNo(String applnRefNo) {
		this.applnRefNo = applnRefNo;
	}

	public String getNin() {
		return this.nin;
	}

	public void setNin(String nin) {
		this.nin = nin;
	}

	public Date getDateOfApplication() {
		return this.dateOfApplication;
	}

	public void setDateOfApplication(Date dateOfApplication) {
		this.dateOfApplication = dateOfApplication;
	}
	public Date getDateOfIssue() {
		return this.dateOfIssue;
	}

	public void setDateOfIssue(Date dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}
	public String getRegSiteCode() {
		return this.regSiteCode;
	}

	public void setRegSiteCode(String regSiteCode) {
		this.regSiteCode = regSiteCode;
	}

	public String getIssSiteCode() {
		return this.issSiteCode;
	}

	public void setIssSiteCode(String issSiteCode) {
		this.issSiteCode = issSiteCode;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getTransactionSubtype() {
		return this.transactionSubtype;
	}

	public void setTransactionSubtype(String transactionSubtype) {
		this.transactionSubtype = transactionSubtype;
	}

	public String getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
