package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

/**
 * NicFPDataId generated by hbm2java
 */
public class NicFPDataId implements java.io.Serializable {


	private static final long serialVersionUID = -3810692525993904329L;
	
	private String transactionId;
	private int fingerPosition;

	public NicFPDataId() {
	}

	public NicFPDataId(String transactionId, int fingerPosition) {
		this.transactionId = transactionId;
		this.fingerPosition = fingerPosition;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public int getFingerPosition() {
		return this.fingerPosition;
	}

	public void setFingerPosition(int fingerPosition) {
		this.fingerPosition = fingerPosition;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NicFPDataId))
			return false;
		NicFPDataId castOther = (NicFPDataId) other;

		return ((this.getTransactionId() == castOther.getTransactionId())
				|| (this.getTransactionId() != null && castOther.getTransactionId() != null
						&& this.getTransactionId().equals(castOther.getTransactionId())))
				&& (this.getFingerPosition() == castOther.getFingerPosition());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTransactionId() == null ? 0 : this.getTransactionId().hashCode());
		result = 37 * result + (int) this.getFingerPosition();
		return result;
	}

}
