package com.nec.asia.nic.admin.audit;

import java.util.HashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.nec.asia.nic.framework.admin.audit.impl.AbstractAuditService;
import com.nec.asia.nic.framework.admin.audit.impl.AuditBean;

/**
 * Default implementation of business action audit.
 * 
 * @author bright_zheng
 *
 */
public class DemoBusinessActionAuditServiceImpl extends AbstractAuditService{
	private static Logger logger = LoggerFactory.getLogger(DemoBusinessActionAuditServiceImpl.class);
	
	/**
	 * extract some info to construct AuditBean
	 * @see AuditBean
	 */
	public AuditBean extractToAuditBean(Object[] args){
		logger.debug("extracting args to auditBean");
		//DEMO only: mock data here
		AuditBean auditBean = new AuditBean();
//		auditBean.setModule("Registration");
//		//subject should come from request(e.g NRIC)
//		auditBean.setSubject("S1234567");
//		//what should come from source(current resource)
//		auditBean.setWhat("First Registration");
//		//state should come from source/request?
//		//when should be generated by system datetime
//		auditBean.setWhen("08-04-2010 12:00:00");
//		//where should come from session(current workstation)
//		auditBean.setWhere("Bright-Zheng laptop");
//		//who should come from session(current user)
//		auditBean.setWho("Bright Zheng");
//		
//		//need more info? I don't think so, but...anyway you can make it
//		HashMap<String, Object> extendInfo = new HashMap<String,Object>();
//		extendInfo.put("myextendinfo1", "Made in Singapore");
//		extendInfo.put("myextendinfo2", "Power by NEC asia");
//		auditBean.setExtendInfo(extendInfo);
		
		return auditBean;
	}
	
	@Override
	protected void store(AuditBean auditBean){
		super.store(auditBean);
		//DO THE REAL STORE LOGIC HERE
	}
}
