package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Entity;

/**
 * NicDecisionManager generated by hbm2java
 */
@Entity
public class BufEppPersonInvestigation implements java.io.Serializable {

	/**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private String transactionId;
    private String createBy;
	private String createWkstnId;
	private Date createDatetime;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDatetime;
    private String name;
    private String otherName;
    private String gender;
    private String dateOfBirth;
    private String placeOfBirthName;
    private String idNumber;
    private String dateOfIdIssue;
    private String ethnic;
    private String religion;
    private String searchName;
    private String nationalityName;
    private String residentPlaceName;
    private String residentAddress;
    private String tmpAddress;
    private String occupation;
    private String officeInfo;
    private String fatherName;
    private String fatherNationality;
    private String fatherOccupation;
    private String motherName;
    private String motherNationality;
    private String motherOccupation;
    private String transactionMasterId;
    private Long key;
    private String type;
    private String personCode;
    private String src;
    private String passportNo;
    private Long matchPoint;
    private String placeOfIdIssueName;
    private byte[] photo;
    private String isPushQueue;
    private String maCaNhan;
    private String orgPerson;
    private String dataType;
    
	public BufEppPersonInvestigation(){
		
	}
	
	public String getDataType() {
		return dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getOrgPerson() {
		return orgPerson;
	}

	public void setOrgPerson(String orgPerson) {
		this.orgPerson = orgPerson;
	}

	public String getMaCaNhan() {
		return maCaNhan;
	}


	public void setMaCaNhan(String maCaNhan) {
		this.maCaNhan = maCaNhan;
	}


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDatetime() {
		return createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOtherName() {
		return otherName;
	}

	public void setOtherName(String otherName) {
		this.otherName = otherName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getPlaceOfBirthName() {
		return placeOfBirthName;
	}

	public void setPlaceOfBirthName(String placeOfBirthName) {
		this.placeOfBirthName = placeOfBirthName;
	}

	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getDateOfIdIssue() {
		return dateOfIdIssue;
	}

	public void setDateOfIdIssue(String dateOfIdIssue) {
		this.dateOfIdIssue = dateOfIdIssue;
	}

	public String getEthnic() {
		return ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

	public String getReligion() {
		return religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getSearchName() {
		return searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	public String getNationalityName() {
		return nationalityName;
	}

	public void setNationalityName(String nationalityName) {
		this.nationalityName = nationalityName;
	}

	public String getResidentPlaceName() {
		return residentPlaceName;
	}

	public void setResidentPlaceName(String residentPlaceName) {
		this.residentPlaceName = residentPlaceName;
	}

	public String getResidentAddress() {
		return residentAddress;
	}

	public void setResidentAddress(String residentAddress) {
		this.residentAddress = residentAddress;
	}

	public String getTmpAddress() {
		return tmpAddress;
	}

	public void setTmpAddress(String tmpAddress) {
		this.tmpAddress = tmpAddress;
	}

	public String getOccupation() {
		return occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getOfficeInfo() {
		return officeInfo;
	}

	public void setOfficeInfo(String officeInfo) {
		this.officeInfo = officeInfo;
	}

	public String getFatherName() {
		return fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getFatherNationality() {
		return fatherNationality;
	}

	public void setFatherNationality(String fatherNationality) {
		this.fatherNationality = fatherNationality;
	}

	public String getFatherOccupation() {
		return fatherOccupation;
	}

	public void setFatherOccupation(String fatherOccupation) {
		this.fatherOccupation = fatherOccupation;
	}

	public String getMotherName() {
		return motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getMotherNationality() {
		return motherNationality;
	}

	public void setMotherNationality(String motherNationality) {
		this.motherNationality = motherNationality;
	}

	public String getMotherOccupation() {
		return motherOccupation;
	}

	public void setMotherOccupation(String motherOccupation) {
		this.motherOccupation = motherOccupation;
	}

	public String getTransactionMasterId() {
		return transactionMasterId;
	}

	public void setTransactionMasterId(String transactionMasterId) {
		this.transactionMasterId = transactionMasterId;
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPersonCode() {
		return personCode;
	}

	public void setPersonCode(String personCode) {
		this.personCode = personCode;
	}

	public String getSrc() {
		return src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public String getPassportNo() {
		return passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public Long getMatchPoint() {
		return matchPoint;
	}

	public void setMatchPoint(Long matchPoint) {
		this.matchPoint = matchPoint;
	}

	public String getPlaceOfIdIssueName() {
		return placeOfIdIssueName;
	}

	public void setPlaceOfIdIssueName(String placeOfIdIssueName) {
		this.placeOfIdIssueName = placeOfIdIssueName;
	}

	public byte[] getPhoto() {
		return photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public String getIsPushQueue() {
		return isPushQueue;
	}

	public void setIsPushQueue(String isPushQueue) {
		this.isPushQueue = isPushQueue;
	}

}
