package com.nec.asia.nic.comp.trans.domain;

// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class DocumentInfo implements java.io.Serializable {
	/**
     * 
     */
	/* Trạng thái hồ sơ */
	public final static String CREATED = "CREATED";// Khởi tạo
	public final static String PROCESSING = "PROCESSING"; // đang xử lý
	public final static String PROCESSED = "PROCESSED"; // đã xử lý
	public final static String REPROCESSING = "REPROCESSING"; // đang xử lý lại
	public final static String REPROCESSED = "REPROCESSED";// Đã xử lý lại
	public final static String INVESTIGATED = "INVESTIGATED"; // Đã tra cứu
	public final static String REINVESTIGATING = "REINVESTIGATING";// Đang tra cứu
	public final static String RETURNED = "RETURNED"; // Trả lại A08 do ko có người nhận
	public final static String DELIVERED = "DELIVERED";// Đã trả hộ chiếu cho CD
	public final static String ADDING = "ADDING";// Đang bổ sung
	public final static String ADDED = "ADDED"; // Đã bổ sung
	public final static String PERSONALIZING = "PERSONALIZING"; // Đang in
	public final static String PERSONALIZED = "PERSONALIZED"; // Đã in
	public final static String ISSUING = "ISSUING"; // Đang phát hành
	public final static String LIST_B_COMPLETE = "LIST_B_COMPLETE"; // Bổ sung kết quả phê duyệt của lãnh đạo
	public final static String LIST_B_SUBMIT = "LIST_B_SUBMIT"; // đã lập đề xuất
	public final static String NEED_APPENDED = "NEED_APPENDED"; // bổ sung xác minh thông tin
	public final static String LIST_B_REJECTED = "LIST_B_REJECTED"; // đã từ chối
	public final static String WAIT_FOR_PRINTING = "WAIT_FOR_PRINTING"; // Chờ in HC

	private static final long serialVersionUID = 4030959704968010599L;

	private String code;
	private PassportInformation passport;
	private PersonInformation person;
	private String phoneNo;
	/*private String occupation;
	private String officeInfo;*/
	private String isEpassport; // / Ho chieu dien tu: “Y”, Khong phải: “N”
	private String priority;
	private String prevPassportNo;
	private Date prevDateOfIssue;
	private String type;
	/*private String description;*/
	private OfficeData office;
	//private List<AttachmentDoc> attachments = new LinkedList<AttachmentDoc>();
	private String registrationNo;
	private String dateOfDelivery;
	private DocAttachment docattachment;
	private PersonAttachment perattachment;
	private String status;

	public DocumentInfo() {
	}

	public DocumentInfo(String code) {
		this.code = code;
	}

	public DocumentInfo(String code, PassportInformation passport,
			PersonInformation person, String phoneNo, PlaceData residentPlace,
			AreaData residentArea, String residentAddress, PlaceData tmpPlace,
			AreaData tmpArea, String tmpAddress, String occupation,
			String officeInfo, String isEpassport, String priority,
			String prevPassportNo, Date prevDateOfIssue, String type,
			String description, OfficeData office,
			List<AttachmentDoc> attachments) {
		this.code = code;
		this.passport = passport;
		this.person = person;
		this.phoneNo = phoneNo;
		/*this.occupation = occupation;
		this.officeInfo = officeInfo;*/
		this.isEpassport = isEpassport;
		this.priority = priority;
		this.prevDateOfIssue = prevDateOfIssue;
		this.prevPassportNo = prevPassportNo;
		this.type = type;
		/*this.description = description;*/
		this.office = office;
		//this.attachments = attachments;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public PassportInformation getPassport() {
		return this.passport;
	}

	public void setPassport(PassportInformation passport) {
		this.passport = passport;
	}

	public PersonInformation getPerson() {
		return this.person;
	}

	public void setPerson(PersonInformation person) {
		this.person = person;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	/*public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getOfficeInfo() {
		return this.officeInfo;
	}*/

	public String getRegistrationNo() {
		return registrationNo;
	}

	public void setRegistrationNo(String registrationNo) {
		this.registrationNo = registrationNo;
	}

	public String getDateOfDelivery() {
		return dateOfDelivery;
	}

	public void setDateOfDelivery(String dateOfDelivery) {
		this.dateOfDelivery = dateOfDelivery;
	}

	public DocAttachment getDocattachment() {
		return docattachment;
	}

	public void setDocattachment(DocAttachment docattachment) {
		this.docattachment = docattachment;
	}

	public PersonAttachment getPerattachment() {
		return perattachment;
	}

	public void setPerattachment(PersonAttachment perattachment) {
		this.perattachment = perattachment;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/*public void setOfficeInfo(String officeInfo) {
		this.officeInfo = officeInfo;
	}*/

	public String getIsEpassport() {
		return this.isEpassport;
	}

	public void setIsEpassport(String isEpassport) {
		this.isEpassport = isEpassport;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public Date getPrevDateOfIssue() {
		return this.prevDateOfIssue;
	}

	public void setPrevDateOfIssue(Date prevDateOfIssue) {
		this.prevDateOfIssue = prevDateOfIssue;
	}

	public String getPrevPassportNo() {
		return this.prevPassportNo;
	}

	public void setPrevPassportNo(String prevPassportNo) {
		this.prevPassportNo = prevPassportNo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/*public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}*/

	public OfficeData getOffice() {
		return this.office;
	}

	public void setOffice(OfficeData office) {
		this.office = office;
	}
/*
	public List<AttachmentDoc> getAttachments() {
		return this.attachments;
	}

	public void setAttachments(List<AttachmentDoc> attachments) {
		this.attachments = attachments;
	}*/

}
