package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * NicDecisionManager generated by hbm2java
 */

@XmlRootElement(name = "EppBlacklistAttachment")
@XmlAccessorType(XmlAccessType.FIELD)
public class EppBlacklistAttachment implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private Long blacklistId;
    private String type_;
    private String fileName;
	private String base64;
	
	public EppBlacklistAttachment(){
		
	}
	
	public EppBlacklistAttachment(Long id, Long blacklistId, String type_,
			String fileName, String base64) {
		super();
		this.id = id;
		this.blacklistId = blacklistId;
		this.type_ = type_;
		this.fileName = fileName;
		this.base64 = base64;
	}
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getBlacklistId() {
		return blacklistId;
	}
	public void setBlacklistId(Long blacklistId) {
		this.blacklistId = blacklistId;
	}
	public String getType_() {
		return type_;
	}
	public void setType_(String type_) {
		this.type_ = type_;
	}
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public String getBase64() {
		return base64;
	}
	public void setBase64(String base64) {
		this.base64 = base64;
	}
	
	
}
