package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * NicDecisionManager generated by hbm2java
 */

@XmlRootElement(name = "EppIdentificationAttachmnt")
@XmlAccessorType(XmlAccessType.FIELD)
public class EppIdentificationAttachmnt implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private Long identificationId;
    private String name;
    private String description;
	private String base64;
	
	public EppIdentificationAttachmnt(){
		
	}
	
	public EppIdentificationAttachmnt(Long id, Long identificationId, String name, String description,
			String base64) {
		super();
		this.id = id;
		this.identificationId = identificationId;
		this.name = name;
		this.description = description;
		this.base64 = base64;
	}

	public Long getIdentificationId() {
		return identificationId;
	}

	public void setIdentificationId(Long identificationId) {
		this.identificationId = identificationId;
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBase64() {
		return base64;
	}

	public void setBase64(String base64) {
		this.base64 = base64;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
}
