package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

/**
 * NicDecisionManager generated by hbm2java
 */

public class EppIdentification implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private String idNumber;
    private String transactionId;
    private String maCsdl;
    private String cmId;
	private String maDp;
	private String soCmnd;
	private String ctVt1;
	private String ctVt2;
	private String hoTen;
	private String tenKhac;
	private String maGioiTinh;
	private String ngaySinh;
	private String namSinh;
	private String noiSinh;
	private String nguyenQuan;
	private String maDpNq;
	private String maDpTt;
	private String maPxTt;
	private String thonPhoTt;
	private String soNhaTt;
	private String maNgheNghiep;
	private String noiLamViec;
	private String maDanToc;
	private String maTonGiao;
	private String maHocVan;
	private String hoTenCha;
	private String hoTenMe;
	private String hoTenVc;
	private String soCmndCu;
	private String ngayCapCu;
	private String maDpCap;
	private String dauVetRieng;
	private String ngayKhai;
	private String imgId;
	private String tenAnhTruoc;
	private String tenAnhSau;
	private String thuMuc;
	private byte[] anhTruoc;
	private byte[] anhSau;
	
	public EppIdentification() {
		super();
	}

	public EppIdentification(Long id, String idNumber, String transactionId,
			String maCsdl, String cmId, String maDp, String soCmnd,
			String ctVt1, String ctVt2, String hoTen, String tenKhac,
			String maGioiTinh, String ngaySinh, String namSinh, String noiSinh,
			String nguyenQuan, String maDpNq, String maDpTt, String maPxTt,
			String thonPhoTt, String soNhaTt, String maNgheNghiep,
			String noiLamViec, String maDanToc, String maTonGiao,
			String maHocVan, String hoTenCha, String hoTenMe, String hoTenVc,
			String soCmndCu, String ngayCapCu, String maDpCap,
			String dauVetRieng, String ngayKhai, String imgId,
			String tenAnhTruoc, String tenAnhSau, String thuMuc,
			byte[] anhTruoc, byte[] anhSau) {
		super();
		this.id = id;
		this.idNumber = idNumber;
		this.transactionId = transactionId;
		this.maCsdl = maCsdl;
		this.cmId = cmId;
		this.maDp = maDp;
		this.soCmnd = soCmnd;
		this.ctVt1 = ctVt1;
		this.ctVt2 = ctVt2;
		this.hoTen = hoTen;
		this.tenKhac = tenKhac;
		this.maGioiTinh = maGioiTinh;
		this.ngaySinh = ngaySinh;
		this.namSinh = namSinh;
		this.noiSinh = noiSinh;
		this.nguyenQuan = nguyenQuan;
		this.maDpNq = maDpNq;
		this.maDpTt = maDpTt;
		this.maPxTt = maPxTt;
		this.thonPhoTt = thonPhoTt;
		this.soNhaTt = soNhaTt;
		this.maNgheNghiep = maNgheNghiep;
		this.noiLamViec = noiLamViec;
		this.maDanToc = maDanToc;
		this.maTonGiao = maTonGiao;
		this.maHocVan = maHocVan;
		this.hoTenCha = hoTenCha;
		this.hoTenMe = hoTenMe;
		this.hoTenVc = hoTenVc;
		this.soCmndCu = soCmndCu;
		this.ngayCapCu = ngayCapCu;
		this.maDpCap = maDpCap;
		this.dauVetRieng = dauVetRieng;
		this.ngayKhai = ngayKhai;
		this.imgId = imgId;
		this.tenAnhTruoc = tenAnhTruoc;
		this.tenAnhSau = tenAnhSau;
		this.thuMuc = thuMuc;
		this.anhTruoc = anhTruoc;
		this.anhSau = anhSau;
	}

	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public byte[] getAnhTruoc() {
		return anhTruoc;
	}

	public void setAnhTruoc(byte[] anhTruoc) {
		this.anhTruoc = anhTruoc;
	}

	public byte[] getAnhSau() {
		return anhSau;
	}

	public void setAnhSau(byte[] anhSau) {
		this.anhSau = anhSau;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getMaCsdl() {
		return maCsdl;
	}

	public void setMaCsdl(String maCsdl) {
		this.maCsdl = maCsdl;
	}

	public String getCmId() {
		return cmId;
	}

	public void setCmId(String cmId) {
		this.cmId = cmId;
	}

	public String getMaDp() {
		return maDp;
	}

	public void setMaDp(String maDp) {
		this.maDp = maDp;
	}

	public String getSoCmnd() {
		return soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	public String getCtVt1() {
		return ctVt1;
	}

	public void setCtVt1(String ctVt1) {
		this.ctVt1 = ctVt1;
	}

	public String getCtVt2() {
		return ctVt2;
	}

	public void setCtVt2(String ctVt2) {
		this.ctVt2 = ctVt2;
	}

	public String getHoTen() {
		return hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public String getTenKhac() {
		return tenKhac;
	}

	public void setTenKhac(String tenKhac) {
		this.tenKhac = tenKhac;
	}

	public String getMaGioiTinh() {
		return maGioiTinh;
	}

	public void setMaGioiTinh(String maGioiTinh) {
		this.maGioiTinh = maGioiTinh;
	}

	public String getNgaySinh() {
		return ngaySinh;
	}

	public void setNgaySinh(String ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getNamSinh() {
		return namSinh;
	}

	public void setNamSinh(String namSinh) {
		this.namSinh = namSinh;
	}

	public String getNoiSinh() {
		return noiSinh;
	}

	public void setNoiSinh(String noiSinh) {
		this.noiSinh = noiSinh;
	}

	public String getNguyenQuan() {
		return nguyenQuan;
	}

	public void setNguyenQuan(String nguyenQuan) {
		this.nguyenQuan = nguyenQuan;
	}

	public String getMaDpNq() {
		return maDpNq;
	}

	public void setMaDpNq(String maDpNq) {
		this.maDpNq = maDpNq;
	}

	public String getMaDpTt() {
		return maDpTt;
	}

	public void setMaDpTt(String maDpTt) {
		this.maDpTt = maDpTt;
	}

	public String getMaPxTt() {
		return maPxTt;
	}

	public void setMaPxTt(String maPxTt) {
		this.maPxTt = maPxTt;
	}

	public String getThonPhoTt() {
		return thonPhoTt;
	}

	public void setThonPhoTt(String thonPhoTt) {
		this.thonPhoTt = thonPhoTt;
	}

	public String getSoNhaTt() {
		return soNhaTt;
	}

	public void setSoNhaTt(String soNhaTt) {
		this.soNhaTt = soNhaTt;
	}

	public String getMaNgheNghiep() {
		return maNgheNghiep;
	}

	public void setMaNgheNghiep(String maNgheNghiep) {
		this.maNgheNghiep = maNgheNghiep;
	}

	public String getNoiLamViec() {
		return noiLamViec;
	}

	public void setNoiLamViec(String noiLamViec) {
		this.noiLamViec = noiLamViec;
	}

	public String getMaDanToc() {
		return maDanToc;
	}

	public void setMaDanToc(String maDanToc) {
		this.maDanToc = maDanToc;
	}

	public String getMaTonGiao() {
		return maTonGiao;
	}

	public void setMaTonGiao(String maTonGiao) {
		this.maTonGiao = maTonGiao;
	}

	public String getMaHocVan() {
		return maHocVan;
	}

	public void setMaHocVan(String maHocVan) {
		this.maHocVan = maHocVan;
	}

	public String getHoTenCha() {
		return hoTenCha;
	}

	public void setHoTenCha(String hoTenCha) {
		this.hoTenCha = hoTenCha;
	}

	public String getHoTenMe() {
		return hoTenMe;
	}

	public void setHoTenMe(String hoTenMe) {
		this.hoTenMe = hoTenMe;
	}

	public String getHoTenVc() {
		return hoTenVc;
	}

	public void setHoTenVc(String hoTenVc) {
		this.hoTenVc = hoTenVc;
	}

	public String getSoCmndCu() {
		return soCmndCu;
	}

	public void setSoCmndCu(String soCmndCu) {
		this.soCmndCu = soCmndCu;
	}

	public String getNgayCapCu() {
		return ngayCapCu;
	}

	public void setNgayCapCu(String ngayCapCu) {
		this.ngayCapCu = ngayCapCu;
	}

	public String getMaDpCap() {
		return maDpCap;
	}

	public void setMaDpCap(String maDpCap) {
		this.maDpCap = maDpCap;
	}

	public String getDauVetRieng() {
		return dauVetRieng;
	}

	public void setDauVetRieng(String dauVetRieng) {
		this.dauVetRieng = dauVetRieng;
	}

	public String getNgayKhai() {
		return ngayKhai;
	}

	public void setNgayKhai(String ngayKhai) {
		this.ngayKhai = ngayKhai;
	}

	public String getImgId() {
		return imgId;
	}

	public void setImgId(String imgId) {
		this.imgId = imgId;
	}

	public String getTenAnhTruoc() {
		return tenAnhTruoc;
	}

	public void setTenAnhTruoc(String tenAnhTruoc) {
		this.tenAnhTruoc = tenAnhTruoc;
	}

	public String getTenAnhSau() {
		return tenAnhSau;
	}

	public void setTenAnhSau(String tenAnhSau) {
		this.tenAnhSau = tenAnhSau;
	}

	public String getThuMuc() {
		return thuMuc;
	}

	public void setThuMuc(String thuMuc) {
		this.thuMuc = thuMuc;
	}
}
