package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicDecisionManager generated by hbm2java
 */
public class EppPerson implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long personId;
    private String personCode;
    private String orgPerson;
    private String refId;
    private String name;
	private String otherName;
	private String searchName;
	private String gender;
	private String dateOfBirth;
	private String placeOfBirthCode; 
	private String placeOfBirthName; 
	private String idNumber; 
	private String dateOfIdIssue;
	private String placeOfIdIssueName;  
	private String ethnic; 
	private String religion;
	private String ethnicCode;
	private String religionCode;
	private String nationalityName; 
	private String nationalityCode;
	private String fatherName;
	private String fatherSearchName;
	private String motherName; 
	private String motherSearchName;
	private String countryOfBirth;
	private String createdBy;
	private Date createTs;
	private String updatedBy;
	private Date updateTs;
	private Boolean isChecked;
	private String description;
	private String srcOffice; 
	private String srcDoc; 
	private String status;
	private String createdByName; 
	private String updatedByName;
	
	public EppPerson(){
		
	}

	
	public EppPerson(Long personId, String personCode, String orgPerson,
			String refId, String name, String otherName, String searchName,
			String gender, String dateOfBirth, String placeOfBirthCode,
			String placeOfBirthName, String idNumber, String dateOfIdIssue,
			String placeOfIdIssueName, String ethnic, String religion,
			String ethnicCode, String religionCode, String nationalityName,
			String nationalityCode, String fatherName, String fatherSearchName,
			String motherName, String motherSearchName, String countryOfBirth,
			String createdBy, Date createTs, String updatedBy, Date updateTs,
			Boolean isChecked, String description, String srcOffice,
			String srcDoc, String createdByName, String updatedByName) {
		super();
		this.personId = personId;
		this.personCode = personCode;
		this.orgPerson = orgPerson;
		this.refId = refId;
		this.name = name;
		this.otherName = otherName;
		this.searchName = searchName;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.placeOfBirthCode = placeOfBirthCode;
		this.placeOfBirthName = placeOfBirthName;
		this.idNumber = idNumber;
		this.dateOfIdIssue = dateOfIdIssue;
		this.placeOfIdIssueName = placeOfIdIssueName;
		this.ethnic = ethnic;
		this.religion = religion;
		this.ethnicCode = ethnicCode;
		this.religionCode = religionCode;
		this.nationalityName = nationalityName;
		this.nationalityCode = nationalityCode;
		this.fatherName = fatherName;
		this.fatherSearchName = fatherSearchName;
		this.motherName = motherName;
		this.motherSearchName = motherSearchName;
		this.countryOfBirth = countryOfBirth;
		this.createdBy = createdBy;
		this.createTs = createTs;
		this.updatedBy = updatedBy;
		this.updateTs = updateTs;
		this.isChecked = isChecked;
		this.description = description;
		this.srcOffice = srcOffice;
		this.srcDoc = srcDoc;
		this.createdByName = createdByName;
		this.updatedByName = updatedByName;
	}




	public Long getPersonId() {
		return personId;
	}

	public void setPersonId(Long personId) {
		this.personId = personId;
	}

	public String getPersonCode() {
		return personCode;
	}

	public void setPersonCode(String personCode) {
		this.personCode = personCode;
	}

	public String getOrgPerson() {
		return orgPerson;
	}

	public void setOrgPerson(String orgPerson) {
		this.orgPerson = orgPerson;
	}

	public String getRefId() {
		return refId;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOtherName() {
		return otherName;
	}

	public void setOtherName(String otherName) {
		this.otherName = otherName;
	}

	public String getSearchName() {
		return searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getPlaceOfBirthCode() {
		return placeOfBirthCode;
	}

	public void setPlaceOfBirthCode(String placeOfBirthCode) {
		this.placeOfBirthCode = placeOfBirthCode;
	}

	public String getPlaceOfBirthName() {
		return placeOfBirthName;
	}

	public void setPlaceOfBirthName(String placeOfBirthName) {
		this.placeOfBirthName = placeOfBirthName;
	}

	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	

	public String getDateOfIdIssue() {
		return dateOfIdIssue;
	}

	public void setDateOfIdIssue(String dateOfIdIssue) {
		this.dateOfIdIssue = dateOfIdIssue;
	}

	public String getPlaceOfIdIssueName() {
		return placeOfIdIssueName;
	}

	public void setPlaceOfIdIssueName(String placeOfIdIssueName) {
		this.placeOfIdIssueName = placeOfIdIssueName;
	}

	public String getEthnic() {
		return ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

	public String getReligion() {
		return religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getEthnicCode() {
		return ethnicCode;
	}

	public void setEthnicCode(String ethnicCode) {
		this.ethnicCode = ethnicCode;
	}

	public String getReligionCode() {
		return religionCode;
	}

	public void setReligionCode(String religionCode) {
		this.religionCode = religionCode;
	}

	public String getNationalityName() {
		return nationalityName;
	}

	public void setNationalityName(String nationalityName) {
		this.nationalityName = nationalityName;
	}

	public String getNationalityCode() {
		return nationalityCode;
	}

	public void setNationalityCode(String nationalityCode) {
		this.nationalityCode = nationalityCode;
	}

	public String getFatherName() {
		return fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getFatherSearchName() {
		return fatherSearchName;
	}

	public void setFatherSearchName(String fatherSearchName) {
		this.fatherSearchName = fatherSearchName;
	}

	public String getMotherName() {
		return motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getMotherSearchName() {
		return motherSearchName;
	}

	public void setMotherSearchName(String motherSearchName) {
		this.motherSearchName = motherSearchName;
	}

	public String getCountryOfBirth() {
		return countryOfBirth;
	}

	public void setCountryOfBirth(String countryOfBirth) {
		this.countryOfBirth = countryOfBirth;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateTs() {
		return createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdateTs() {
		return updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public Boolean getIsChecked() {
		return isChecked;
	}

	public void setIsChecked(Boolean isChecked) {
		this.isChecked = isChecked;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSrcOffice() {
		return srcOffice;
	}

	public void setSrcOffice(String srcOffice) {
		this.srcOffice = srcOffice;
	}

	public String getSrcDoc() {
		return srcDoc;
	}

	public void setSrcDoc(String srcDoc) {
		this.srcDoc = srcDoc;
	}


	public String getCreatedByName() {
		return createdByName;
	}


	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}


	public String getUpdatedByName() {
		return updatedByName;
	}


	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}
	
	
	
}
