package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * NicDecisionManager generated by hbm2java
 */
public class LogJobSchedule implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private Long recordId;
    private String code;
	private String guid;
	private String hrefJob;
	private Date createDate;
	private Date modifyDate;
	private String description;
	private String typeLogJob;
	private String typeTransaction;
	private String status;
	
	public LogJobSchedule() {
	}

	public LogJobSchedule(Long id, Long recordId, String code, String guid,
			String hrefJob, Date createDate, Date modifyDate,
			String description, String typeLogJob, String typeTransaction, String status) {
		super();
		this.id = id;
		this.recordId = recordId;
		this.code = code;
		this.guid = guid;
		this.hrefJob = hrefJob;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.description = description;
		this.typeLogJob = typeLogJob;
		this.typeTransaction = typeTransaction;
		this.status = status;
	}

	
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTypeTransaction() {
		return typeTransaction;
	}

	public void setTypeTransaction(String typeTransaction) {
		this.typeTransaction = typeTransaction;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRecordId() {
		return recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getHrefJob() {
		return hrefJob;
	}

	public void setHrefJob(String hrefJob) {
		this.hrefJob = hrefJob;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTypeLogJob() {
		return typeLogJob;
	}

	public void setTypeLogJob(String typeLogJob) {
		this.typeLogJob = typeLogJob;
	}

	

	
}
