package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicAfisData generated by hbm2java
 */
public class NicAfisData implements java.io.Serializable {

	public static final String STATUS_INSERTED       = "I";
	public static final String STATUS_DELETED        = "D";
	public static final String STATUS_ARCHIVED       = "A";
    private String transactionId;

    private String afisKeyNo;

    private Long afisRefId;

    private String status;

    private Date createDatetime;

    private Date updateDatetime;

    public NicAfisData() {
    }

    public NicAfisData(String transactionId) {
        this.transactionId = transactionId;
    }

    public NicAfisData(String transactionId, String afisKeyNo, Long afisRefId, String status, Date createDatetime, Date updateDatetime) {
        this.transactionId = transactionId;
        this.afisKeyNo = afisKeyNo;
        this.afisRefId = afisRefId;
        this.status = status;
        this.createDatetime = createDatetime;
        this.updateDatetime = updateDatetime;
    }

    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getAfisKeyNo() {
        return this.afisKeyNo;
    }

    public void setAfisKeyNo(String afisKeyNo) {
        this.afisKeyNo = afisKeyNo;
    }

    public Long getAfisRefId() {
        return this.afisRefId;
    }

    public void setAfisRefId(Long afisRefId) {
        this.afisRefId = afisRefId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreateDatetime() {
        return this.createDatetime;
    }

    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }

    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

}
