package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicApprovalData generated by hbm2java
 */
@Deprecated
public class NicApprovalData implements java.io.Serializable {

    private Long workflowJobId;

    private String transactionId;

    private String approveBy;

    private Date approveDatetime;

    private String approveReason;

    private String approveRemarks;

    public NicApprovalData() {
    }

    public NicApprovalData(Long workflowJobId) {
        this.workflowJobId = workflowJobId;
    }

    public NicApprovalData(Long workflowJobId, String transactionId, String approveBy, Date approveDatetime, String approveReason, String approveRemarks) {
        this.workflowJobId = workflowJobId;
        this.transactionId = transactionId;
        this.approveBy = approveBy;
        this.approveDatetime = approveDatetime;
        this.approveReason = approveReason;
        this.approveRemarks = approveRemarks;
    }

    public Long getWorkflowJobId() {
        return this.workflowJobId;
    }

    public void setWorkflowJobId(Long workflowJobId) {
        this.workflowJobId = workflowJobId;
    }

    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getApproveBy() {
        return this.approveBy;
    }

    public void setApproveBy(String approveBy) {
        this.approveBy = approveBy;
    }

    public Date getApproveDatetime() {
        return this.approveDatetime;
    }

    public void setApproveDatetime(Date approveDatetime) {
        this.approveDatetime = approveDatetime;
    }

    public String getApproveReason() {
        return this.approveReason;
    }

    public void setApproveReason(String approveReason) {
        this.approveReason = approveReason;
    }

    public String getApproveRemarks() {
        return this.approveRemarks;
    }

    public void setApproveRemarks(String approveRemarks) {
        this.approveRemarks = approveRemarks;
    }

}
