package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicDecisionManager generated by hbm2java
 */
public class NicBusinessList implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private long id;
    private String decisionNumber;
	private int serial;
	private String fullname;
	private String gender;
	private Date dob;
	private String pob;
	private String address;
	private String agency;
	private String position;
	private String positionEng;
	private String addressAgency;
	private String phone;
	private String type;
	private String rank;
	private String curb;
	private String jaw;
	private Date createDate;
	private String createBy;
	private String modifyBy;
	private Date modifyDate;
	private String description;
	private String dateF;
	
	public NicBusinessList() {
	}

	public NicBusinessList(long id) {
		this.id = id;
	}

	public NicBusinessList(long id,
			String decisionNumber, int serial, String fullname, String gender,
			Date dob, String pob, String address, String agency,
			String position, String positionEng, String addressAgency,
			String phone, String type, String rank, String curb, String jaw,
			Date createDate, String modifyBy, Date modifyDate,
			String description, String createBy, String dateF) {
		super();
		this.id = id;
		this.decisionNumber = decisionNumber;
		this.serial = serial;
		this.fullname = fullname;
		this.gender = gender;
		this.dob = dob;
		this.pob = pob;
		this.address = address;
		this.agency = agency;
		this.position = position;
		this.positionEng = positionEng;
		this.addressAgency = addressAgency;
		this.phone = phone;
		this.type = type;
		this.rank = rank;
		this.curb = curb;
		this.jaw = jaw;
		this.createDate = createDate;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.description = description;
		this.createBy = createBy;
		this.dateF = dateF;
	}

	public String getDateF() {
		return dateF;
	}

	public void setDateF(String dateF) {
		this.dateF = dateF;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDecisionNumber() {
		return decisionNumber;
	}

	public void setDecisionNumber(String decisionNumber) {
		this.decisionNumber = decisionNumber;
	}

	public int getSerial() {
		return serial;
	}

	public void setSerial(int serial) {
		this.serial = serial;
	}

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getPob() {
		return pob;
	}

	public void setPob(String pob) {
		this.pob = pob;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAgency() {
		return agency;
	}

	public void setAgency(String agency) {
		this.agency = agency;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getPositionEng() {
		return positionEng;
	}

	public void setPositionEng(String positionEng) {
		this.positionEng = positionEng;
	}

	public String getAddressAgency() {
		return addressAgency;
	}

	public void setAddressAgency(String addressAgency) {
		this.addressAgency = addressAgency;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRank() {
		return rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	public String getCurb() {
		return curb;
	}

	public void setCurb(String curb) {
		this.curb = curb;
	}

	public String getJaw() {
		return jaw;
	}

	public void setJaw(String jaw) {
		this.jaw = jaw;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModifyBy() {
		return modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
