package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicDocumentHistory generated by hbm2java
 */
public class NicDocumentHistory implements java.io.Serializable {

    private Long statusLogId;

    private String passportNo;

    private String siteCode;

    private String status;

    private String statusUpdateBy;

    private Date statusUpdateTime;

    public NicDocumentHistory() {
    }

    public NicDocumentHistory(Long statusLogId, String passportNo, String status) {
        this.statusLogId = statusLogId;
        this.passportNo = passportNo;
        this.status = status;
    }

	public NicDocumentHistory(Long statusLogId, String passportNo, String siteCode, String status,
			String statusUpdateBy, Date statusUpdateTime) {
		this.statusLogId = statusLogId;
		this.passportNo = passportNo;
		this.siteCode = siteCode;
		this.status = status;
		this.statusUpdateBy = statusUpdateBy;
		this.statusUpdateTime = statusUpdateTime;
	}

    public Long getStatusLogId() {
        return this.statusLogId;
    }

    public void setStatusLogId(Long statusLogId) {
        this.statusLogId = statusLogId;
    }

    public String getPassportNo() {
        return this.passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    public String getSiteCode() {
        return this.siteCode;
    }

    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatusUpdateBy() {
        return this.statusUpdateBy;
    }

    public void setStatusUpdateBy(String statusUpdateBy) {
        this.statusUpdateBy = statusUpdateBy;
    }

    public Date getStatusUpdateTime() {
        return this.statusUpdateTime;
    }

    public void setStatusUpdateTime(Date statusUpdateTime) {
        this.statusUpdateTime = statusUpdateTime;
    }

}
