package com.nec.asia.nic.comp.trans.domain;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.util.Date;

/**
 * NicJobAfisCheckResult generated by hbm2java
 */
@Deprecated
public class NicJobAfisCheckResult implements java.io.Serializable {

	private long uploadJobId;
	private NicUploadJob nicUploadJob;
	private Long searchResultId;
	private Date afisCheckTime;
	private String afisDecision; /* A:APPROVED R:REJECTED */
	private String afisDecisionOfficerId;
	private String afisDecisionWkstnId;
	private Date afisDecisionTime;
	private String createBy;
	private String createWkstnId;
	private Date createDate;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDate;

	public NicJobAfisCheckResult() {
	}

	public NicJobAfisCheckResult(NicUploadJob nicUploadJob) {
		this.nicUploadJob = nicUploadJob;
	}

	public long getUploadJobId() {
		return this.uploadJobId;
	}

	public void setUploadJobId(long uploadJobId) {
		this.uploadJobId = uploadJobId;
	}

	public NicUploadJob getNicUploadJob() {
		return this.nicUploadJob;
	}

	public void setNicUploadJob(NicUploadJob nicUploadJob) {
		this.nicUploadJob = nicUploadJob;
	}

	

	public Long getSearchResultId() {
		return this.searchResultId;
	}

	public void setSearchResultId(Long searchResultId) {
		this.searchResultId = searchResultId;
	}

	public Date getAfisCheckTime() {
		return this.afisCheckTime;
	}

	public void setAfisCheckTime(Date afisCheckTime) {
		this.afisCheckTime = afisCheckTime;
	}

	public String getAfisDecision() {
		return this.afisDecision;
	}

	public void setAfisDecision(String afisDecision) {
		this.afisDecision = afisDecision;
	}

	public String getAfisDecisionOfficerId() {
		return this.afisDecisionOfficerId;
	}

	public void setAfisDecisionOfficerId(String afisDecisionOfficerId) {
		this.afisDecisionOfficerId = afisDecisionOfficerId;
	}

	public String getAfisDecisionWkstnId() {
		return this.afisDecisionWkstnId;
	}

	public void setAfisDecisionWkstnId(String afisDecisionWkstnId) {
		this.afisDecisionWkstnId = afisDecisionWkstnId;
	}

	public Date getAfisDecisionTime() {
		return this.afisDecisionTime;
	}

	public void setAfisDecisionTime(Date afisDecisionTime) {
		this.afisDecisionTime = afisDecisionTime;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
