package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicDecisionManager generated by hbm2java
 */
public class NicOfficalNation implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private String decisionNumber;
    private String officalNationNo;
    private Long businessID;
    /*
     *  - REGISTRATION: Khởi tạo/ lưu tạm
		- VERIFY: Xác nhận
		- RECIVED: Đã nhận
		- PROCESSING: Chờ xử lý (Giai đoạn lấy thị thực)
		- REFUSE: Từ chối từ đại sứ quán
		- REFUSE_CLS: Từ chối từ cục lãnh sự
		- NATION_VISA: Không cần cấp do đã có miễn thị thực Quốc gia
     * */
	private String status;
	private String passportNo;
	private String passportType;
	private String visaNo;
	private String nationCode;
	private Date createDate;
	private String createBy;
	private String modifyBy;
	private Date modifyDate;
	private String description;
	private String fullname;
	private String statusS;
	private Date passportIss;
	private String passportIssuePlace;
	private Date passportExp;
	
	public NicOfficalNation() {
		
	}
	
	public NicOfficalNation(Long id) {
		this.id = id;
	}
	
	public NicOfficalNation(Long id, String decisionNumber,
			String officalNationNo, String status,
			String passportNo, String passportType, String visaNo,
			String nationCode, Date createDate, String createBy,
			String modifyBy, Date modifyDate, String description, Long businessID, String fullname, String statusS,
			Date passportIss, String passportIssuePlace, Date passportExp) {
		super();
		this.id = id;
		this.decisionNumber = decisionNumber;
		this.officalNationNo = officalNationNo;
		this.status = status;
		this.passportNo = passportNo;
		this.passportType = passportType;
		this.visaNo = visaNo;
		this.nationCode = nationCode;
		this.createDate = createDate;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.description = description;
		this.businessID = businessID;
		this.fullname = fullname;
		this.statusS = statusS;
		this.passportIss = passportIss;
		this.passportExp = passportExp;
		this.passportIssuePlace = passportIssuePlace;
	}

	
	
	public Date getPassportIss() {
		return passportIss;
	}

	public void setPassportIss(Date passportIss) {
		this.passportIss = passportIss;
	}

	public String getPassportIssuePlace() {
		return passportIssuePlace;
	}

	public void setPassportIssuePlace(String passportIssuePlace) {
		this.passportIssuePlace = passportIssuePlace;
	}

	public Date getPassportExp() {
		return passportExp;
	}

	public void setPassportExp(Date passportExp) {
		this.passportExp = passportExp;
	}

	public String getStatusS() {
		return statusS;
	}

	public void setStatusS(String statusS) {
		this.statusS = statusS;
	}

	public String getFullname() {
		return fullname;
	}


	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getBusinessID() {
		return businessID;
	}

	public void setBusinessID(Long businessID) {
		this.businessID = businessID;
	}

	
	public String getDecisionNumber() {
		return decisionNumber;
	}


	public void setDecisionNumber(String decisionNumber) {
		this.decisionNumber = decisionNumber;
	}


	public String getOfficalNationNo() {
		return officalNationNo;
	}


	public void setOfficalNationNo(String officalNationNo) {
		this.officalNationNo = officalNationNo;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getPassportNo() {
		return passportNo;
	}


	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}


	public String getPassportType() {
		return passportType;
	}


	public void setPassportType(String passportType) {
		this.passportType = passportType;
	}


	public String getVisaNo() {
		return visaNo;
	}


	public void setVisaNo(String visaNo) {
		this.visaNo = visaNo;
	}


	public String getNationCode() {
		return nationCode;
	}


	public void setNationCode(String nationCode) {
		this.nationCode = nationCode;
	}


	public Date getCreateDate() {
		return createDate;
	}


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public String getCreateBy() {
		return createBy;
	}


	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}


	public String getModifyBy() {
		return modifyBy;
	}


	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}


	public Date getModifyDate() {
		return modifyDate;
	}


	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}
	
	
}
