package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicDecisionManager generated by hbm2java
 */
public class NicOfficalVisa implements java.io.Serializable {

	/**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
    private String countryCode;
    private String passportType;
    private String description;
	private int freeday; 
	private Date validFrom;
	private Date validTo;
	private int status;
	private int type;
	private int passportExpiredday;
	private int stayday;
	private int maxLastemmiday;
	private String createBy;
	private Date createDate;
	private String lastModifiedBy;
	private Date lastModifiedTime;
	private String statusS;
	private String typeS;
	
	public NicOfficalVisa() {
		
	}
	
	public NicOfficalVisa(Long id) {
		this.id = id;
	}

	public NicOfficalVisa(Long id, String countryCode, String passportType,
			String description, int freeday, Date validFrom, Date validTo,
			int status, int type, int passportExpiredday, int stayday,
			int maxLastemmiday, String createBy, Date createDate,
			String lastModifiedBy, Date lastModifiedTime) {
		super();
		this.id = id;
		this.countryCode = countryCode;
		this.passportType = passportType;
		this.description = description;
		this.freeday = freeday;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.status = status;
		this.type = type;
		this.passportExpiredday = passportExpiredday;
		this.stayday = stayday;
		this.maxLastemmiday = maxLastemmiday;
		this.createBy = createBy;
		this.createDate = createDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedTime = lastModifiedTime;
	}
	
	
    public String getTypeS() {
		return typeS;
	}

	public void setTypeS(String typeS) {
		this.typeS = typeS;
	}

	public String getStatusS() {
		return statusS;
	}

	public void setStatusS(String statusS) {
		this.statusS = statusS;
	}


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getPassportType() {
		return passportType;
	}

	public void setPassportType(String passportType) {
		this.passportType = passportType;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getFreeday() {
		return freeday;
	}

	public void setFreeday(int freeday) {
		this.freeday = freeday;
	}

	public Date getValidFrom() {
		return validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getPassportExpiredday() {
		return passportExpiredday;
	}

	public void setPassportExpiredday(int passportExpiredday) {
		this.passportExpiredday = passportExpiredday;
	}

	public int getStayday() {
		return stayday;
	}

	public void setStayday(int stayday) {
		this.stayday = stayday;
	}

	public int getMaxLastemmiday() {
		return maxLastemmiday;
	}

	public void setMaxLastemmiday(int maxLastemmiday) {
		this.maxLastemmiday = maxLastemmiday;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getLastModifiedBy() {
		return lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedTime() {
		return lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}
	
}
