package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * NicTransactionAttachment generated by hbm2java
 */
/* 
 * Modification History:
 * 
 * 05 Jan 2016 (chris): add TPL constant. 
 * 15 Jan 2016 (chris): add STORAGE_TYPE constants.
 */
public class NicTransactionAttachment implements java.io.Serializable {

	private static final long serialVersionUID = -654770394172631328L;
	//Prefix
		public final static String DOC_TYPE_PREFIX_PHOTO 		= "PH";
		public final static String DOC_TYPE_PREFIX_THUMBNAIL 	= "TH";
		public final static String DOC_TYPE_PREFIX_SCANNEDDOC 	= "SC";
		public final static String DOC_TYPE_PREFIX_SIGN 		= "SIGN";
		public final static String DOC_TYPE_FINGERPRINT 		= "FP";
		public final static String DOC_TYPE_MINUTIA 			= "MNU";
		public final static String DOC_TYPE_MINUTIA_CBEFF		= "MNU_CBEFF";
		
		public final static String DOC_TYPE_TPL					= "TPL";
		public final static String DOC_TYPE_ENCODING 			= "ENCODING";
		public final static String DOC_TYPE_PERSO 				= "PERSO";
		public final static String DOC_TYPE_SIGNATURE 			= "SIGNATURE";
		public final static String DOC_TYPE_SIGN_FP 			= "SIGN_FP";
		public final static String DOC_TYPE_USER_DECLARATION 	= "SC_USER_DECL";
		//SubTypes
		public final static String DOC_TYPE_PHOTO_CAPTURE 		= "PH_CAP";
		public static final String DOC_TYPE_ENROLLED_SUB = "PH_TE";
		public final static String DOC_TYPE_THUMBNAIL_CAPTURE 	= "TH_CAP";
		public final static String DOC_TYPE_PHOTO_GREY	 		= "PH_GREY";
		public final static String DOC_TYPE_THUMBNAIL_GREY 		= "TH_GREY";
		public final static String DOC_TYPE_PHOTO_CHIP 			= "PH_CHIP";
		public final static String DOC_TYPE_THUMBNAIL_CHIP 		= "TH_CHIP";
		public final static String DOC_TYPE_PHOTO_CLI 			= "PH_CLI";
		//Scanned Document
		public final static String DOC_TYPE_SC_BIRTH_CERT		= "SC_BIRTH_CERT";
		public final static String DOC_TYPE_SC_MAR_CERT 		= "SC_MAR_CERT";
		public final static String DOC_TYPE_SC_ADDR_PROOF		= "SC_ADDR_PROOF_DOC";

		public final static String DOC_TYPE_EPP_BIRTH_CERT		    = "BC";
		public final static String DOC_TYPE_EPP_MAR_CERT 		    = "MC";
		public final static String DOC_TYPE_EPP_IDENTIFICATION		= "ID";
		public final static String DOC_TYPE_EPP_AFFIDAVIT_OF_LOSS   = "AFF";
		public final static String DOC_TYPE_EPP_APPLICATION_FORM    = "AF";
		public final static String DOC_TYPE_EPP_National_Bureau_of_Investigation = "NBI";
		public final static String DOC_TYPE_EPP_Photocopy_of_Old_passport        = "OPPT";
		public final static String DOC_TYPE_EPP_Other_Type_of_Document           = "OTH";
		public final static String DOC_TYPE_EPP_Enrollment_Confirmation          = "EC";
		public final static String DOC_TYPE_EPP_Travel_Document                  = "TD";
		//Reference Document
		public final static String DOC_TYPE_REF_COL_SLIP		= "REF_COL_SLIP";
		public final static String DOC_TYPE_REF_TXN_ID			= "REF_TXN_ID";
		
		public static final String DEFAULT_SERIAL_NO	 = "01";
		public static final String DEFAULT_SERIAL_NO_A	 = "1";
		public static final Short  TPL_POSITION			 = 99;
		public static final String TPL_SERIAL_NO		 = "99";//TPL_POSITION.toString();
		
		public static final String STORAGE_TYPE_ONLINE		= "O";
		public static final String STORAGE_TYPE_REFERENCE	= "R";
		public static final String KEY_SC_DSIGNER	= "SC_DSIGNER"; //Tờ khai
		public static final String KEY_SC_NBERNIN	= "SC_NBERNIN"; //CMND
		public static final String KEY_SC_PASPORT	= "SC_PASPORT"; //Hộ chiếu
		public static final String KEY_SCAN_DOCUMENT = "SCAN_DOCUMENT";
	
	private Long transactionDocId;
	//private NicTransaction nicTransaction;
	private String transactionId;
	private String docType;
	private String serialNo;
	private byte[] docData;
	private String storageRefId;
	private String storageType;
	private String remarks;
	private String createBy;
	private String createWkstnId;
	private Date createDatetime;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDatetime;
	
	private String createByName;
	private String updateByName;

	public NicTransactionAttachment() {
	}

	public NicTransactionAttachment(Long transactionDocId, String docType) {
		this.transactionDocId = transactionDocId;
		this.docType = docType;
	}

	public NicTransactionAttachment(Long transactionDocId,
			String transactionId, String docType, String serialNo,
			byte[] docData, String storageRefId, String storageType,
			String remarks, String createBy, String createWkstnId,
			Date createDatetime, String updateBy, String updateWkstnId,
			Date updateDatetime, String createByName, String updateByName) {
		super();
		this.transactionDocId = transactionDocId;
		this.transactionId = transactionId;
		this.docType = docType;
		this.serialNo = serialNo;
		this.docData = docData;
		this.storageRefId = storageRefId;
		this.storageType = storageType;
		this.remarks = remarks;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDatetime = createDatetime;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDatetime = updateDatetime;
		this.createByName = createByName;
		this.updateByName = updateByName;
	}

	public Long getTransactionDocId() {
		return transactionDocId;
	}

	public void setTransactionDocId(Long transactionDocId) {
		this.transactionDocId = transactionDocId;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getDocType() {
		return docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public String getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public byte[] getDocData() {
		return docData;
	}

	public void setDocData(byte[] docData) {
		this.docData = docData;
	}

	public String getStorageRefId() {
		return storageRefId;
	}

	public void setStorageRefId(String storageRefId) {
		this.storageRefId = storageRefId;
	}

	public String getStorageType() {
		return storageType;
	}

	public void setStorageType(String storageType) {
		this.storageType = storageType;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDatetime() {
		return createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public String getCreateByName() {
		return createByName;
	}

	public void setCreateByName(String createByName) {
		this.createByName = createByName;
	}

	public String getUpdateByName() {
		return updateByName;
	}

	public void setUpdateByName(String updateByName) {
		this.updateByName = updateByName;
	}


}
