package com.nec.asia.nic.comp.trans.domain;

// Generated May 16, 2013 7:03:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/*
 * Modification History:
 * 
 * 29 Dec 2015 (Chris): refactor with EPP_WORKLOW_JOB
 * 19 Jan 2016 (Chris): add constant RECORD_STATUS_SUSPENDED
 */

/**
 * NicUploadJob generated by hbm2java
 */
public class NicUploadJob implements java.io.Serializable {

	private static final long serialVersionUID = 26339297685802833L;

	public static final String RECORD_STATUS_NOT_REQUIRED = "-1";
	public static final String RECORD_STATUS_INITIAL = "00";
	public static final String RECORD_STATUS_IN_PROGRESS = "01";
	public static final String RECORD_STATUS_COMPLETED = "02"; // TRẠNG THÁI DUYỆT CHO PHÉP Ở DANH SÁCH ĐIỀU TRA
	public static final String RECORD_STATUS_APPROVED = "02";
	public static final String RECORD_STATUS_COMPLETED_WITH_HIT = "03";
	public static final String RECORD_STATUS_REJECTED = "04"; // TẤT CẢ CÁC LỆNH TỪ CHỐI BẢN GHI ĐỀU Ở TRẠNG THÁI  NÀY
	public static final String RECORD_STATUS_CANCELLED = "05"; 
	public static final String RECORD_STATUS_CONFIRMED = "30"; // TRUNG THÊM TRẠNG THÁI DUYỆT DANH SÁCH SƠ BỘ
	public static final String RECORD_STATUS_CONFIRMED_DSQ = "70"; // TRUNG THÊM TRẠNG THÁI DUYỆT DANH SÁCH HỒ SƠ YÊU CẦU XÁC MINH TỪ CƠ QUAN ĐẠI DIỆN
	public static final String RECORD_STATUS_PENDING_BCA = "33"; // TRUNG THÊM TRẠNG THÁI CHỜ XÁC THỰC DỮ LIỆU TỪ BỘ CÔNG AN
	public static final String RECORD_STATUS_CONFIRMED_BCA = "34"; // TRUNG THÊM TRẠNG THÁI NHẬN XÁC THỰC DỮ LIỆU TỪ BỘ  CÔNG AN
	public static final String RECORD_STATUS_PENDING_BOSS = "35"; // TRUNG THÊM TRẠNG THÁI CHỜ XÉT DUYỆT
	public static final String RECORD_STATUS_APPROVE_BOSS = "36"; // TRUNG THÊM TRẠNG THÁI ĐÃ XÉT DUYỆT
	public static final String RECORD_STATUS_APPROVE_PERSO = "40"; // TRUNG THÊM TRẠNG THÁI DUYỆT IN
	public static final String RECORD_STATUS_SUSPENDED = "06";
	public static final String RECORD_STATUS_ERROR = "09";

	public static final String INVESTIGATION_TYPE_CPD = "CPD";
	public static final String INVESTIGATION_TYPE_AFIS = "AFIS";
	public static final String INVESTIGATION_TYPE_PERSO = "PERSO";

	public static final String JOB_STATE_INIT = "INITIALIZE";
	// transaction
	public static final String JOB_STATE_CPD_CHECK = "CPD_CHECK";
	public static final String JOB_STATE_AFIS_REGISTER = "AFIS_REGISTER";
	public static final String JOB_STATE_AFIS_CHECK = "AFIS_CHECK";
	public static final String JOB_STATE_DEACTIVATE_CARD = "DEACTIVATE_CARD";// "NIC_OLD_CARD_DEACTIVATED";
	public static final String JOB_STATE_DATA_PREPARATION = "DATA_PREPARATION";
	public static final String JOB_STATE_PERSO_REGISTER = "PERSO_REGISTER";
	public static final String JOB_STATE_UPD_MAIN_AND_HISTORY = "UPD_MAIN_AND_HISTORY"; // update NIC
	public static final String JOB_STATE_SYNC_TX_CPD = "SYNC_TX_CPD";
	// transaction rejection
	public static final String JOB_STATE_AFIS_DELETE = "AFIS_DELETE";
	public static final String JOB_STATE_NIC_REJECTION = "NIC_REJECTION";
	// card
	public static final String JOB_STATE_SYNC_CARD_CPD = "SYNC_CARD_CPD";
	public static final String JOB_STATE_INVENTORY_SYNC = "INVENTORY_SYNC";
	// transaction void
	public static final String JOB_STATE_VOID = "VOID";

	public static final Integer JOB_PRIORITY_NORMAL = 1;
	public static final Integer JOB_PRIORITY_EXPRESS = 2;
	public static final Integer JOB_PRIORITY_IMMEDIATE = 3;

	public static final String JOB_CURRENT_STAGE_INVESTIGATION = "INVESTIGATION";

	public static final String JOB_CURRENT_STAGE_INVESTIGATION_PROCESSING = "INVESTIGATION_PROCESSING";

	public static final String JOB_STATUS_PERSO_PRINTED = "PERSO_PRINTED";

	private Long workflowJobId;
	private NicTransaction nicTransaction;
	private String transactionId;
	private String jobType;
	private Integer jobPriority;
	private Date jobCreatedTime;
	private String jobCurrentStage;
	private String jobCurrentStatus;
	private Date jobStartTime;
	private Date jobEndTime;
	private String cpdCheckStatus;
	private String afisRegisterStatus;
	private String afisCheckStatus;
	private String afisVerifyStatus;
	private String blacklistCheckStatus;
	private String identificationCheckStatus;
	private String investigationType;
	private String investigationStatus;
	private String investigationOfficerId;
	private String afisUpdateStatus;
	private String persoRegisterStatus;
	private Boolean jobCompletedFlag;
	private Integer jobReprocessCount;
	private String jobApproveStatus;
	///16-04 TRUNG them luu tam so ho chiếu nhập tay
	private String tempPassportNo;
	private String checkSigner;
	///11-12 Luu ma goi tin tu A08
	private String receiptNo;	
	///12-12 Check trang thai xac thuc thông tin tu bo cong an
	private Integer validateInfoBca;
//	private String originalyPersonCode;
	private Date dateApprovePerson;
	private String noteApprovePerson;
	private Long originalyBlacklistId;
	private Date dateApproveInvestigation;
	private String noteApproveObj;
	private Date dateApproveNin;
	private String noteApproveNin;
	private Date editTimeExpiry;
	private Integer workflowJobRunAgainCount;
	private String createBy;
	private String createWkstnId;
	private Date createDatetime;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDatetime;
	//Thoi gian luu ho so
	private Date investigationDate;
	//Cán bộ tra cứu đối tượng
	private String userApproverObj;
	
	public String getUserApproverObj() {
		return userApproverObj;
	}

	public void setUserApproverObj(String userApproverObj) {
		this.userApproverObj = userApproverObj;
	}

	private Set<NicSearchResult> nicSearchResults = new HashSet<NicSearchResult>(0);
	// private NicApprovalData nicApprovalData;
	private NicRejectionData nicRejectionData;
	
	/*private Date estDateOfCollection;
	private Integer priority;
	private Boolean jobErrorFlag;
	//phúc thêm thông tin phiếu bàn giao
	private String packageId;
	private Date datePackage;
	private String numberTran;
	private String ricName;
	private String originalyId;
	private String originalyPersonId;
	private String approveFlag;*/
	
	
	public NicUploadJob(){
		
	}
	

	public NicUploadJob(Long workflowJobId, NicTransaction nicTransaction,
			String transactionId, String jobType, Integer jobPriority,
			Date jobCreatedTime, String jobCurrentStage,
			String jobCurrentStatus, Date jobStartTime, Date jobEndTime,
			String cpdCheckStatus, String afisRegisterStatus,
			String afisCheckStatus, String afisVerifyStatus,
			String blacklistCheckStatus, String identificationCheckStatus,
			String investigationType, String investigationStatus,
			String investigationOfficerId, String afisUpdateStatus,
			String persoRegisterStatus, Boolean jobCompletedFlag,
			Integer jobReprocessCount, String jobApproveStatus,
			String tempPassportNo, String checkSigner, String receiptNo,
			Integer validateInfoBca, Date dateApprovePerson,
			String noteApprovePerson, Long originalyBlacklistId,
			Date dateApproveInvestigation, String noteApproveObj,
			Date dateApproveNin, String noteApproveNin, Date editTimeExpiry,
			Integer workflowJobRunAgainCount, String createBy,
			String createWkstnId, Date createDatetime, String updateBy,
			String updateWkstnId, Date updateDatetime, Date investigationDate,
			String userApproverObj, Set<NicSearchResult> nicSearchResults,
			NicRejectionData nicRejectionData) {
		super();
		this.workflowJobId = workflowJobId;
		this.nicTransaction = nicTransaction;
		this.transactionId = transactionId;
		this.jobType = jobType;
		this.jobPriority = jobPriority;
		this.jobCreatedTime = jobCreatedTime;
		this.jobCurrentStage = jobCurrentStage;
		this.jobCurrentStatus = jobCurrentStatus;
		this.jobStartTime = jobStartTime;
		this.jobEndTime = jobEndTime;
		this.cpdCheckStatus = cpdCheckStatus;
		this.afisRegisterStatus = afisRegisterStatus;
		this.afisCheckStatus = afisCheckStatus;
		this.afisVerifyStatus = afisVerifyStatus;
		this.blacklistCheckStatus = blacklistCheckStatus;
		this.identificationCheckStatus = identificationCheckStatus;
		this.investigationType = investigationType;
		this.investigationStatus = investigationStatus;
		this.investigationOfficerId = investigationOfficerId;
		this.afisUpdateStatus = afisUpdateStatus;
		this.persoRegisterStatus = persoRegisterStatus;
		this.jobCompletedFlag = jobCompletedFlag;
		this.jobReprocessCount = jobReprocessCount;
		this.jobApproveStatus = jobApproveStatus;
		this.tempPassportNo = tempPassportNo;
		this.checkSigner = checkSigner;
		this.receiptNo = receiptNo;
		this.validateInfoBca = validateInfoBca;
		this.dateApprovePerson = dateApprovePerson;
		this.noteApprovePerson = noteApprovePerson;
		this.originalyBlacklistId = originalyBlacklistId;
		this.dateApproveInvestigation = dateApproveInvestigation;
		this.noteApproveObj = noteApproveObj;
		this.dateApproveNin = dateApproveNin;
		this.noteApproveNin = noteApproveNin;
		this.editTimeExpiry = editTimeExpiry;
		this.workflowJobRunAgainCount = workflowJobRunAgainCount;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDatetime = createDatetime;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDatetime = updateDatetime;
		this.investigationDate = investigationDate;
		this.userApproverObj = userApproverObj;
		this.nicSearchResults = nicSearchResults;
		this.nicRejectionData = nicRejectionData;
	}

	public Long getWorkflowJobId() {
		return workflowJobId;
	}

	public void setWorkflowJobId(Long workflowJobId) {
		this.workflowJobId = workflowJobId;
	}

	public Date getInvestigationDate() {
		return investigationDate;
	}

	public void setInvestigationDate(Date investigationDate) {
		this.investigationDate = investigationDate;
	}

	public NicTransaction getNicTransaction() {
		return nicTransaction;
	}

	public void setNicTransaction(NicTransaction nicTransaction) {
		this.nicTransaction = nicTransaction;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getJobType() {
		return jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	public Integer getJobPriority() {
		return jobPriority;
	}

	public void setJobPriority(Integer jobPriority) {
		this.jobPriority = jobPriority;
	}

	public Date getJobCreatedTime() {
		return jobCreatedTime;
	}

	public void setJobCreatedTime(Date jobCreatedTime) {
		this.jobCreatedTime = jobCreatedTime;
	}

	public String getJobCurrentStage() {
		return jobCurrentStage;
	}

	public void setJobCurrentStage(String jobCurrentStage) {
		this.jobCurrentStage = jobCurrentStage;
	}

	public String getJobCurrentStatus() {
		return jobCurrentStatus;
	}

	public void setJobCurrentStatus(String jobCurrentStatus) {
		this.jobCurrentStatus = jobCurrentStatus;
	}

	public Date getJobStartTime() {
		return jobStartTime;
	}

	public void setJobStartTime(Date jobStartTime) {
		this.jobStartTime = jobStartTime;
	}

	public Date getJobEndTime() {
		return jobEndTime;
	}

	public void setJobEndTime(Date jobEndTime) {
		this.jobEndTime = jobEndTime;
	}

	public String getCpdCheckStatus() {
		return cpdCheckStatus;
	}

	public void setCpdCheckStatus(String cpdCheckStatus) {
		this.cpdCheckStatus = cpdCheckStatus;
	}

	public String getAfisRegisterStatus() {
		return afisRegisterStatus;
	}

	public void setAfisRegisterStatus(String afisRegisterStatus) {
		this.afisRegisterStatus = afisRegisterStatus;
	}

	public String getAfisCheckStatus() {
		return afisCheckStatus;
	}

	public void setAfisCheckStatus(String afisCheckStatus) {
		this.afisCheckStatus = afisCheckStatus;
	}

	public String getAfisVerifyStatus() {
		return afisVerifyStatus;
	}

	public void setAfisVerifyStatus(String afisVerifyStatus) {
		this.afisVerifyStatus = afisVerifyStatus;
	}

	public String getBlacklistCheckStatus() {
		return blacklistCheckStatus;
	}

	public void setBlacklistCheckStatus(String blacklistCheckStatus) {
		this.blacklistCheckStatus = blacklistCheckStatus;
	}

	public String getIdentificationCheckStatus() {
		return identificationCheckStatus;
	}

	public void setIdentificationCheckStatus(String identificationCheckStatus) {
		this.identificationCheckStatus = identificationCheckStatus;
	}

	public String getInvestigationType() {
		return investigationType;
	}

	public void setInvestigationType(String investigationType) {
		this.investigationType = investigationType;
	}

	public String getInvestigationStatus() {
		return investigationStatus;
	}

	public void setInvestigationStatus(String investigationStatus) {
		this.investigationStatus = investigationStatus;
	}

	public String getInvestigationOfficerId() {
		return investigationOfficerId;
	}

	public void setInvestigationOfficerId(String investigationOfficerId) {
		this.investigationOfficerId = investigationOfficerId;
	}

	public String getAfisUpdateStatus() {
		return afisUpdateStatus;
	}

	public void setAfisUpdateStatus(String afisUpdateStatus) {
		this.afisUpdateStatus = afisUpdateStatus;
	}

	public String getPersoRegisterStatus() {
		return persoRegisterStatus;
	}

	public void setPersoRegisterStatus(String persoRegisterStatus) {
		this.persoRegisterStatus = persoRegisterStatus;
	}

	public Boolean getJobCompletedFlag() {
		return jobCompletedFlag;
	}

	public void setJobCompletedFlag(Boolean jobCompletedFlag) {
		this.jobCompletedFlag = jobCompletedFlag;
	}

	public Integer getJobReprocessCount() {
		return jobReprocessCount;
	}

	public void setJobReprocessCount(Integer jobReprocessCount) {
		this.jobReprocessCount = jobReprocessCount;
	}

	public String getJobApproveStatus() {
		return jobApproveStatus;
	}

	public void setJobApproveStatus(String jobApproveStatus) {
		this.jobApproveStatus = jobApproveStatus;
	}

	public String getTempPassportNo() {
		return tempPassportNo;
	}

	public void setTempPassportNo(String tempPassportNo) {
		this.tempPassportNo = tempPassportNo;
	}

	public String getCheckSigner() {
		return checkSigner;
	}

	public void setCheckSigner(String checkSigner) {
		this.checkSigner = checkSigner;
	}

	public String getReceiptNo() {
		return receiptNo;
	}

	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo;
	}

	public Integer getValidateInfoBca() {
		return validateInfoBca;
	}

	public void setValidateInfoBca(Integer validateInfoBca) {
		this.validateInfoBca = validateInfoBca;
	}

	public Date getDateApprovePerson() {
		return dateApprovePerson;
	}

	public void setDateApprovePerson(Date dateApprovePerson) {
		this.dateApprovePerson = dateApprovePerson;
	}

	public String getNoteApprovePerson() {
		return noteApprovePerson;
	}

	public void setNoteApprovePerson(String noteApprovePerson) {
		this.noteApprovePerson = noteApprovePerson;
	}

	public Long getOriginalyBlacklistId() {
		return originalyBlacklistId;
	}

	public void setOriginalyBlacklistId(Long originalyBlacklistId) {
		this.originalyBlacklistId = originalyBlacklistId;
	}

	public Date getDateApproveInvestigation() {
		return dateApproveInvestigation;
	}

	public void setDateApproveInvestigation(Date dateApproveInvestigation) {
		this.dateApproveInvestigation = dateApproveInvestigation;
	}

	public String getNoteApproveObj() {
		return noteApproveObj;
	}

	public void setNoteApproveObj(String noteApproveObj) {
		this.noteApproveObj = noteApproveObj;
	}

	public Date getDateApproveNin() {
		return dateApproveNin;
	}

	public void setDateApproveNin(Date dateApproveNin) {
		this.dateApproveNin = dateApproveNin;
	}

	public String getNoteApproveNin() {
		return noteApproveNin;
	}

	public void setNoteApproveNin(String noteApproveNin) {
		this.noteApproveNin = noteApproveNin;
	}

	public Date getEditTimeExpiry() {
		return editTimeExpiry;
	}

	public void setEditTimeExpiry(Date editTimeExpiry) {
		this.editTimeExpiry = editTimeExpiry;
	}

	public Integer getWorkflowJobRunAgainCount() {
		return workflowJobRunAgainCount;
	}

	public void setWorkflowJobRunAgainCount(Integer workflowJobRunAgainCount) {
		this.workflowJobRunAgainCount = workflowJobRunAgainCount;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDatetime() {
		return createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public Set<NicSearchResult> getNicSearchResults() {
		return nicSearchResults;
	}

	public void setNicSearchResults(Set<NicSearchResult> nicSearchResults) {
		this.nicSearchResults = nicSearchResults;
	}

	public NicRejectionData getNicRejectionData() {
		return nicRejectionData;
	}

	public void setNicRejectionData(NicRejectionData nicRejectionData) {
		this.nicRejectionData = nicRejectionData;
	}

}
