package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicWorkflowJob generated by hbm2java
 */
public class NicWorkflowJob implements java.io.Serializable {

	private static final long serialVersionUID = -8750326960725040378L;
	
	private Long workflowJobId;
	private NicTransaction nicTransaction;
	private String transactionId;
	private String jobType;
	private Date jobCreatedTime;
	private String jobCurrentStage;
	private String jobCurrentStatus;
	private Date jobStartTime;
	private Date jobEndTime;
	private String cpdCheckStatus;
	private String afisRegisterStatus;
	private String afisCheckStatus;
	private String afisVerifyStatus;
	private String investigationType;
	private String investigationStatus;
	private String investigationOfficerId;
	private Date investigationStatusUpdateTime;
	private String afisUpdateStatus;
	private String persoRegisterStatus;
	private Boolean nicJobCompletedFlag;
	private String createBy;
	private String createWkstnId;
	private Date createDatetime;
	private String updateBy;
	private String updateWkstnId;
	private Date updateDatetime;
	private Integer jobReprocessCount;
	private Set<NicSearchResult> nicSearchResults = new HashSet<NicSearchResult>(0);
	//private NicApprovalData nicApprovalData;
	private NicRejectionData nicRejectionData;
	private String jobApproveStatus;
	///16-04 TRUNG them luu tam so ho chiếu nhập tay
	private String tempPassportNo;
	public NicWorkflowJob() {
	}

	public NicWorkflowJob(Long workflowJobId) {
		this.workflowJobId = workflowJobId;
	}

	public NicWorkflowJob(Long workflowJobId, NicTransaction nicTransaction, String jobType, Date jobCreatedTime,
			String jobCurrentStage, String jobCurrentStatus, Date jobStartTime, Date jobEndTime, String cpdCheckStatus,
			String afisRegisterStatus, String afisCheckStatus, String afisVerifyStatus, String investigationType,
			String investigationStatus, String investigationOfficerId, String afisUpdateStatus,
			String persoRegisterStatus, Boolean nicJobCompletedFlag, String createBy, String createWkstnId,
			Date createDatetime, String updateBy, String updateWkstnId, Date updateDatetime, Integer jobReprocessCount,
			Set<NicSearchResult> nicSearchResults) {
		this.workflowJobId = workflowJobId;
		this.nicTransaction = nicTransaction;
		this.jobType = jobType;
		this.jobCreatedTime = jobCreatedTime;
		this.jobCurrentStage = jobCurrentStage;
		this.jobCurrentStatus = jobCurrentStatus;
		this.jobStartTime = jobStartTime;
		this.jobEndTime = jobEndTime;
		this.cpdCheckStatus = cpdCheckStatus;
		this.afisRegisterStatus = afisRegisterStatus;
		this.afisCheckStatus = afisCheckStatus;
		this.afisVerifyStatus = afisVerifyStatus;
		this.investigationType = investigationType;
		this.investigationStatus = investigationStatus;
		this.investigationOfficerId = investigationOfficerId;
		this.afisUpdateStatus = afisUpdateStatus;
		this.persoRegisterStatus = persoRegisterStatus;
		this.nicJobCompletedFlag = nicJobCompletedFlag;
		this.createBy = createBy;
		this.createWkstnId = createWkstnId;
		this.createDatetime = createDatetime;
		this.updateBy = updateBy;
		this.updateWkstnId = updateWkstnId;
		this.updateDatetime = updateDatetime;
		this.jobReprocessCount = jobReprocessCount;
		this.nicSearchResults = nicSearchResults;
	}

	public Long getWorkflowJobId() {
		return this.workflowJobId;
	}

	public void setWorkflowJobId(Long workflowJobId) {
		this.workflowJobId = workflowJobId;
	}

	public NicTransaction getNicTransaction() {
		return this.nicTransaction;
	}

	public void setNicTransaction(NicTransaction nicTransaction) {
		this.nicTransaction = nicTransaction;
	}
	
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}
	
	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	public Date getJobCreatedTime() {
		return this.jobCreatedTime;
	}

	public void setJobCreatedTime(Date jobCreatedTime) {
		this.jobCreatedTime = jobCreatedTime;
	}

	public String getJobCurrentStage() {
		return this.jobCurrentStage;
	}

	public void setJobCurrentStage(String jobCurrentStage) {
		this.jobCurrentStage = jobCurrentStage;
	}

	public String getJobCurrentStatus() {
		return this.jobCurrentStatus;
	}

	public void setJobCurrentStatus(String jobCurrentStatus) {
		this.jobCurrentStatus = jobCurrentStatus;
	}

	public Date getJobStartTime() {
		return this.jobStartTime;
	}

	public void setJobStartTime(Date jobStartTime) {
		this.jobStartTime = jobStartTime;
	}

	public Date getJobEndTime() {
		return this.jobEndTime;
	}

	public void setJobEndTime(Date jobEndTime) {
		this.jobEndTime = jobEndTime;
	}

	public String getCpdCheckStatus() {
		return this.cpdCheckStatus;
	}

	public void setCpdCheckStatus(String cpdCheckStatus) {
		this.cpdCheckStatus = cpdCheckStatus;
	}

	public String getAfisRegisterStatus() {
		return this.afisRegisterStatus;
	}

	public void setAfisRegisterStatus(String afisRegisterStatus) {
		this.afisRegisterStatus = afisRegisterStatus;
	}

	public String getAfisCheckStatus() {
		return this.afisCheckStatus;
	}

	public void setAfisCheckStatus(String afisCheckStatus) {
		this.afisCheckStatus = afisCheckStatus;
	}

	public String getAfisVerifyStatus() {
		return this.afisVerifyStatus;
	}

	public void setAfisVerifyStatus(String afisVerifyStatus) {
		this.afisVerifyStatus = afisVerifyStatus;
	}

	public String getInvestigationType() {
		return this.investigationType;
	}

	public void setInvestigationType(String investigationType) {
		this.investigationType = investigationType;
	}

	public String getInvestigationStatus() {
		return this.investigationStatus;
	}

	public void setInvestigationStatus(String investigationStatus) {
		this.investigationStatus = investigationStatus;
	}

	public String getInvestigationOfficerId() {
		return this.investigationOfficerId;
	}

	public void setInvestigationOfficerId(String investigationOfficerId) {
		this.investigationOfficerId = investigationOfficerId;
	}
	
	public Date getInvestigationStatusUpdateTime() {
		return this.investigationStatusUpdateTime;
	}

	public void setInvestigationStatusUpdateTime(Date investigationStatusUpdateTime) {
		this.investigationStatusUpdateTime = investigationStatusUpdateTime;
	}

	public String getAfisUpdateStatus() {
		return this.afisUpdateStatus;
	}

	public void setAfisUpdateStatus(String afisUpdateStatus) {
		this.afisUpdateStatus = afisUpdateStatus;
	}

	public String getPersoRegisterStatus() {
		return this.persoRegisterStatus;
	}

	public void setPersoRegisterStatus(String persoRegisterStatus) {
		this.persoRegisterStatus = persoRegisterStatus;
	}

	public Boolean getNicJobCompletedFlag() {
		return this.nicJobCompletedFlag;
	}

	public void setNicJobCompletedFlag(Boolean nicJobCompletedFlag) {
		this.nicJobCompletedFlag = nicJobCompletedFlag;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateWkstnId() {
		return this.createWkstnId;
	}

	public void setCreateWkstnId(String createWkstnId) {
		this.createWkstnId = createWkstnId;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateWkstnId() {
		return this.updateWkstnId;
	}

	public void setUpdateWkstnId(String updateWkstnId) {
		this.updateWkstnId = updateWkstnId;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public Integer getJobReprocessCount() {
		return this.jobReprocessCount;
	}

	public void setJobReprocessCount(Integer jobReprocessCount) {
		this.jobReprocessCount = jobReprocessCount;
	}

	public Set<NicSearchResult> getNicSearchResults() {
		return this.nicSearchResults;
	}

	public void setNicSearchResults(Set<NicSearchResult> nicSearchResults) {
		this.nicSearchResults = nicSearchResults;
	}

	/*public NicApprovalData getNicApprovalData() {
		return this.nicApprovalData;
	}
	
	public void setNicApprovalData(NicApprovalData nicApprovalData) {
		this.nicApprovalData = nicApprovalData;
	}*/
	
	public NicRejectionData getNicRejectionData() {
		return this.nicRejectionData;
	}
	
	public void setNicRejectionData(NicRejectionData nicRejectionData) {
		this.nicRejectionData = nicRejectionData;
	}
	
	public String getJobApproveStatus() {
		return this.jobApproveStatus;
	}

	public void setJobApproveStatus(String jobApproveStatus) {
		this.jobApproveStatus = jobApproveStatus;
	}
	
	public String getTempPassportNo() {
		return this.tempPassportNo;
	}

	public void setTempPassportNo(String tempPassportNo) {
		this.tempPassportNo = tempPassportNo;
	}
}
