package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicWorkflowProcess generated by hbm2java
 */
public class NicWorkflowProcess implements java.io.Serializable {
	
	public static final String CHECK_CPD = "CHECK_CPD"; //Kiểm tra CPD
	public static final String CHECK_BMS = "CHECK_BMS"; //Kiểm tra vân tay
	public static final String ASSIGNMENT = "ASSIGNMENT"; //Cán bộ phân công
	public static final String INVESTIGATION = "INVESTIGATION"; //Điều tra
	public static final String INVESTIGATION_VERIFICATION = "INVESTIGATION_VERIFICATION"; //Điều tra yêu cầu xác minh
	public static final String INVESTIGATION_REJECT = "INVESTIGATION_REJECT"; //Điều tra từ chối
	public static final String PRESENT_APPROVAL = "PRESENT_APPROVAL"; //Kiểm duyệt sơ bộ
	public static final String PRESENT_APPROVAL_VERIFICATION = "PRESENT_APPROVAL_VERIFICATION"; //Kiểm duyệt sơ bộ - yêu cầu xác minh
	public static final String PRESENT_APPROVAL_REJECT = "PRESENT_APPROVAL_REJECT"; //Kiểm duyệt sơ bộ - từ chối
	public static final String LEADERS_APPROVAL = "LEADERS_APPROVAL"; //Lãnh đạo phê duyệt
	public static final String LEADERS_APPROVAL_REJECT = "LEADERS_APPROVAL_REJECT"; //Lãnh đạo phê duyệt - từ chối
	public static final String PERSO = "PERSO"; //Cá thể hóa
	public static final String UPLOADED = "UPLOADED"; //Ric Upload
	public static final String VERIFICATION = "VERIFICATION"; //Xác minh
	
	public static final String WORKFLOW_START_RESULT_YES = "YES"; 
	public static final String WORKFLOW_START_RESULT_NO = "NO"; 
	public static final String WORKFLOW_START_RESULT_VERIFICATION = "VER"; //Kiểm tra xử lý xác minh (Gọi đến key VERIFICATION)
    
	public static final int WORKFLOW_STATUS_OFF = 0; 
	public static final int WORKFLOW_STATUS_ON = 1; 
	/**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private long id;
    private String workflowStart;
	private String workflowEnd;
	private String workflowStartResult;
	private String transactionType;
	private String parameter;
	private int status;
	private Date createDate;
	private String createBy;
	private String updateBy;
	private Date updateDate;
	private String description;
	
	public NicWorkflowProcess() {
		
	}
	
	public NicWorkflowProcess(long id, String workflowStart,
			String workflowEnd, String workflowStartResult,
			String transactionType, String parameter, int status,
			Date createDate, String createBy, String updateBy, Date updateDate,
			String description) {
		super();
		this.id = id;
		this.workflowStart = workflowStart;
		this.workflowEnd = workflowEnd;
		this.workflowStartResult = workflowStartResult;
		this.transactionType = transactionType;
		this.parameter = parameter;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.description = description;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getWorkflowStart() {
		return workflowStart;
	}

	public void setWorkflowStart(String workflowStart) {
		this.workflowStart = workflowStart;
	}

	public String getWorkflowEnd() {
		return workflowEnd;
	}

	public void setWorkflowEnd(String workflowEnd) {
		this.workflowEnd = workflowEnd;
	}

	public String getWorkflowStartResult() {
		return workflowStartResult;
	}

	public void setWorkflowStartResult(String workflowStartResult) {
		this.workflowStartResult = workflowStartResult;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getParameter() {
		return parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	
}
