package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class PersonInformation implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L;
    
	private String name;
	private String gender;
	private String dateOfBirth;
	private PlaceData placeOfBirth;
	private String idNumber;
	private Date dateOfIdIssue;
	private OfficeData placeOfIdIssue;
	private String ethnic;
	private OfficeData religion;
	private CountryData nationality;
	private PersonInformation origin;
	
	private PlaceData residentPlace;
	private AreaData residentArea;
	private String residentAddress;
	private PlaceData tmpPlace;
	private AreaData tmpArea;
	private String  tmpAddress;
	private String  searchName;
	private String  occupation;
	private String  officeInfo;
	private String  type;
	
	
	public PersonInformation() {
	}

	public PersonInformation(String name, String gender, String dateOfBirth, PlaceData placeOfBirth,
			String idNumber, Date dateOfIdIssue, OfficeData placeOfIdIssue, String ethnic,
			OfficeData religion, CountryData nationality, PersonInformation origin, String residentAddress) {
		this.name = name;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.placeOfBirth = placeOfBirth;
		this.idNumber = idNumber;
		this.dateOfIdIssue = dateOfIdIssue;
		this.placeOfIdIssue = placeOfIdIssue;
		this.ethnic = ethnic;
		this.religion = religion;
		this.nationality = nationality;
		this.origin = origin;
		this.residentAddress = residentAddress;
		
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	public PlaceData getPlaceOfBirth() {
		return this.placeOfBirth;
	}

	public void setPlaceOfBirth(PlaceData placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	
	public String getEthnic() {
		return this.ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

	public OfficeData getReligion() {
		return this.religion;
	}

	public void setReligion(OfficeData religion) {
		this.religion = religion;
	}

	public CountryData getNationality() {
		return this.nationality;
	}

	public void setNationality(CountryData nationality) {
		this.nationality = nationality;
	}

	public PersonInformation getOrigin() {
		return this.origin;
	}

	public void setOrigin(PersonInformation origin) {
		this.origin = origin;
	}

	public Date getDateOfIdIssue() {
		return dateOfIdIssue;
	}

	public void setDateOfIdIssue(Date dateOfIdIssue) {
		this.dateOfIdIssue = dateOfIdIssue;
	}

	public OfficeData getPlaceOfIdIssue() {
		return placeOfIdIssue;
	}

	public void setPlaceOfIdIssue(OfficeData placeOfIdIssue) {
		this.placeOfIdIssue = placeOfIdIssue;
	}

	public PlaceData getResidentPlace() {
		return residentPlace;
	}

	public void setResidentPlace(PlaceData residentPlace) {
		this.residentPlace = residentPlace;
	}

	public AreaData getResidentArea() {
		return residentArea;
	}

	public void setResidentArea(AreaData residentArea) {
		this.residentArea = residentArea;
	}

	public String getResidentAddress() {
		return residentAddress;
	}

	public void setResidentAddress(String residentAddress) {
		this.residentAddress = residentAddress;
	}

	public PlaceData getTmpPlace() {
		return tmpPlace;
	}

	public void setTmpPlace(PlaceData tmpPlace) {
		this.tmpPlace = tmpPlace;
	}

	public AreaData getTmpArea() {
		return tmpArea;
	}

	public void setTmpArea(AreaData tmpArea) {
		this.tmpArea = tmpArea;
	}

	public String getTmpAddress() {
		return tmpAddress;
	}

	public void setTmpAddress(String tmpAddress) {
		this.tmpAddress = tmpAddress;
	}

	public String getSearchName() {
		return searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	public String getOccupation() {
		return occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getOfficeInfo() {
		return officeInfo;
	}

	public void setOfficeInfo(String officeInfo) {
		this.officeInfo = officeInfo;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}
