package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NicTransaction generated by hbm2java
 */
public class RequestCancel implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4030959704968010599L;
    
	private String code;
	private String docType;
	private String docCode;
	private Date dateOfDocIssue;
	private Date dateOfDocExpiry;
	//private String placeIssue;
	private String name;
	private String gender;
	private String dateOfBirth;
	//private PlaceData placeOfBirth;
	//private CountryData nationality;
	private String reason;
	private OfficeData office;
	private String dateOfRegister;

	public RequestCancel() {
	}

	public RequestCancel(String code) {
		this.code = code;
	}

	public RequestCancel(String code, String docType, String docCode, Date dateOfDocIssue, Date dateOfDocExpiry,
			String placeIssue, String name, String gender, String dateOfBirth, PlaceData placeOfBirth,
			CountryData nationality, String reason, OfficeData office, String dateOfRegister) {
		this.code = code;
		this.docType = docType;
		this.docCode = docCode;
		this.dateOfDocIssue = dateOfDocIssue;
		this.dateOfDocExpiry = dateOfDocExpiry;
		//this.placeIssue = placeIssue;
		this.name = name;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		//this.placeOfBirth = placeOfBirth;
		//this.nationality = nationality;
		this.reason = reason;
		this.office = office;
		this.dateOfRegister = dateOfRegister;
		
	}

	public String getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}
	
	public String getDocCode() {
		return this.docCode;
	}

	public void setDocCode(String docCode) {
		this.docCode = docCode;
	}

	public Date getDateOfDocIssue() {
		return this.dateOfDocIssue;
	}

	public void setDateOfDocIssue(Date dateOfDocIssue) {
		this.dateOfDocIssue = dateOfDocIssue;
	}
	
	public Date getDateOfDocExpiry() {
		return this.dateOfDocExpiry;
	}

	public void setDateOfDocExpiry(Date dateOfDocExpiry) {
		this.dateOfDocExpiry = dateOfDocExpiry;
	}

	/*public String getPlaceIssue() {
		return this.placeIssue;
	}

	public void setPlaceIssue(String placeIssue) {
		this.placeIssue = placeIssue;
	}
*/
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	/*public PlaceData getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(PlaceData dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}*/

	/*public CountryData getNationality() {
		return this.nationality;
	}

	public void setNationality(CountryData nationality) {
		this.nationality = nationality;
	}*/

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public OfficeData getOffice() {
		return this.office;
	}

	public void setOffice(OfficeData office) {
		this.office = office;
	}

	public String getDateOfRegister() {
		return this.dateOfRegister;
	}

	public void setDateOfRegister(String dateOfRegister) {
		this.dateOfRegister = dateOfRegister;
	}

	
}
