package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RptStatisticsTransmitData generated by hbm2java
 */
public class RptStatisticsTransmitData implements java.io.Serializable {
    /**
     * 
     */
	public static final String GUI_DL_XNC = "GUI_DL_XNC";
	public static final String NHAN_DL_XNC = "NHAN_DL_XNC";
	public static final String GUI_TT_HC = "GUI_TT_HC";
	public static final String TRA_KQTC = "TRA_KQTC";
	public static final String GUI_GT_MH = "GUI_GT_MH";
	public static final String KY_CA = "KY_CA";
	
    private static final long serialVersionUID = 4030959704968010599L; 
    
    private Long id;
	private String type;
	private String siteCode;
	private Date rptDate;
	private Integer total;
	private Date updateDatetime;
	
	public RptStatisticsTransmitData() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSiteCode() {
		return siteCode;
	}

	public void setSiteCode(String siteCode) {
		this.siteCode = siteCode;
	}

	public Date getRptDate() {
		return rptDate;
	}

	public void setRptDate(Date rptDate) {
		this.rptDate = rptDate;
	}

	public Integer getTotal() {
		return total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public Date getUpdateDatetime() {
		return updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
