
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISoapIdentityService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISoapIdentityService {


    /**
     * 
     * @param info
     * @return
     *     returns org.tempuri.GetIdentityInfoResponse.GetIdentityInfoResult
     */
    @WebMethod(operationName = "GetIdentityInfo", action = "http://tempuri.org/ISoapIdentityService/GetIdentityInfo")
    @WebResult(name = "GetIdentityInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIdentityInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIdentityInfo")
    @ResponseWrapper(localName = "GetIdentityInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIdentityInfoResponse")
    public org.tempuri.GetIdentityInfoResponse.GetIdentityInfoResult getIdentityInfo(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        IdentityRequest info);

    /**
     * 
     * @param info
     * @return
     *     returns org.tempuri.GetIdentityInfoAdvanceResponse.GetIdentityInfoAdvanceResult
     */
    @WebMethod(operationName = "GetIdentityInfoAdvance", action = "http://tempuri.org/ISoapIdentityService/GetIdentityInfoAdvance")
    @WebResult(name = "GetIdentityInfoAdvanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIdentityInfoAdvance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIdentityInfoAdvance")
    @ResponseWrapper(localName = "GetIdentityInfoAdvanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIdentityInfoAdvanceResponse")
    public org.tempuri.GetIdentityInfoAdvanceResponse.GetIdentityInfoAdvanceResult getIdentityInfoAdvance(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        IdentityAdvanceRequest info);

}
