package com.nec.asia.nic.comp.trans.domain;
// Generated Jan 20, 2016 11:25:39 AM by Hibernate Tools 4.3.1.Final

/**
 * NicTransactionReconRptId generated by hbm2java
 */
@Deprecated
public class NicTransactionReconRptId implements java.io.Serializable {

    private String regSiteCode;

    private String issSiteCode;

    private String applicationDate;

    private String collectionDate;

    public NicTransactionReconRptId() {
    }

    public NicTransactionReconRptId(String regSiteCode, String issSiteCode, String applicationDate, String collectionDate) {
        this.regSiteCode = regSiteCode;
        this.issSiteCode = issSiteCode;
        this.applicationDate = applicationDate;
        this.collectionDate = collectionDate;
    }

    public String getRegSiteCode() {
        return this.regSiteCode;
    }

    public void setRegSiteCode(String regSiteCode) {
        this.regSiteCode = regSiteCode;
    }

    public String getIssSiteCode() {
        return this.issSiteCode;
    }

    public void setIssSiteCode(String issSiteCode) {
        this.issSiteCode = issSiteCode;
    }

    public String getApplicationDate() {
        return this.applicationDate;
    }

    public void setApplicationDate(String applicationDate) {
        this.applicationDate = applicationDate;
    }

    public String getCollectionDate() {
        return this.collectionDate;
    }

    public void setCollectionDate(String collectionDate) {
        this.collectionDate = collectionDate;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof NicTransactionReconRptId))
            return false;
        NicTransactionReconRptId castOther = (NicTransactionReconRptId) other;

        return ((this.getRegSiteCode() == castOther.getRegSiteCode())
            || (this.getRegSiteCode() != null && castOther.getRegSiteCode() != null && this.getRegSiteCode().equals(castOther.getRegSiteCode())))
            && ((this.getIssSiteCode() == castOther.getIssSiteCode())
                || (this.getIssSiteCode() != null && castOther.getIssSiteCode() != null && this.getIssSiteCode().equals(castOther.getIssSiteCode())))
            && ((this.getApplicationDate() == castOther.getApplicationDate())
                || (this.getApplicationDate() != null && castOther.getApplicationDate() != null && this.getApplicationDate().equals(castOther.getApplicationDate())))
            && ((this.getCollectionDate() == castOther.getCollectionDate())
                || (this.getCollectionDate() != null && castOther.getCollectionDate() != null && this.getCollectionDate().equals(castOther.getCollectionDate())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getRegSiteCode() == null ? 0 : this.getRegSiteCode().hashCode());
        result = 37 * result + (getIssSiteCode() == null ? 0 : this.getIssSiteCode().hashCode());
        result = 37 * result + (getApplicationDate() == null ? 0 : this.getApplicationDate().hashCode());
        result = 37 * result + (getCollectionDate() == null ? 0 : this.getCollectionDate().hashCode());
        return result;
    }

}
