
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentityService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.3.30.79/CMND/IdentityService.svc?wsdl")
public class IdentityService
    extends Service
{

    private final static URL IDENTITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException IDENTITYSERVICE_EXCEPTION;
    private final static QName IDENTITYSERVICE_QNAME = new QName("http://tempuri.org/", "IdentityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.3.30.79/CMND/IdentityService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTITYSERVICE_WSDL_LOCATION = url;
        IDENTITYSERVICE_EXCEPTION = e;
    }

    public IdentityService() {
        super(__getWsdlLocation(), IDENTITYSERVICE_QNAME);
    }

    public IdentityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTITYSERVICE_QNAME, features);
    }

    public IdentityService(URL wsdlLocation) {
        super(wsdlLocation, IDENTITYSERVICE_QNAME);
    }

    public IdentityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTITYSERVICE_QNAME, features);
    }

    public IdentityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoapIdentityService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoapIdentityService")
    public ISoapIdentityService getBasicHttpBindingISoapIdentityService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISoapIdentityService"), ISoapIdentityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoapIdentityService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISoapIdentityService")
    public ISoapIdentityService getBasicHttpBindingISoapIdentityService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISoapIdentityService"), ISoapIdentityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTITYSERVICE_EXCEPTION!= null) {
            throw IDENTITYSERVICE_EXCEPTION;
        }
        return IDENTITYSERVICE_WSDL_LOCATION;
    }

}
