package com.nec.asia.nic.framework.admin.code.domain;

// Generated Jan 20, 2016 3:28:44 PM by Hibernate Tools 4.3.1.Final

/**
 * CodeValuesId generated by hbm2java
 */
public class CodeValuesId implements java.io.Serializable {

    private String codeId;

    private String codeValue;

    public CodeValuesId() {
    }

    public CodeValuesId(String codeId, String codeValue) {
        this.codeId = codeId;
        this.codeValue = codeValue;
    }

    public String getCodeId() {
        return this.codeId;
    }

    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    public String getCodeValue() {
        return this.codeValue;
    }

    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CodeValuesId))
            return false;
        CodeValuesId castOther = (CodeValuesId) other;

        return ((this.getCodeId() == castOther.getCodeId()) || (this.getCodeId() != null && castOther.getCodeId() != null && this.getCodeId().equals(castOther.getCodeId())))
            && ((this.getCodeValue() == castOther.getCodeValue()) || (this.getCodeValue() != null && castOther.getCodeValue() != null && this.getCodeValue().equals(castOther.getCodeValue())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getCodeId() == null ? 0 : this.getCodeId().hashCode());
        result = 37 * result + (getCodeValue() == null ? 0 : this.getCodeValue().hashCode());
        return result;
    }

}
